jac-uk/admin

- .firebaserc
- README.md
- firebase.json
A couple of minor things I missed.
> Readme update

- src/components/NewExercise/NewExerciseName.vue
- src/components/NewExercise/NewExerciseType.vue
- src/store/createExercise.js
- src/views/CreateExercise.vue
- tests/unit/components/NewExercise/NewExerciseName.spec.js
- tests/unit/components/NewExercise/NewExerciseType.spec.js
- tests/unit/store/createExercise.spec.js
- tests/unit/views/CreateExercise.spec.js
**Change log**
1. Add new component for ExerciseType
2. Include it into CreateExercise view and make it visible if title is available in a store
3. When type is added, reset state
> Add type component to the application form

- src/router.js
- src/views/Eligibility.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/Eligibility.spec.js
TODO:
- Plug the form into the database.
- Add Ollie's reusable components when they're ready.
- Have the submit button move to the next step.
This was copied and pasted directly from the prototype, and the happy path tests were adapted from the ViewExercise template.
> Scaffold the Eligibility view

- src/router.js
- src/views/AboutTheRole.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/AboutTheRole.spec.js
TODO:
- Plug the form into the database.
- Add Ollie's reusable components when they're ready.
This was copied and pasted directly from the prototype, and the happy 
path tests were adapted from the ViewExercise template. Tests include 
happy path, and unauthenticated user redirect tests.
> Scaffold the About The Role view

- src/router.js
- src/views/CreateAnExercise.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/AboutTheRole.spec.js
- tests/unit/views/CreateAnExercise.spec.js
I've scaffolded the Create an Exercise page - it has passing Journey and View tests. 
please note - in this PR, I have also changed the tests for the About The Role page (./tests/unit/views/AboutTheRole.spec.js), as these were incorrect in that approved PR.
> Scaffold create an exercise

- src/router.js
- src/views/AboutTheSelectionProcess.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/AboutTheSelectionProcess.spec.js
Please note - in the signin.spc.js file, I noticed I was missing the redirect to sign in tests for 2 pages, so I've just added those in.
> Scaffold the About The Selection Process page

- package-lock.json
Update version to resolve a critical vulnerability
> Update eslint-utils version

- src/components/Form/README.md
> Add documentation for DateInput and TimeInput

- src/components/Form/README.md
- Added some details for the text field component to the Form file 
README that Alex made.
> Added Text Field Documentation

- src/App.vue
- src/main.scss
- src/views/Dashboard.vue
- tests/unit/views/Dashboard.spec.js
**Change log**
Update styling and move buttons to the top as per prototype.
> Update Dashboard page styling

- src/components/Form/CheckboxGroup.vue
- src/components/Form/RadioGroup.vue
Change the class of legend element.
> Make legend smaller in Radio and Checkbox groups

- src/router.js
- src/views/AddExerciseContacts.vue
- src/views/AddShortlistingMethods.vue
- src/views/CreateAnExercise.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/AddShortlistingMethods.spec.js
Added our components to the shortlisting methods page. Also added a pathway to our router. All tests are passing, and code has been linted. 
- Need to link it up to the AddExerciseContacts page via 'save and continue' button. 
- Need to have the 'save and continue' button point to the next page.
> Scaffold shortlisting methods

- src/main.scss
- src/views/CreateAnExercise.vue
- Added a dummy ref number in to the Create an Exercise page.
- It's a hard coded component. Copied the format Kellie used in the prototype but tried to tidy it up a bit so it's inline with our components. 
Please let me know if there's anything that needs changing as I wasn't too sure about how much I could clean up 🌻
> Dummy Ref Number

- src/views/AddExerciseContacts.vue
- src/views/CreateAnExercise.vue
- tests/unit/views/AddExerciseContacts.spec.js
- tests/unit/views/CreateAnExercise.spec.js
- Added routing for the current three pages.
- Added tests to the Views folder for these pages. 
- Run lint, Tests pass.
> Added Button Routing and Tests.

- src/components/Form/DateInput.vue
- src/components/Form/TimeInput.vue
- src/router.js
- src/views/AddExerciseTimeline.vue
- src/views/AddShortlistingMethods.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/AddExerciseTimeline.spec.js
Created a new page with new components in accordance with the latest prototype. 
Tests have been created and are passing.
All code has been linted.
Need to: 
- Add functionality to the 'add another' links.
- Modify the TimeInput component to have little colons in between the time fields.
> Scaffold Add Exercise Timeline

- src/router.js
- src/views/Exercises/Edit/Eligibility.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/Exercises/Edit/Eligibility.spec.js
A second attempt at making the Eligibility page.  This page follows the requirements of Prototype V2.1, along with the new patterns in the code base. 
- Journey and View tests added for the eligibility page.
- Routing added to the router for the eligibility page.
- Passed code through the linter.
- All tests are passing.
> Eligibility Retry

- src/views/Exercises/Edit/Shortlisting.vue
- Refactored the Shortlisting page inline with the V2.1 Prototype. 
- Renamed the other v-model field to be more descriptive. 
- Tests still passing.
- Code has been linted.
> Amended the Shortlisting page

- src/components/RepeatableFields.vue
- src/components/RepeatableFields/SelectionDay.vue
- src/views/Exercises/Edit/Timeline.vue
- tests/unit/components/RepeatableFields.spec.js
- tests/unit/components/RepeatableFields/SelectionDay.spec.js
- tests/unit/views/Exercises/Edit/Timeline.spec.js
This PR adds the main component for Repeatablefields, and adds a reusable field for a SelectionDay to the Timeline page.
PR for repeatable Textinput is upcoming. 
1) Add Repeatablefields component and tests
2) Create SelectionDay component
3) Integrate SelectionDay repeatable component into a Timeline page
> Repeatable fields

- src/views/Exercises/New.vue
- tests/unit/views/Exercises/New.spec.js
- Edited components to meet new requirements.
- Edited the save method to not record a type of exercise. 
- Edited the tests to not expect an exercise type. 
- Run linter on code. 
- All tests pass.
> Edited Create Exercise page in line with Prototype V2.1

- src/components/RepeatableFields/SelectionDay.vue
- src/views/Exercises/Edit/Timeline.vue
Updated the Timeline page to match the Prototype V2.1
- Rearranged and edited components as required.
- Added navigation functionality to the buttons. 
- Added a location textfield component into the SelectionDay component.
- Code has been linted
- Tests are passing. 
Note: 
- What do we think about the v-Model naming? With the Situational Judgement and Critical Analysis tests sharing a field, it's been hard to come up with a comprehensive name for them. 
thanks 😎 💻 🖥 📱
> V2.1 timeline

- src/components/LoadingMessage.vue
- src/views/Exercises/Edit.vue
- tests/unit/components/LoadingMessage.spec.js
- tests/unit/views/Exercises/Edit.spec.js
**Change log:** 
1) Add LoadingMessage component
> Create Edit page

- src/components/Form/Currency.vue
- src/components/Form/TextField.vue
- src/views/Exercises/Edit/About.vue
- tests/unit/components/Form/Currency.spec.js
Created a currency component based off the TextField component 
Isn't it cute? 
- The components follows the same formatting as Textfield however it doesn't take in an optional input class and it expects a number. 
- The tests are also copied from the Textfield component but have been edited accordingly to fit the component. 
- The styling has been added into the component's scoped style tags, and this has been copied from the MOJ css file (Sorry this whole component basically isn't my work lol) 
Let me know if anything needs to change or if I've missed anything! 
🌻
> Currency component

- src/components/RepeatableFields/OtherShortlistingMethod.vue
- src/views/Exercises/Edit/Shortlisting.vue
- tests/unit/components/RepeatableFields/RepeatableTextFields.spec.js
- tests/unit/views/Exercises/Edit/Shortlisting.spec.js
Super cutesie page that saves data to the database. 
- Added a Form tag to the page and amended its inners to be in line with the contacts page. 
-Also had to make a sneaky 'OtherShortlistingMethod' component cause I forgot it. ooopssss. 
🌻
> Saving Shortlisting

- src/views/Exercises/Edit/Vacancy.vue
- tests/unit/views/Exercises/Edit/Vacancy.spec.js
Added database functionality to the Vacancy page. Data saves to the database and tests are all passing, everything is dandy.
Note - 
This page has the file uploads on, that's still currently doing nothing but that's fine 
🌻
> Saving Vacancy

- src/views/Exercises/Edit/Eligibility.vue
- src/views/Exercises/Edit/Vacancy.vue
- tests/unit/views/Exercises/Edit/Eligibility.spec.js
Created amendments to the Eligibility page in order to add save to database functionality 
- Tests are passing
- Code has been linted
🌻
> Saving Eligibility

- src/components/Page/Navigation.vue
- src/main.scss
- src/views/Exercises/Show/Overview.vue
- tests/unit/views/Exercises/Show/Overview.spec.js
1) Add Overview page
2) Add classes into CSS for sections with grey and blue background
> Add Show Overview page

- src/views/Dashboard.vue
- src/views/Exercises/Show/Contacts.vue
- tests/unit/views/Exercises/Show/Contacts.spec.js
**Change log**
Add Show Contacts page
> Add Show Contacts page

- src/helpers/formatDate.js
- src/views/Exercises/Show/Timeline.vue
- tests/unit/helpers/formatDate.spec.js
- tests/unit/views/Exercises/Show/Timeline.spec.js
**Change log**
Add Timeline show page
> Add Timeline show page

- src/views/Exercises/Edit/Shortlisting.vue
- src/views/Exercises/Show/Shortlisting.vue
- tests/unit/views/Exercises/Show/Shortlisting.spec.js
- Amended the Edit Shortlisting page. The Values are now equal to the 
same string that Label is equal to, in order to have human- readable 
variables. Doesn't iterate correctly though. 
- Copied and amended the HTML from Alex's Contacts page. Have not made 
any changes to the CSS so could still have the wrong details for that. 
- Added tests for the Shortlisting Show page. all passing. 
- Code has been linted.
> Added a Show shortlisting page

- src/views/Exercises/Show/Contacts.vue
- src/views/Exercises/Show/Vacancy.vue
- tests/unit/views/Exercises/Show/Vacancy.spec.js
**Change log**
Add show Vacancy page
> Create show vacancy

- src/components/Form/TextareaInput.vue
- src/views/Exercises/Edit/Eligibility.vue
- src/views/Exercises/Edit/Vacancy.vue
- src/views/Exercises/Show/Eligibility.vue
- tests/unit/components/Form/TextareaInput.spec.js
Using the TextField component as a guide, I've created a TextareaInput component, that by default allows 5 rows of text. 
- Tests have been created and are passing, 
- Code has been linted,
- TextareaInput component has been added to the Vacancy-edit and Eligibility-edit pages to replace the hardcoded versions that were implemented on those pages beforehand. 
🍁
> Textarea Input Component

- src/views/Exercises/Edit/Timeline.vue
- tests/unit/views/Exercises/Edit/Timeline.spec.js
**Change log**
Timeline edit page:
1. Add computed properties to get selected shortlisting methods
2. Render date fields for only selected shortlisting methods
> Conditionally render timeline shortlisting fields

- src/components/Page/AddToFavouritesButton.vue
- src/views/Exercises/Show.vue
- tests/unit/components/Page/AddToFavouritesButton.spec.js
- tests/unit/views/Exercises/Show.spec.js
This PR adds "Add to favourites" component.
As currently, we don't have user roles or records associated with users, this PR just adds "updateFavoutites" method which can be used in the future.
Change log:
1) Add "Add to favourites" component
2) Use it on Edit page
> Add to favourites component

- src/views/Exercises/New.vue
- tests/unit/views/Exercises/New.spec.js
**Change log**
Add BackLink component to CreateExercise page
> Use BackLink component on CreateExercise page

- src/router.js
- src/views/Exercises/Edit/EditName.vue
- src/views/Exercises/Show.vue
- tests/unit/journeys/page-titles.spec.js
- tests/unit/journeys/signin.spec.js
- tests/unit/views/Exercises/Edit/EditName.spec.js
- tests/unit/views/Exercises/Show.spec.js
This PR adds an Edit page for a name of the exercise. 
1) Add Update Name page 
2) Place a link to this page under the exercise name on Show overview page
> Add Edit Name view

- .eslintrc
- src/router.js
- src/views/Exercises/Show/Contacts.vue
- src/views/SignIn.vue
- tests/unit/components/Form/TimeInput.spec.js
**Change log**
Add a rule to eslint config that removes empty lines (in case if there are more than one line)
> Add eslint rule to remove extra empty lines

- src/helpers/Timeline/createTimeline.js
- src/helpers/Timeline/exerciseTimeline.js
- src/helpers/isDate.js
- src/views/Exercises/Show/Overview.vue
- src/views/Exercises/Show/Timeline.vue
- tests/unit/helpers/Timeline/createTimeline.spec.js
- tests/unit/helpers/Timeline/exerciseTimeline.spec.js
- tests/unit/helpers/isDate.spec.js
- tests/unit/views/Exercises/Show/Overview.spec.js
- tests/unit/views/Exercises/Show/Timeline.spec.js
This PR adds helper methods for creating timeline functionality and adds an Exercise Timeline builder.
1) Add Exercise Timeline builder (exerciseTimeline.js)
2) Use helper methods to remove entries with invalid dates from the timeline
3) Use exerciseTimeline builder on Overview and Timeline show pages
> Generate timeline

- src/helpers/Timeline/exerciseTimeline.js
- src/views/Exercises/Edit/Timeline.vue
- src/views/Exercises/Show/Vacancy.vue
- tests/unit/views/Exercises/Edit/Timeline.spec.js
1) Add InputDate for paperSift if paperSift is selected as a shortlisting method, add paperSift to timeline
2) Remove duplicate from Show page
> Add block for paperSift on Timeline page

- package-lock.json
- package.json
- src/main.js
- src/router.js
Added Sentry to help monitor bugs
> Added Sentry to the Project

- src/views/Exercises/Edit/Vacancy.vue
This PR contains all amendments to the Vacancy Information page. This work equates to multiple tickets.
Things that have been completed: 
- Added an additional option of 'Leadership - non legal' to the 'Type of exercise question. 
Code has been linted
Tests have been written and are passing.
> Amendments to the Vacancy Information page

- src/router.js
- src/views/Exercises/ApplicationsFull.vue
- src/views/Exercises/Show/Applications.vue
- tests/unit/views/Exercises/Show/Applications.spec.js
Made a dummy applications page to match claire's mock up. 
It currently does nothing. 
there's one test to check it renders the component, cause it doesn't do anything.
> Applications page

- src/views/Exercises/Show.vue
Added two additional links to the show page's nav bar. 
These pages haven't been made yet. 
Tests have been amended and re passing, and code has been linted.
> Added additional links to the show page main nav bar

- src/views/Exercises/Reports/CharacterIssues.vue
Added details to the character issues page. 
No tests as it's only a placeholder and is likely to change.
> Added scaffolding to the Character Issues page

- package-lock.json
Updated package-lock file...but also testing a merge to master
> Update package-lock following fresh install

- src/test2.txt
- src/views/Exercises/New.vue
- tests/unit/views/Exercises/New.spec.js
> test circleci

- src/store/exercise/document.js
- src/views/Dashboard.vue
- src/views/Exercises/Show.vue
- tests/unit/store/exercise/document.spec.js
Show exercise reference number on dashboard and exercise cover page
Include back navigation
> Create unique reference number for exercise

- src/views/Exercises/Edit/Contacts.vue
- src/views/Exercises/Edit/Eligibility.vue
- src/views/Exercises/Edit/Shortlisting.vue
- src/views/Exercises/Edit/Vacancy.vue
- Renamed the values on the checkboxes and radio buttons back to kebab case.
> Amended the apply-admin app variables

- src/views/Exercises/Show/Vacancy.vue
Show download links in the Vacancy detail page for uploaded files:
- Job Description
- Terms and Conditions
> show uploaded items in vacancy details page

- src/views/Exercises/Show.vue
- src/views/Exercises/Show/Vacancy.vue
- fix '..' in exercise name if exercise is less than 80 characters
- style job description and terms and condtions uploaded templates to look like hyperlinks
> fix small things

- src/components/Page/Navigation.vue
- src/main.js
- src/router.js
- src/views/Exercises/Edit/AssessmentOptions.vue
- src/views/Exercises/Edit/Downloads.vue
- src/views/Exercises/Edit/Vacancy.vue
- src/views/Exercises/Edit/WorkingPreferences.vue
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/AssessmentOptions.vue
- src/views/Exercises/Show/Downloads.vue
- src/views/Exercises/Show/Overview.vue
- src/views/Exercises/Show/WorkingPreferences.vue
Include Assessment Options, Exercise Downloads and Working Preferences pages ready for further development.
Remove 'additional information' header from Vacancy information form
> Exercise form additions

- src/views/Exercises/Edit/AssessmentOptions.vue
Added radio buttons to the Assessment options page. 
Saving to the database functionality works.
> Assessment Options. New form to collect assessment options

- src/views/Exercises/Edit/Downloads.vue
- src/views/Exercises/Edit/Vacancy.vue
- src/views/Exercises/Show/Downloads.vue
- src/views/Exercises/Show/Vacancy.vue
- Deleted file upload widgets from Vacancies page
- Moved file upload widgets into Downloads page
> Move File Upload widgets to Exercise Downloads

- src/App.vue
- src/store/auth.js
- src/views/SignIn.vue
* Also display logged in user name
> Admin login security

- src/filters.js
- src/views/Exercises/Edit/Eligibility.vue
- src/views/Exercises/Edit/Vacancy.vue
- src/views/Exercises/Show/AssessmentOptions.vue
- src/views/Exercises/Show/Eligibility.vue
- src/views/Exercises/Show/Shortlisting.vue
- src/views/Exercises/Show/Vacancy.vue
Eligibility improvements including:
- Show correct fields depending upon type of exercise
- Ensure numerical options are stored as numbers and 'Other' fields collect number type data
- Improve view page and use lookups
Also include lookup for dropdown, radio and checkbox values and apply to:
- Vacancy
- Assessment Options
- Shortlisting
> Eligibility improvements

- src/components/RepeatableFields/SelectionExerciseManager.vue
- src/components/RepeatableFields/SeniorSelectionExerciseManager.vue
- src/views/Exercises/Edit/Contacts.vue
- src/views/Exercises/Show/Contacts.vue
- Added Senior Selection Exercise Manager and Selection Exercise Manager to the Repeatable Fields components. 
- Imported and used these RF components on the Edit/Contacts page.
- Amended the rendering of these RF components on the Show/Contacts page.
> Added two Repeatable Fields components to the contacts page

- src/helpers/Timeline/exerciseTimeline.js
- exerciseTimeline.js has been amended to include multiple selection days.
- Added a for loop to iterate through all the selection days entered.
> Amended the Timeline to include multiple selection days

- src/filters.js
- src/views/Exercises/Edit/AssessmentOptions.vue
- Also added the option to the lookup filter
> Added additional option to the Assessment Options page

- src/views/Exercises/Edit/Timeline.vue
- Added some computed properties that conditionally render the shortlisting methods in the timeline Edit page.
> Added functionality to conditionally render the shortlisting methods on the Timeline/Edit page

- src/filters.js
- src/views/Exercises/Edit/Eligibility.vue
- src/views/Exercises/Show/Eligibility.vue
- Added a checkbox to check authorisations.
- Added this new section to the Eligbility show page.
- Added the new options to the filter.
> Added additional question to the Eligibility Edit page

- src/helpers/Timeline/exerciseTimeline.js
- src/views/Exercises/Edit/Timeline.vue
- I've added end dates to the shortlisting methods.
- I've shown these end dates on the timeline. 
- I've refactored the timeline to only show 'to and from' dates if they're different days. This applies to Selection Day and Shortlisting methods.
> Added end dates to the shortlisting methods and amended timeline

- src/components/DownloadLink.vue
- src/helpers/Timeline/exerciseTimeline.js
- src/main.js
- Fixed the timeline errors by added the selectiondays code and the shortlisting methods code into if statements that check that the required data exists. This is because they're not 'secretly vetted' like the stuff in the timeline component. 
- Fixed a DownloadLink bug that appeared after this, as we were passing in the wrong default to the downloadlink component. Before we had passed in a default of null, but we've specified that the type should be string. To fix the error, we've made the default an empty string.
> Timeline de bug and Download de bug

- src/views/Exercises/Edit/Contacts.vue
Added a new 'HMCTS or Welsh Government contact' field below the 'HMCTS or Welsh Government lead contact'
> Contacts. Add new 'HMCTS or Welsh Government contact' field

- src/views/Exercises/Edit/Downloads.vue
As requested, I've added the download file variables to the default object listed on the page. 
Not sure If I've done this right so best to check just in case
> Not a ticket: Added the Download files to the defaults

- src/App.vue
- src/components/RepeatableFields/SelectionCriterion.vue
- src/views/Exercises/Edit/Eligibility.vue
- src/views/Exercises/Show/Eligibility.vue
Admin: Does ASC apply? needs a repeatable field within it.
__________________________________
Admin: ELIGIBILITY PAGE
Does additional selection criteria (ASC) apply?
-Yes
Additional skills and experience 
TITLE
TEXTAREA
Add another (button) 
-No 
________________________________
- Also edited the rendering of the eligibility show page to show multiple title-text answers. 
- Added a max of 2
- Let me know about naming conventions - this one was hard.
> ADMIN SIDE: Statement of Suitability - Rework on layout

- src/App.vue
Reverts jac-uk/apply-admin#184
> Revert "Header"

- src/components/Form/FileUpload.vue
- src/components/RepeatableFields.vue
- src/components/RepeatableFields/JobDescriptionFileUpload.vue
- src/views/Exercises/Edit/Downloads.vue
- src/views/Exercises/Show/Downloads.vue
- Amended Edit/Downloads to include the FileUpload component.
- Amended the Save method on the edit Downloads page.
- Amended the Show/Downloads page to accommodate new changes.
> File Uploads

- package.json
Tweaks around development environment
> Development environment

- src/filters.js
- src/main.js
- src/views/Exercises/Show/Applications.vue
- tests/unit/views/Exercises/Show/Applications.spec.js
Added date of birth and selected diversity fields to `contacts.csv` for online qualifying.
> #345 Added diversity fields to contacts.csv

- src/components/RepeatableFields.vue
- src/components/RepeatableFields/Answer.vue
- src/components/RepeatableFields/Membership.vue
- src/views/Exercises/Edit/Eligibility.vue
- tests/unit/components/RepeatableFields.spec.js
* "id required" warning in tests
* check for otherMemberships existence
> #347 Bug fixes

- src/views/Exercises/Edit/Downloads.vue
Uncommented uploading files other than "job description"
> Re-enabled file uploads

- src/components/Form/FileUpload.vue
- src/components/RepeatableFields.vue
- src/components/RepeatableFields/MultiFileUpload.vue
- src/store/exercise/document.js
- src/views/Exercises/Edit/Downloads.vue
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/AssessmentOptions.vue
- src/views/Exercises/Show/Contacts.vue
- src/views/Exercises/Show/Downloads.vue
- src/views/Exercises/Show/Eligibility.vue
- src/views/Exercises/Show/Shortlisting.vue
- src/views/Exercises/Show/Summary.vue
- src/views/Exercises/Show/Timeline.vue
- src/views/Exercises/Show/Vacancy.vue
- src/views/Exercises/Show/WorkingPreferences.vue
- tests/unit/components/Form/FileUpload.spec.js
- tests/unit/components/RepeatableFields/MultiFileUpload.spec.js
- tests/unit/components/RepeatableFields/RepeatableTextFields.spec.js
- tests/unit/components/RepeatableFields/SelectionDay.spec.js
- tests/unit/views/Exercises/Edit/Downloads.spec.js
- tests/unit/views/Exercises/Show/Downloads.spec.js
All sections of "Exercise downloads" can now upload multiple files using the improved FileUpload component.
> Improved file uploads

- package-lock.json
- package.json
- src/App.vue
- src/styles/main.scss
First attempt at implementing changes from the prototype, changes made to App.vue and main.css.
Added MOJ design system to package.json
> header updated

- src/helpers/constants.js
- src/views/Exercises/Show.vue
This is the first task of some other that we need to do in order to allow the user to witdrawn an application.
This simply searches the database for application that have the status as `withdrawn`
> 441 Added the application heading on the right side

- package-lock.json
- src/components/Page/Navigation.vue
- src/filters.js
- src/helpers/constants.js
- src/router.js
- src/store.js
- src/store/stage/handover.js
- src/store/stage/recommended.js
- src/store/stage/review.js
- src/store/stage/selected.js
- src/store/stage/shortlisted.js
- src/views/Exercises/Show.vue
- src/views/Exercises/Stages.vue
- src/views/Exercises/Stages/HandoverList.vue
- src/views/Exercises/Stages/RecommendedEdit.vue
- src/views/Exercises/Stages/RecommendedList.vue
- src/views/Exercises/Stages/ReviewEdit.vue
- src/views/Exercises/Stages/ReviewList.vue
- src/views/Exercises/Stages/SelectedEdit.vue
- src/views/Exercises/Stages/SelectedList.vue
- src/views/Exercises/Stages/ShortlistEdit.vue
- src/views/Exercises/Stages/ShortlistList.vue
Initial views for all exercise stages and editing application status
> Scaffolding for exercise stages and application statuses

- src/helpers/constants.js
- src/store/stage/handover.js
- src/views/Exercises/Stages/HandoverList.vue
This is to add the handover to the DB
> #439 add HANDOVER to the DB

- src/App.vue
- src/components/Page/TabsList.vue
- src/router.js
- src/store.js
- src/store/notifications.js
- src/views/NotificationsList.vue
- src/views/Sandbox.vue
- tests/unit/components/Form/TabsList.spec.js
- tests/unit/helper.js
Include notifications queue.
Admins can:
- see what's about to be sent out
- see what's already been sent out
> #474 Notifications

- src/store/stage/recommended.js
- src/store/stage/review.js
- src/store/stage/selected.js
- src/store/stage/shortlisted.js
- src/views/Exercises/Stages/ReviewEdit.vue
On this commit I am moving the Stage from REVIEW to SHORTLISTED.
> #451 Review Status moved to Shortlisted

- src/components/ActionButton.vue
- src/filters.js
- src/views/Exercises/Show/IndependentAssessments.vue
> 488 assessments changes

- src/components/Page/Banner.vue
- src/router.js
- src/store/stage/review.js
- src/store/stage/selected.js
- src/views/Exercises/Show.vue
- src/views/Exercises/Stages/ReviewEdit.vue
- src/views/Exercises/Stages/ReviewList.vue
- src/views/Exercises/Stages/SelectedList.vue
- src/views/Sandbox.vue
- tests/unit/components/Page/Banner.spec.js
> Revert "Feature/#528/banner infomation status"

- src/views/Exercises/Stages/HandoverList.vue
- src/views/Exercises/Stages/RecommendedList.vue
- src/views/Exercises/Stages/ReviewList.vue
- src/views/Exercises/Stages/SelectedList.vue
- src/views/Exercises/Stages/ShortlistList.vue
Updated instances of the Banner with the correct `status` prop.
> #503 Set banner status on lists

- src/views/Exercises/Stages/HandoverList.vue
- src/views/Exercises/Stages/RecommendedList.vue
- src/views/Exercises/Stages/ReviewList.vue
- src/views/Exercises/Stages/SelectedList.vue
- src/views/Exercises/Stages/ShortlistList.vue
Adding the ISSUES column to all stages
REVIEW
SHORTLISTED
SELECTED
RECOMMENDED
HANDOVER
> #454 Added Issues column to all stages

- src/store/stage/review.js
- src/views/Exercises/Stages/ReviewEdit.vue
- Conditionally send `empApplied` parameter
- Check for null rather than empty string
- Updated variable names to more closely match data model
> #455 Couple of tweaks to EMP:

- src/App.vue
- src/filters.js
- src/router.js
- src/store.js
- src/store/candidates.js
- src/views/Candidates/Candidates.vue
- src/views/Candidates/CandidatesList.vue
This PR adds a Candidate List page at the top level
> #509 Add a candidate list page

- src/App.vue
- src/filters.js
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/Reports/Diversity.vue
- Diversity report shows data for all exercise stages.
- Data for each stage can be exported
- Data for all stages can be exported
- Print view tidied slightly
Example exercise on develop: exercises/wdpALbyICL7ZxxN5AQt8/reports/diversity
> #356 Diversity report shows data for each exercise stage

- src/components/Candidates/CharacterInformation.vue
This PR fixes an error on the Candiades Page Details
> #509 fix the component error on the Applications page

- src/views/Exercises/Tasks/IndependentAssessments.vue
Also 
- removed some old code
- #583 Remove selected option from dropdown when beginning IAs
> #581 Can only cancel assessments before sent

- src/components/Candidates/PersonalDetails.vue
- src/store/candidates.js
- src/views/Candidates/CandidatesView.vue
Added the possibility of editing the name and email directly on the Candidate detail page.
> #513 Edit Email and Name on the Candidate Detail page

- src/components/Notes/Notes.vue
- src/components/Notes/NotesList.vue
- src/components/Notes/NotesNew.vue
- src/store.js
- src/store/candidates.js
- src/store/notes.js
- src/views/Candidates/CandidatesView.vue
- Removed files from Candidates
- Created a store for notes
- Ability to EDIT and DELETE
This PR doesn't include the design for the DELETE note (in progress)
> #514 Notes

- src/router.js
- src/views/Exercises/Applications/Application.vue
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/Applications.vue
Hey @tomlovesgithub please consider my changes here. Have added a new route, which might be slightly whiffy, but it should enable the navigation to show the correct active page for applications.
> #564 Application route including status

- src/components/EditableField.vue
- src/store/application.js
- src/views/Exercises/Applications/Application.vue
Possibilty of changing details of the Assessors
Added a new shared component EditableField.vue
> #626  New component for Editable Fields

- src/views/Exercises/Applications/Application.vue
http://localhost:8080/exercises/wdpALbyICL7ZxxN5AQt8/applications/draft/application/LZxWU3IM2DsaMg7Hb1qS
> #633 Add telephone to Candidate Assessor Details

- src/helpers/Timeline/exerciseTimeline.js
- src/views/Exercises/Edit/Timeline.vue
- src/views/Exercises/Tasks/CharacterChecks.vue
Return date in timeline and character checks task
> Added character checks return date to timeline

- src/components/Candidates/PersonalDetails.vue
- src/components/EditableField.vue
- src/views/Exercises/Applications/Application.vue
- Added a label to the Personal Details that needs review "Change details updates the candidate information"
- The updates works on the following way:
- Updates to the Application Personal Details will update the candidate Personal Details
- Updates to candidate Personal Details will not update the Application Personal Details
Next work on this if required:
- Update citizenship
- Update Reasonable adjustments (2 fields)
> #659 Change Candidate Details

- src/components/Candidates/PersonalDetails.vue
- src/views/Exercises/Applications/Application.vue
Changed the text as per Claire's review
> #659 Change the text copy as per review

- src/router.js
- src/store/applications.js
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/Reports/Agency.vue
#520 + #521 - character checks agency report
> Agency report

- src/views/Exercises/Applications/AgencyReport.vue
- src/views/Exercises/Applications/Application.vue
- src/views/Exercises/Show/Reports/Agency.vue
#523
plus small fix for the Agency report
> Agency tab in candidate record

- src/components/Page/Table/Table.vue
- src/helpers/constants.js
- src/router.js
- src/store/stage/handover.js
- src/styles/main.scss
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/Reports/Diversity.vue
- src/views/Exercises/Show/Reports/Handover.vue
- tests/unit/components/Page/Navigation.spec.js
- tests/unit/views/Exercises/Show/Applications.spec.js
#663 Handover report page
+ fixed some tests displaying warnings
> Handover report

- src/App.vue
- src/views/Exercises/Applications/Application.vue
Oops, another fix for the footer, found that it overlaps the exercise at the very bottom of the page, can be seen here.
https://admin-staging.judicialappointments.digital/dashboard
Fixed by padding the main content.
> Add padding to page content so footer doesnt overlap

- src/views/Exercises/Edit/Timeline.vue
- src/views/Exercises/Tasks/IndependentAssessments.vue
- Optional field in Timeline to add the hard limit (with updated hints) 
- Conditionally displays in the IA task
> #712 - Add optional IA Hard Limit field

- src/components/Form/FileUpload.vue
- tests/unit/components/Form/FileUpload.spec.js
Updates  the extensions allowed on admin.
> #722 - Update allowed file extensions

- src/App.vue
> Resurrected footer fix

- src/views/Exercises/Applications/Application.vue
Add "print-none" to IA email row to remove it from print formatting function
> include IA emails in print-none

- package-lock.json
- package.json
- src/views/Exercises/Show/Applications.vue
- src/views/Exercises/Show/Reports/Diversity.vue
- src/views/Exercises/Show/Reports/ReasonableAdjustments.vue
- tests/unit/views/Exercises/Applications/Application.spec.js
- tests/unit/views/Exercises/Show/Applications.spec.js
- tests/unit/views/Exercises/Show/Reports/ReasonableAdjustments.spec.js
* Contacts
* Diversity report
* Reasonable Adjustments report
> Replace CSV exports with XLSX

- src/store.js
- src/store/qualifyingTest/qualifyingTestResponses.js
- src/styles/main.scss
- src/views/Exercises/Tasks/QualifyingTests.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
- Added a TODO class to highlight WIP
- Changed the Route to the database ID
- Populated DASH with dummy HTML
> #776 QT Store creation for qualifyingTestResponses

- src/views/Exercises/Tasks/QualifyingTests.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
- Added exercise Id
- Created template for Test Responses
- Changed names of the functions in the View
> #776 QT Store and others

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Review.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
- Add another button to go back on Test Review qualifying-test/ddkfdld/review
> #799 Tidy up Qualifying Tests MVP

- src/filters.js
- src/helpers/constants.js
- src/store/qualifyingTest/qualifyingTestResponses.js
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
#762 - Show invited, started and completed test responses
- Added the STARTED and IN PROGRESS direct links from the dashboard
#813 QTs: mark and show scores
- Added the button to SCORE the responses
> #762 - Show invited, started and completed test responses

- src/components/Form/DateInput.vue
> #848 Fixed Launch dates defaulting to the day that BST becomes GMT

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
Fixed the undefined error on the export.
> #852 fix Export - undefined and no answer rows

- src/views/Exercises/Applications/Application.vue
List now includes checking for additional prefs, looping through each and displaying them formatted by type (with type in brackets next to question title) as below;
> show additional prefs on review

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
Added scores to the export file
> #832 Add scores to the export file

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Review.vue
> #894 QT: Add questions to the REVIEW page

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
> Changed button name from initialise to create

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
- Added the OFFLINE time in between
- Added information about the user being ONLINE just now
> #838 Time Logs

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
Activate button changed to say create
> Change 'activate' to 'open' 

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Review.vue
- tests/unit/helpers.js
- tests/unit/views/Tasks/QualifyingTests/QualifyingTest/Review.spec.js
Tried setting up a test suite for this view but encountered a-lot of issues removing warnings from the suite cause i couldnt satisfactorily mock the full qt object
> Remove duplicate answers response review page

- src/store/qualifyingTest/qualifyingTestResponses.js
Hey @lloback please could you sanity check this locally to ensure:
- responses are not wiped
- responses in `testQuestions` are copied across to `responses` (iff `responses` is empty)
- anything else
> #919 Move test. Check responses in testQuestions

- src/components/Micro/QuestionDuration.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
> #917 Update the status of the questions on the fly

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/dac276b7-7400-48d0-82f2-43bb45e8c390
https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/407edb03-4c2a-4c75-80ae-109e181073dd
https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/2a0a3487-ea1a-43d2-8272-148419965245
> #918 Run out of time: admin

- src/router.js
- src/store.js
- src/store/qualifyingTestReports/collection.js
- src/store/qualifyingTestReports/document.js
- src/views/Exercises/Show.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport/View.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReports.vue
Initial list and view pages for qualifying test reports
> #929 #931 List and view qualifying test reports

- src/router.js
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport/View.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport/ViewScore.vue
Also includes drilling down into each score
> #932 Download qualifying test report

- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
> #873 Stage/status selection when initialising a qualifying test

- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport/View.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Review.vue
Includes status in the QT report download
Also auto-fixed some rogue spaces
> #967 QT results - see those who did not submit

- src/views/Exercises/Applications/Application.vue
see [here](http://localhost:8080/exercises/wdpALbyICL7ZxxN5AQt8/applications/applied/application/AzQNMOymDcUs0LjM7mlB)
> add check for memberships

- package-lock.json
- src/components/Modal/views/IndependentAssessorChange.vue
- src/store/assessment.js
- src/views/Exercises/Applications/Application.vue
Change assessor
Changes the `application` and `assessor` if exists
> #985 Independent assessor change

- src/components/Candidates/EqualityAndDiversity.vue
- src/views/Exercises/Applications/Application.vue
admin changes reflecting apply 640.
> equality-diversity-changes

- src/components/ModalViews/UploadFiles.vue
- src/views/Exercises/Edit/Downloads.vue
- tests/unit/views/Exercises/Edit/Downloads.spec.js
- created the popup for uploading files
- added the possibility of adding / removing/ replacing
- commmented out the tests
- validation
> #1066 Add any numbers of documents to exercise downloads

- package-lock.json
- src/components/Notes/NotesList.vue
- src/views/Candidates/CandidatesList.vue
- src/views/Dashboard.vue
- src/views/Exercises/Show/Applications.vue
- src/views/Exercises/Show/Reports/CharacterIssues.vue
- src/views/Exercises/Show/Reports/EligibilityIssues.vue
- src/views/Exercises/Show/Reports/Handover.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport/View.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReport/ViewScore.vue
- src/views/Exercises/Show/Reports/QualifyingTestReports/QualifyingTestReports.vue
- src/views/Exercises/Stages/HandoverList.vue
- src/views/Exercises/Stages/RecommendedList.vue
- src/views/Exercises/Stages/ReviewList.vue
- src/views/Exercises/Stages/SelectedList.vue
- src/views/Exercises/Stages/ShortlistedList.vue
- src/views/Exercises/Tasks/CharacterChecks.vue
- src/views/Exercises/Tasks/IndependentAssessments.vue
- src/views/Exercises/Tasks/QualifyingTests/Cover.vue
- src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
- src/views/NotificationsList.vue
Includes latest Table component from jac-kit and enables filtering for Dashboard and Review list.
Note: remaining Filters to be added in #996
> #1001 Add filtering to table component

- package-lock.json
- package.json
- src/views/Dashboard.vue
- src/views/Sandbox.vue
Update admin to use jac-kit 0.0.25 which includes mobile-friendly tables.
Update dashboard to include column titles, which are shown in mobile view
> #995 Update jac-kit for mobile-friendly tables

- src/components/PanelPacks/PanelPacks.vue
- src/router.js
- src/store/panels.js
- src/views/Exercises/Tasks/PanelsNew.vue
List different candidates to add to sift and Selection Days
> 1131 Panel pack candidates

- src/components/ModalViews/PanelMemberChange.vue
- src/components/PanelPacks/PanelPacks.vue
- src/store/panels.js
- src/views/Exercises/Tasks/PanelsView.vue
> 1131 TODOs

- src/components/PanelPacks/PanelPacks.vue
- src/router.js
- src/store/panels.js
- src/views/Exercises/Edit/Downloads.vue
- src/views/Exercises/Show.vue
- src/views/Exercises/Tasks/PanelsNew.vue
- src/views/Exercises/Tasks/PanelsView.vue
- src/views/Exercises/Tasks/SelectionDays.vue
Hi @mbrookeswebdev and @tomlovesgithub please double check and let me know any issues
> #1171 Panel packs review

- package.json
- public/index.html
- src/App.vue
- src/router.js
Go away "Internal Service Name".
Hello "JAC Digital Platform".
😄
> #1187 Name the admin app!

- package-lock.json
- src/views/Exercises/Applications/Application.vue
- src/views/Exercises/Applications/CharacterInformationSummaryV1.vue
Fixed the issue sentry highlighted and made things look less like:
and more like:
> account for missing info in applications

- src/views/Exercises/Show/Reports/EligibilityIssues.vue
---
Describe the changes included in this pull request and highlight dependencies with other repos/tickets
✅ Developers
✅ UTG
---
> Fixed report, added export button and first name filter

- src/views/Exercises/Show/Reports/CharacterIssues.vue
---
This PR closes #1319.
Adds a button to export the character information from a firebase cloud function that gathers the data. This request depends on a pull request for the digital-platform repository - [digital-platform#545](https://github.com/jac-uk/digital-platform/pull/545) which contains the report information.
✅ Developers
✅ UTG
Click the button.
Ensure the report that should be downloaded looks as specified.
---
> add character issues export button

- src/components/ModalViews/IndependentAssessorChange.vue
- src/components/ModalViews/LeadershipJudgeDetails.vue
- src/views/Exercises/Tasks/IndependentAssessments.vue
✅ Developers
✅ UTG
Edit an independant assessor for an application, the form fields should now be validated.
---
> #465 Validate independent assessor details

- src/views/Exercises/Show/Reports/EligibilityIssues.vue
---
✅ Developers
✅ UTG
Export the Eligibility Report. The filename should no longer be called `Contacts.xlsx`
---
> eligibility issues - renamed filename

- src/components/RepeatableFields/SelectionCriterion.vue
- src/views/Exercises/Applications/Application.vue
- src/views/Exercises/Show/Eligibility.vue
- src/views/Exercises/Show/Reports/Agency.vue
- src/views/Exercises/Show/Reports/ReasonableAdjustments.vue
Swapped out the basic text input for our rich text input. 
Allowing admins to format this paragraph 
✅ Developers
✅ UTG
Update/create an exercises additional selection criteria
🟢 Low risk - This change relies upon the apply app suitably displaying the input text.
So needs to be released alongside the accompanying apply changes. 
---
> #1271 rich text input for ASC

- .github/workflows/on-pull-request.yml
- src/components/Navigation/SubNavigation.vue
- tests/unit/views/Exercises/Edit.spec.js
- tests/unit/views/Exercises/Edit/Contacts.spec.js
- tests/unit/views/Exercises/Edit/Downloads.spec.js
- tests/unit/views/Exercises/Edit/EditName.spec.js
- tests/unit/views/Exercises/Edit/Eligibility.spec.js
- tests/unit/views/Exercises/Edit/Shortlisting.spec.js
- tests/unit/views/Exercises/Edit/Timeline.spec.js
- tests/unit/views/Exercises/Edit/Vacancy.spec.js
- tests/unit/views/Exercises/New.spec.js
- tests/unit/views/Exercises/Reports.spec.js
- tests/unit/views/Exercises/Show.spec.js
- tests/unit/views/Exercises/Show/Applications.spec.js
- tests/unit/views/Exercises/Show/Contacts.spec.js
- tests/unit/views/Exercises/Show/Downloads.spec.js
- tests/unit/views/Exercises/Show/Eligibility.spec.js
- tests/unit/views/Exercises/Show/Overview.spec.js
- tests/unit/views/Exercises/Show/Reports/ReasonableAdjustments.spec.js
- tests/unit/views/Exercises/Show/Shortlisting.spec.js
- tests/unit/views/Exercises/Show/Timeline.spec.js
- tests/unit/views/Exercises/Show/Vacancy.spec.js
This PR patch fixes our tests and includes them again in the Pull Request workflow (they were turned off as part of #1362).
Our tests need a decent amount of attention outside the scope of this epic.
✅ Developers
Check out this branch and run `npm run tests`. There should be no failing tests
---
PREVIEW:OFF
> #1341 Staged applications

- src/views/Exercise/Details/Timeline/Edit.vue
> Testing fix for timeline

- src/store/auth.js
Added an approved statistitian email, removed product owner email.
✅  BA
The statistitian should be able to create an account and log in to the platform.
---
> #1482 Added the approved email, removed a no-longer-in-use email

- src/views/Exercise/Stages/ReviewList.vue
I placed data into correct columns on Stages->Review page.
✅ Developers
Check Stages->Review page and confirm that data displayed in Issues and Status table columns is correct.
---
> #1484 Placed data into correct columns

- src/helpers/authUsers.js
- src/store/auth.js
> Allow deeson account access

- src/views/Exercise/Applications/Application.vue
This ticket addresses a bug which is preventing applications from showing.
Bug introduced in #1314 
---
> fix task details show

- package-lock.json
- package.json
- src/firebase.js
- src/router.js
- src/views/Exercise/Reports.vue
- src/views/Exercise/Reports/Custom.vue
A new way to inspect data within the dashboard and generate / save your own reports.
✅ Developers
✅ UTG
Go to an Exercise
Click the reports tab
Click the Custom report link on the left nav
Functionality:
1. Select a column from the dropdown to show the values in a table
2. Add multiple columns, delete them by clicking and re-order by dragging.
3. Change the report type to count to view aggregated results
4. On the count report, click one of the values to add a 'where clause' which limits the results
5. Save a report by clicking Save Report at the top right of the page, give it a name. Then switch to a different exercise and try to load the report.
---
> #1078 - Create custom report

- .github/workflows/manual-deploy.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- src/firebase.js
- src/helpers/authUsers.js
- src/store/auth.js
Removes changes introduced to assist pen testers
✅ Developers
---
> Remove pen test temporary changes

- package-lock.json
- package.json
- src/App.vue
- src/helpers/exerciseHelper.js
- src/store/auth.js
- src/store/exercise/document.js
- src/store/stage/handover.js
- src/store/stage/recommended.js
- src/store/stage/review.js
- src/store/stage/selected.js
- src/store/stage/shortlisted.js
- src/views/Exercise.vue
- src/views/Exercise/Applications.vue
- src/views/Exercise/Applications/List.vue
- src/views/Exercise/Details/Overview.vue
- src/views/Exercise/Reports/CharacterIssues.vue
- src/views/Exercise/Stages.vue
- src/views/Exercise/Stages/HandoverList.vue
- src/views/Exercise/Stages/RecommendedList.vue
- src/views/Exercise/Stages/ReviewList.vue
- src/views/Exercise/Stages/SelectedList.vue
- src/views/Exercise/Stages/ShortlistedList.vue
- src/views/Exercise/Tasks.vue
- src/views/Exercise/Tasks/IndependentAssessments.vue
- src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/View.vue
- src/views/Exercises.vue
Updates Admin interface to use the latest numeric counters for applications and the stages they are in.
✅ Developers
The counters effected by this change are:
- The number of **Draft**, **Applied** and **Withdrawn** applications
- The number of applications in the **Review**, **Shortlisted**, **Selected**, **Recommended** and **Handover** stages
The counters appear in the following places:
- Exercise Overview. **Draft** and **Applied**
- Applications. Side menu shows **Draft**, **Applied** and **Withdrawn**
- Stages. Side menu shows **Review**, **Shortlisted**, **Selected**, **Recommended** and **Handover**
- Stages. Review. Heading shows **Review**
- Stages. Shortlisted. Heading shows **Shortlisted**
- Stages. Selected. Heading shows **Selected**
- Stages. Recommended. …
> #1474 Exercise dashboard and counts

- package-lock.json
- package.json
- src/views/Exercise/Tasks/PanelsView.vue
All tables now compatible with new logic.
`params.orderBy` now optional.
paging logic can work without being passed orderBy 
✅ Developers
✅ UTG
Check table views such as panel view and character issues report pages work.
---
> Tables. Enable optional sorting

- src/store.js
This is related to improvements to JAC Kit Table component [Ticket TBC]
Here we are changing the way vuexfire loads data. 
The table contents are no longer emptied when changes happen, for example the Page next/previous buttons are pressed. 
The result is that the table has smoother transitions.
✅ Developers
Try paging, sorting, searching and filtering a table in Admin on both the preview URL and the existing develop URL.
Observe that on the preview URL there is much less jumpy, flickery shenanigans going on 😄 
**Before**
https://user-images.githubusercontent.com/8524401/153852260-4bf4c1e8-f402-470d-8d5e-929dfda4315f.mov
**After**
https://user-images.githubusercontent.com/8524401/153852484-05172dac-19f3-4cd0-bbf9-dbdac1638fc7.mov
🟠 Medium risk - this is just a one line …
> Table improvements

- src/views/Exercise/Reports/CharacterIssues.vue
---
Add the character search feature:
* case-insensitive query
* fuzzy query
Note: the search keywords will be based on the field `computed.search` of collection `candidates`. 
✅ Developers
✅ UTG
1. Go to an exercise
2. Go to `Reports` and click `Character Issues`
3. Type candidate name in search box
Sample test link: https://jac-admin-develop--pr1600-feature-1599-charact-m9ytouyf.web.app/exercise/ws8DOmg9UkBA2KrHnWdl/reports/character-issues
Demo:
---
> #1599 Character Search

- src/views/Exercise/Reports/EligibilityIssues.vue
---
Improve the eligibility search feature:
* It is case sensitive, it shouldn't be
* The search only works when you type the first few letters in, it should bring back results for any letters typed
* When you clear the search it should return all results back
Note: the search keywords will be based on the field `computed.search` of collection `candidates`. 
✅ Developers
✅ UTG
1. Go to an exercise
2. Go to `Reports` and click `Eligibility Issues`
3. Type candidate name in search box
Sample test link: https://jac-admin-develop--pr1598-feature-1597-eligibi-jvvew6wl.web.app/exercise/ws8DOmg9UkBA2KrHnWdl/reports/eligibility-issues
Demo:
---
_can be OFF, …
> #1597 Eligibility Search

- src/views/Exercise/Details/Eligibility/Edit.vue
---
There has been a policy change regarding the standard mandatory retirement age. 
Our system included a default of 70, which has now been changed to reflect the policy. 
✅ Developers
✅ UTG
Observe "retirement age" under eligibility.
Options should be 
- 75 years
- Other
---
> Manditory retirement age update

- src/views/Exercise/Reports/EligibilityIssues.vue
---
Eligibility Issues - A new Export to Google Docs button.
Note: this issue is relative to [#1620 - eligibility issue google doc report](https://github.com/jac-uk/digital-platform/pull/727) on digital-platform
✅ Developers
✅ UTG
Preview URL: https://jac-admin-develop--pr1626-feature-1625-eligibi-kae8dryz.web.app
- View an exercise with eligibility issues
- Click the `Generate Report` button to generate report on google doc
- A document should be downloaded, containing an export of the eligibility issues
Example layout:
[Selection and Character Committee Eligibility and ASC paper.docx](https://github.com/jac-uk/admin/files/8796901/Selection.and.Character.Committee.Eligibility.and.ASC.paper.docx)
Demo: …
> #1625 - eligibility issues google doc report

- src/router.js
- src/views/Candidates/CandidatesList.vue
- src/views/Candidates/TargetedOutreachReport.vue
This is the frontend part of the function to generate the Targeted Outreach Report.
✅ Developers
✅ UTG
https://jac-admin-develop--1667-outreach-u31g3a2h.web.app/
Go to the Candidate's page by clicking on the link at the top of the page (next to Sign out)
Click on the new button "Targeted Outreach Report"
Clear function - to start again
Download Report - to download a CSV file
Video with a demo:
https://drive.google.com/file/d/1onKF_l-n3a2icJwl6TBtwfKlHazdAk1j/view?usp=sharing
> 1667 Targeted Outreach Report - admin

- src/assets/expand.svg
- src/filters.js
- src/helpers/constants.js
- src/views/Exercise/Reports/CharacterIssues.vue
On Character Issues page show all character issues from other exercises.
https://docs.google.com/document/d/1KumfgugHW0PQWasyjjs1X07Eh4uMbyPXqHeo_gLu3gk/edit
✅ Developers
✅ UTG
1. Go to character issues report of an exercise
2. Check character issues from other exercises
Demo:
https://user-images.githubusercontent.com/79906532/180025742-77a2abcd-43f7-4810-a823-1d57a2d82766.mov
---
> #1677 Character Report Part 2 - Show all character issues from other exercises

- package-lock.json
- package.json
- src/components/PanelPacks/PanelPacks.vue
- src/store/stage/selected.js
Updated search function implemented in panel packs views. 
This allows search to function correctly and allows the candidates to be searched by ref, name, email etc.
(also includes updated JAC-kit which fixes candidate view application tab stuck on loading)
✅ Developers
✅ UTG
- [[JAC00288]](https://jac-admin-develop--pr1722-panel-pack-search-eagzqg5o.web.app/exercise/mzdAdY3zBAAQkbHGOJgg/tasks/selection#candidates)
- Find application with selection days/ sift
- Search by partial match and any other relevant info that you would expect to yield search results.  
---
> Panel pack search function.

- src/helpers/constants.js
Fix the error when building the project.
Note: this problem is caused by the [#1690 Update independent assessments UI](https://github.com/jac-uk/admin/pull/1696).
✅ Developers
Run the command `npm run develop:serve` to check if the project serves successfully.
---
> Bugfix: #1690 conflict merge error

- src/router.js
- src/views/Exercise/Reports/QualifyingTestReports/Create.vue
- src/views/Exercise/Reports/QualifyingTestReports/QualifyingTestReport/Edit.vue
- src/views/Exercise/Reports/QualifyingTestReports/QualifyingTestReport/View.vue
QT report fixes from @tomlovesgithub 
See original pull request https://github.com/jac-uk/admin/pull/1726 for details, how to test etc.
This PR merges the fix into our hotfix 0.92.1 branch which is based off of the current live 0.92.0 tag.
The hotfix branch will then be deployed to live
✅ Developers
---
> Hotfix 0.92.1: QT Report fixes

- src/views/Exercise/Reports/Agency.vue
Add the following HMRC template to the agency report.
[HMRC Request Form Template.xlsx](https://github.com/jac-uk/admin/files/9964279/HMRC.Request.Form.Template.xlsx)
✅ Developers
✅ UTG
1. Go to Agency report and export HMRC report.
2. Check the excel file if the columns are exported properly.
Demo:
https://user-images.githubusercontent.com/79906532/200653735-490f1d02-c200-4e9b-b1cd-7e5db285deb0.mov
---
> #1782 Agency Checks - HMRC Template

- src/helpers/exerciseHelper.js
Add "Relevant qualifications" and "Judicial experience" to non legal exercises. So when character checks are sent out, the following checks can be included in the form sent to candidates:
- SRA
- BSB
- JCIO
✅ Developers
✅ UTG
1. [admin] Create a non legal exercise.
2. [apply] Apply this vacancy on apply site.
3. [admin] Send the character check to the candidate.
4. [apply] Submit the character check.
5. [admin] Generate agency report and check if `SRA`, `BSB`, and `JCIO` are captured.
---
> #1760 Agency Checks - Non Legal Exercises

- src/store/stage/review.js
closes #1820 
✅ Developers
🟢 No risk - this is a bg fix
---
> add check for shortlisting methods

- src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
Closes #1829 
✅ Developers
---
> #1829 Bugfix: TypeError: Cannot convert undefined or null to object 

- src/views/Exercise/Applications/AgencyReport.vue
Closes #1814 
✅ Developers
---
> #1814 Bugfix: handle application missing personal details

- src/store/clipboard.js
Closes #1819 
✅ Developers
---
PREVIEW:OFF
> #1819 Bugfix: check document has focus before accessing clipboard

- package-lock.json
- package.json
- src/store/applications.js
- src/views/Exercise/Applications/List.vue
Add the uppercase letter pagination to the application list.
Note: this PR is related to [jac-kit: Table letter pagination #87](https://github.com/jac-uk/jac-kit/pull/87) and [digital-platform: Application letter pagination indexes #822](https://github.com/jac-uk/digital-platform/pull/822)
✅ Developers
✅ UTG
1. Go to the applications of an exercise.
2. Switch pages and check if the pagination works properly.
3. Check the search functionality.
Demo:
https://user-images.githubusercontent.com/79906532/210990631-03a315b7-99f3-4a01-be33-d14f6a2dc340.mov
---
> #1773 Pagination on Applications Tab

- src/store/clipboard.js
- src/views/NotificationsList.vue
Handles user not allowing access to clipboard
Closes #1815
✅ Developers
---
> #1815 Bugfix: handle not having access to clipboard

- src/views/Exercise/Applications/Application.vue
Indicate if the application is submitted in Welsh.
✅ Developers
✅ UTG
Go to an application submitted in Welsh and check if the information of the welsh application displays.
Screenshot:
---
> #1813 Indicate if application is submitted in welsh

- src/filters.js
- src/reports.js
- src/router.js
- src/views/Exercise/Dashboard/Dashboard.vue
Change BAME to Ethnic Minorities.
Order fields in table.
Fixed missing slash in router path.
✅ Developers
On the Dashboard page ensure the order of the fields in the tabbed table (for gender) are:
Male
Female
Gender neutral
Prefer not to say
Other
No answer
Also ensure any reference to BAME or Black, Asian and minority ethnic are changed to Ethnic minorities. This can be tested by changing the dropdown in the Dashboard page to Ethnicity.
It can also be checked on the Diversity page's tabbed table.
---
> #1786 Dashboard Feedback

- src/filters.js
- src/views/Exercise/Reports/ReasonableAdjustments.vue
The following will be implemented: 
✅ Developers
✅ UTG
Go to Reasonable Adjustments Report and check if the above items work.
https://user-images.githubusercontent.com/79906532/218090998-7c2196be-e0c0-4b57-b150-2c4023ae9ff3.mov
---
> #1842 Refresh of reasonable adjustments

- .github/workflows/on-release.yml
Updates our workflow for Releases to include @tomlovesgithub's dependency check
> Workflow: On Release. Include dependency check

- src/views/Exercise/Tasks/IndependentAssessments.vue
The search functionality under IAs was broken. This should fix it
✅ Developers
✅ UTG
Search for a candidate name under Exercise > tasks > IA > (*any stage of IA*)
(**note** dummy candidates will not show)
---
> Fix IA search

- src/helpersTMP/Timeline/exerciseTimeline.js
- src/views/Exercise/Details/Timeline/Edit.vue
Closes #1903 
✅ Developers
✅ UTG
Go to the timeline of an exercise:
1. Check if the wording of Character Checks is renamed.
2. Check if `Character Checks - Professional Checks sent date` and `Character Checks - Professional Checks return date` are editable.
---
> #1903 Timeline Update - Character Checks - Additions

- package-lock.json
- package.json
- src/views/Exercise/Applications/List.vue
- src/views/Exercise/Reports/ReasonableAdjustments.vue
- src/views/Exercise/Reports/StatutoryConsultation.vue
Closes #1836 
The following will be implemented:
✅ Developers
✅ UTG
Go to Statutory Consultation Report and check if the above items work.
Screenshot:
---
> #1836 Stat Con - Enhancements

- package-lock.json
- package.json
Closes #1929 
✅ Developers
✅ UTG
Go to the timeline of an exercise and check if QT dates are mandatory.
- Critical analysis qualifying test (QT)
- Scenario test qualifying test (QT)
- Situational judgement qualifying test (QT)
Demo:
https://user-images.githubusercontent.com/79906532/231148557-5472bb0a-3635-401c-929d-5fd48048b092.mov
---
> #1929 Timeline - QT Dates

- src/views/Exercise.vue
Closes #1965 
✅ Developers
✅ UTG
Go to an exercise and check if `Copy to clipboard` is working.
Demo:
https://user-images.githubusercontent.com/79906532/232727022-f82f4d41-7af3-4784-8e70-832adfb78893.mov
---
> #1965 Bugfix: copy exercise to clipboard

- src/views/InformationReview/ExperienceSummary.vue
In this previous PR [(Medical Members questions for 00164)](https://github.com/jac-uk/admin/pull/1988) the changes are not working. In this PR it will fix the error showing in the browser console.
✅ Developers
Apply for one of the following vacancies and see that the application review includes the changes in [jac-uk/admin#1974](https://github.com/jac-uk/admin/issues/1974):
Develop: JAC00507
Staging: JAC00660
Production: JAC00164
---
> Bugfix: #1974 Medical Members questions for 00164

- src/App.vue
- src/views/Exercise.vue
Closes #1963 
✅ Developers
✅ UTG
1. Go to an application page.
2. Download the application and check if the information displays correctly.
---
> Bugfix: #1963 Contents Of Download Link On Application Page Is Incorrect

- src/views/Exercise.vue
- src/views/Exercises.vue
> Fix exercise list

- src/views/Exercise/Applications/List.vue
- src/views/InformationReview/EqualityAndDiversityInformationSummary.vue
Along with digi-plat ticket fixes the contacts export and ensures the columns are aligned with their answers.
✅ Developers
✅ UTG
- Visit an exercise with applications
- Navigate to Applications > Applied 
- click 'export contacts'
- ensure columns on downloads are correct with results.
---
> fix report download

- src/store/candidateApplications.js
Fix the bug that can not set panel.
✅ Developers
✅ UTG
Go to Sift, Selection under Reports and check if you can set panel.
---
> Hotfix: can not set panel

- src/store/exercise/document.js
- src/views/Exercise/Details/ApplicationContent/Edit.vue
- src/views/InformationReview/EqualityAndDiversityInformationSummary.vue
- vue.config.js
When on the Application Process page the user's changes are auto-saved.
We now have them saved only when the 'Continue' button is pressed.
Also the 'Continue' button is disabled if there are no changes.
closes #2026
✅ Developers
✅ UTG
See video attached:
https://github.com/jac-uk/admin/assets/115651787/96219f8c-3777-4a3f-9242-68ddedf04d46
---
> #2026 Exercise Application Process - Auto Save

- package-lock.json
- package.json
Display the types of files that can be uploaded next to the file input
Closes #2043 
✅ Developers
✅ UTG
See video:
https://github.com/jac-uk/admin/assets/115651787/e15839fd-ff85-44d3-b9fa-c1463180ad3f
---
> #2046 Displaying file upload types

- src/helpers/exerciseHelper.js
- src/store/exercise/document.js
- src/views/Exercise/Details/ApplicationContent/Edit.vue
Closes #2060 
✅ Developers
Create a new exercise and check that Application Process appears as a link in the side navigation:
@drieJAC please check that this fixes the issue we spotted
@tomlovesgithub @HalcyonJAC please check you are happy with the code changes
---
> #2060 Bugfix: Application Process missing from exercise side nav

- src/views/InformationReview/AssessmentsSummary.vue
- src/views/InformationReview/QualificationsAndMembershipsSummary.vue
Replace @input with @update:model-value for vue3.
Closes #2077 
✅ Developers
✅ UTG
- find an exercise with applications
- select the applications tab
- choose an application
- click the edit button to edit it
- scroll down and ensure you can upload a self assessment or cv (if the file upload is available for the application)
- once uploaded ensure it displays the file name and that you can click on the file name to download the file
- try pressing the 'replace' button and uploading a different file
- once uploaded ensure you can click the filename link to download it again
---
> #2077 File upload not displaying newly uploaded file

- README.md
Quick change to test that our merge and release workflows are working as expected.
We have now moved from version 0.x.x. to version 1.x.x.
We should expect the next release version to be 1.1.0
✅ Developers
No need for specific testing. 
Once this PR is merged we should see the version change from 1.0.0 to 1.1.0 on `develop` and `staging` and we should see a draft release created for 1.1.0
Once the 1.1.0 draft release is published `production` should move to 1.1.0
> Latest Vue 3 upgrade and fixes

- src/views/Exercise/Details.vue
- src/views/Exercise/Details/ApplicationContent/Edit.vue
- src/views/Exercise/Details/Overview.vue
- Ensure Application Process always appears in Sidebar List.
- Ensure Submit For Approval button is always displayed.
- Ensure Application Process appears in task list.
Closes #2034
✅ Developers
✅ UTG
See screenshots:
---
> #2045 Application Process

- src/views/Exercise/Details/Contacts/Edit.vue
Changed Lord Chief Justice to Lady Chief Justice on Admin/Apply/DP
> Change lord to lady (chief justice)

- src/components/Page/InformationReviewSectionRenderer.vue
- src/filters.js
- src/helpers/exerciseHelper.js
- src/views/InformationReview/CharacterSummary.vue
- src/views/InformationReview/ExperienceSummary.vue
Closes #2167 
✅ Developers
✅ UTG
Example exercise:
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft
Example application:
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/GYLBhVPwiNflRTpAGfrM
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/NOmunes43iHwX7AdxAZN
- https://jac-admin-develop--pr2213-feature-2167-update-tib0sk43.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/LinokWzjBmo6uNykztEa
Steps:
1. Go to an application.
2. Check if you can amend the "Post-qualification experience".
When "The carrying-out of …
> #2167 Update Application view

- src/main.js
- src/router.js
Closes #2265 
✅ Developers
✅ UTG
1. Go to the preview link: https://jac-admin-develop--pr2268-feature-2265-redirec-mhcl8lch.web.app/exercise/WfzevDfSdwq3NwWBqJFn/details/downloads
2. It should redirect to sign-in page, then enter the credentials to sign-in
3. If sign in successfully, it should redirect to the original page (the same as the preview link: https://jac-admin-develop--pr2268-feature-2265-redirec-mhcl8lch.web.app/exercise/WfzevDfSdwq3NwWBqJFn/details/downloads)
---
_can be OFF, DEVELOP or …
> #2265 Redirect to next page on sign in

- src/components/PanelPacks/PanelPacks.vue
> remove breaking check for panel pack displays

- src/views/Exercise/Reports/CharacterIssues.vue
Closes #2230 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2278-feature-2230-charact-dzyc1799.web.app/exercise/aDxEqK36807d0Nhpugo3/reports/character-issues
- Click `Refresh` to generate latest report
- `Recommended SCC Approach Field`
- Locate the "Recommended SCC Approach" field (refer to place 1 in the image).
- Confirm that this field is visible for each candidate.
- Selected Option in `Recommended SCC Approach Field`
- Check the "Recommended SCC Approach" field for each candidate.
Verify that the selected option is displayed in this field (refer to place 2 in the image).
- `View All Character Issues` Link
- Look for the "View all character issues from previous applications" link (refer to place 3 in the image).
- Ensure that this link is …
> Feature/2230 Character declaration updates

- src/store/auth.js
- src/store/users.js
Fix the bug when a new user signs in with Microsoft email address.
✅ Developers
---
> Bugfix/User role with Microsoft email address

- src/helpers/exerciseHelper.js
- src/reports.js
- src/store/characterChecks/characterChecks.js
- src/views/Exercise/Dashboard/Dashboard.vue
- src/views/Exercise/Reports/CharacterIssues.vue
- src/views/Exercise/Reports/Diversity.vue
- src/views/Exercise/Reports/Outreach.vue
- src/views/Exercise/Reports/StatutoryConsultation.vue
- src/views/Exercise/Stages/List.vue
Closes #2275 
- Update the diversity report to align with the stage changes (from `Selected` to `Selectable`).
- Update the outreach report to align with the stage changes (from `Selected` to `Selectable`).
- Places that use hard-coded stages:
- "Candidate Breakdown at Each Stage" on the exercise dashboard.
- "Diversity" report
- "Outreach" report
- Places that use hard-coded statuses: **(need to check the final version of statuses)**
- "Character" Issues report
- "Statutory" Consultation report
- "applicationCurrentStep" in `src/helpers/exerciseHelper.js`
Note: This PR needs changes on digital-platform: [Feature/admin#2275 Update reports which include stage & status](https://github.com/jac-uk/digital-platform/pull/1008).
✅ Developers
✅ UTG
Example exercise: …
> Feature/2275 Update reports which include stage status

- package-lock.json
- package.json
- src/views/Exercises.vue
Closes #2281 
✅ Developers
✅ UTG
Preview URL: https://jac-admin-develop--pr2330-feature-2281-update-761kgtue.web.app/
1. Go to the Exercise list.
2. Check if the tickbox `Exclude Exercises in Draft status` works correctly.
3. Check if the Approval section has been removed from the filters.
Demo:
https://github.com/jac-uk/admin/assets/79906532/21d96cd7-b9ea-4175-ad4f-45af1d5e1faa
---
> Feature/2281 Update Filters on Live Exercises index page

- package-lock.json
- src/views/Exercise/Details/Preferences/LocationPreferences.vue
- src/views/Exercise/Details/Preferences/View.vue
> Fix location preferences, the rest to do

- src/helpers/file.js
- src/views/Exercise/Reports/CharacterIssues.vue
Closes #2293.
Note: This PR requires the changes in [digital-platform: Feature/admin 2293 Character Annex Report](https://github.com/jac-uk/digital-platform/pull/1026).
✅ Developers
✅ UTG
Example exercise: https://jac-admin-develop--pr2339-feature-2293-charact-1mneeeti.web.app/exercise/aDxEqK36807d0Nhpugo3/reports/character-issues
1. Go to the Character Issues report and click "SCC Annex" to download the report.
2. Open the report and check if the content is populated correctly.
Demo:
https://github.com/jac-uk/admin/assets/79906532/bb4c9110-f547-4868-9aae-7d12274cb683
--- …
> Feature/2293 Character Annex Report

- package-lock.json
- package.json
- src/views/Exercise/Applications/List.vue
- Increase the page size when using the letter pagination on the application list.
Related PR: [Bugfix/Remove initial page size when using letter pagination #181](https://github.com/jac-uk/jac-kit/pull/181)
✅ Developers
Live exercise: https://jac-apply-admin-production--pr2360-bugfix-ts-265-appli-97nhxr90.web.app/exercise/phf3iabh5KDhRiw4f4xm/applications/applied
1. Go to the application list of an exercise.
2. Check if you can see all records when using the letter pagination.
---
> Bugfix/TS 265 Application List Page Size

- src/views/Exercise/Reports/CharacterIssues.vue
Closes #2345 
- Fix Firebase modular syntax.
✅ Developers
Example exercise: https://jac-admin-develop--pr2358-bugfix-2345-characte-6zg4bd2g.web.app/exercise/FpV4enhw0yWFb9htWO7y/reports/character-issues
1. Go to "Character Issues" report page of an exercise.
2. Click "View all character issues from previous applications" and check if the historic character issues display correctly.
Demo:
https://github.com/jac-uk/admin/assets/79906532/26763ceb-47e1-44c3-a99c-7cac2f116137
---
> Bugfix/2345 Character issues from previous applications are not appearing

- src/views/Exercise/Reports/ReasonableAdjustments.vue
closes #2373 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2374-bugfix-admin-2373-re-4uuexxxo.web.app/exercise/X2tDg5AKt18xvzBRJFYW/reports/reasonable-adjustments
- Click `View all reasonable adjustments`, it should work.
---
> Bugfix/2373 Reasonable Adjustments Report Other applications not shown

- src/components/Page/EditableField.vue
Fix https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/ticketing-system/346
✅ Developers
[Example application](https://jac-admin-develop--pr2478-fix-ts-346-applicati-8u43dk89.web.app/exercise/HhtVCKZhTRSXj5wMNXCY/applications/applied/application/qdKh0KC7i2hIdNKqKnr5)
Steps:
1. Go to an application and try to amend the information on Qualifications.
2. Check if the data is saved correctly.
Demo:
https://github.com/jac-uk/admin/assets/79906532/f88ccfe1-b699-4e11-ade0-8ed8e4a74e98
---
> Bugfix/TS 346 Application qualification not save correctly

- package-lock.json
- package.json
[Identify And Fix NPM Vulnerabilities In All Repositories #2513](https://github.com/jac-uk/admin/issues/2513)
✅ Developers
Run `npm audit` in the terminal and check if there are no high vulnerabilities.
---
> Bugfix/2513 Fix NPM Vulnerabilities

- src/views/ExercisesProgrammeView.vue
Closes #2518 
✅ Developers
✅ UTG
Preview URL:
- [Dev](https://jac-admin-develop--pr2527-feature-2518-add-add-06a0opu6.web.app/exercises/programme-view)
- [Production](https://jac-apply-admin-production--pr2527-feature-2518-add-ad-jqiiz8cv.web.app/exercises/programme-view)
Steps:
1. Go to the Programme view of an exercise.
2. Check if the activity filter works correctly.
Demo:
[video-30145429-60645221a89feaa0ddd1681dd7928732.webm](https://github.com/user-attachments/assets/9c6fec83-f219-40dc-bd83-012e10431237)
---
> Feature/2518 Add additional Gantt chart filter

- src/App.vue
- src/helpers/exerciseHelper.js
When viewing the exercises page there is no exercise selected so the isPublished computed property errors. Added a helper and check to ensure it returns false if there's no exercise.
---
> Fix Error On Live Exercises Page For isPublished Computed Property

- src/views/CreateExercise.vue
- src/views/Exercise.vue
- src/views/Exercise/Details/ApplicationContent/Edit.vue
- src/views/Exercise/Details/Assessments/Edit.vue
- src/views/Exercise/Details/Contacts/Edit.vue
- src/views/Exercise/Details/Downloads/Edit.vue
- src/views/Exercise/Details/EditName.vue
- src/views/Exercise/Details/Eligibility/Edit.vue
- src/views/Exercise/Details/Invitations/Edit.vue
- src/views/Exercise/Details/Preferences/Edit.v1.vue
- src/views/Exercise/Details/Preferences/Edit.vue
- src/views/Exercise/Details/SelectionSetup/Edit.vue
- src/views/Exercise/Details/Shortlisting/Edit.vue
- src/views/Exercise/Details/Summary/Edit.vue
- src/views/Exercise/Details/Timeline/Edit.vue
- src/views/Exercise/Details/Vacancy/Edit.vue
- src/views/Exercise/Externals/Edit.vue
- src/views/Exercise/Reports/PanelsView.vue
- src/views/Exercise/Stages/Back.vue
- src/views/Exercise/Stages/Edit.vue
- src/views/Exercise/Tasks/Task/Panel/View.vue
- src/views/ExercisesExport.vue
- src/views/Panellists/Panellist.vue
closes #2549 
✅ Developers
✅ UTG
- Go to link: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/umjxBon2GRlc6rshqEfG/details/overview
- Check all edit page of each section on the exercise set-up menu, the back button should be removed.
- Go to link: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/umjxBon2GRlc6rshqEfG/stages/scc
- Check all set status and set back pages of each stage on stages menu, the back button should be removed.
- Go to: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/umjxBon2GRlc6rshqEfG/reports/sift
- Check panels of sift and selection day on report menu, the back button should be removed.
- Go to: …
> Remove Back button

- src/views/Exercise/Applications/List.vue
Closes #2575 
✅ Developers
✅ UTG
[Example exercise](https://jac-admin-develop--pr2581-feature-2575-amend-m-4p1mdakn.web.app/exercise/y27ibpzogMIDluD5Wwc2/applications/draft)
1. Go to the draft applications of an exercise and hit the "Send reminders" button.
2. Check if the message is updated.
Screenshot:
---
> Feature/2575 Amend messaging on Send reminders modal

- src/components/Feedback/FeedbackForm.vue
Add slack message sending timestamp and retries to bugReport record
✅ Developers
✅ UTG
Create an issue and check that the bugReport has the following data in it:
slackMessages = {
onCreate: {
retries: 0,
sentAt: null,
},
};
> DP #1261 Raise An Issue Not Always Sending Slack Alerts

- src/views/Exercise/Reports/Diversity.vue
Issue: [User Raised Issue BR_ADMIN_PR_000264 #485](https://github.com/jac-uk/ticketing-system/issues/485)
- Fix the alignment of the applications column.
✅ Developers
[Example exercise](https://jac-admin-develop--pr2630-bugfix-ts-485-divers-z8g7oxo2.web.app/exercise/0ySRDHmWM8ARVxSCw7zv/reports/diversity)
Steps:
1. Go to the Diversity Report of an exercise.
2. Check if the applications column alignment is not awry.
Demo:
https://github.com/user-attachments/assets/e1e7396e-104b-4c94-9fa4-876f8c516251
---
> Bugfix/TS 485 Diversity Checkpoints Report

- src/router.js
- src/services/permissionService.js
Prevent users from accessing the users page who dont have the correct permission
Closes #2597 
✅ Developers
✅ UTG
Test 1
- Login as an Operations Team Member
- Manually change the url to: https://jac-admin-develop--pr2634-bugfix-2597-rbac-rev-wtxqnlto.web.app/users
- You should see a page telling you the page can't be found
Test 1
- Login as a Digital Super User
- Manually change the url to: https://jac-admin-develop--pr2634-bugfix-2597-rbac-rev-wtxqnlto.web.app/users
- You should see the users page
---
> 2597 4.1 RBAC Review

- src/views/Exercise/Tasks/Task/Data/Activated.vue
Enables pasting data from PC
TBC
---
> Bugfix: Scenario Test. Paste from PC

- src/permissions.js
Added task permissions and missing permission for creating test applications
✅ Developers
✅ UTG
- Permissions have been added / updated
---
> Added Permissions For Create/Update Tasks And For Creating Test Applications

- src/views/Exercise.vue
- src/views/NotificationsList.vue
https://github.com/jac-uk/digital-platform/pull/1289
Added/removed permissions to align with digital platform.
> DP 1277 Review tests for permissions on callable functions + firestore rules

- src/router.js
closes #2648 
✅ Developers
✅ UTG
- Go to`/notifications`, it should show notification list.
---
> fix notification permission

- src/store/exercise/document.js
- src/views/Exercise/Configuration/ProcessingVersion.vue
closes #2655 
✅ Developers
- Create an exercise, the processing version should be v3 as default.
---
> Upgrade to processing version 3

- src/store/characterChecks/characterChecks.js
Closes #2685 
Related PR: [digital-platform: Feature/Admin 2685 Exclude withdrawn candidates from character checks task #1317](https://github.com/jac-uk/digital-platform/pull/1317)
✅ Developers
✅ UTG
[Example exercise](https://jac-admin-develop--pr2687-feature-2685-withdra-w69rwh7x.web.app/exercise/Biyjd07Xz2usL9yXjtjV/tasks/all/character-checks)
1. Go to the Character Checks Consent task of an exercise.
2. Check if withdrawn candidates are excluded from the list.
---
> Feature/2685 Withdrawn candidates are included in Character checks consent task

- src/views/Exercise/Details/Contacts/Edit.vue
- src/views/Exercise/Details/Overview.vue
- src/views/Exercise/Reports/Custom.vue
- src/views/Exercise/Reports/MultipleExerciseCustomReport.vue
The first round of improvements for the Multiple Exercise Custom Report (MECR)
- Include withdrawn applicants
- Exclude draft applicants
- Including working preferences
✅ Developers
✅ UTG
Experiment with the MECR.
- Ensure all withdrawn applications are included.
- Ensure no draft applications are included.
- Experiment with creating and downloading Working Preference answers
Where possible, attempt to generate reports with old style pref questions, new style pref questions, multiples, and combinations of each.
---
> Mecr feedback

- src/views/Exercise/Reports/Custom.vue
Commented out code relating to saving and loading reports and removed… the call to getReports in the created hook. I only commented it in case we want it back soon.
**This is associated with digital platform PR: https://github.com/jac-uk/digital-platform/pull/1360**
✅ Developers
✅ UTG
> DP #1355 Custom Report Range Error Maximum call stack size exceeded
