src/components/Form/TextField.vue, src/components/NewExercise/InformationAboutRole.vue, src/router.js, tests/unit/components/Form/TextField.spec.js, tests/unit/components/NewExercise/InformationAboutRole.spec.js, tests/unit/journeys/page-titles.spec.js
1) Add component TextField
2) Create a new view for an "About the role" form
3) Use new TextField component to display Immediate start and Future start fields.
! to get to this component, go to http://localhost:8080/exercise/new/information-about-role.
As this journey should start on a View Vanancy page and View Vanancy page doesn't exist yet, we display form in a separate view which will be connected to View Vanancy page in the future.
=> Add text field component for num of vacancies

src/components/Form/DateInput.vue, tests/unit/components/Form/DateInput.spec.js
As in some cases we want to display only month and a year inputs, we've added type "month" which will hide a day input field and will return a date object with the default value 1 for a day.
**Change log**
1) Add new optional prop "type" to DateInput, which will accept "month" if we only want to see the month and a year
2) Update DateConstructor property which in case if the type is "month" uses default value 1 for a day.
3) Update tests
=> Add type option to DateInput

src/components/Form/TextField.vue, tests/unit/components/Form/TextField.spec.js
- We have changed the type of the text field component to take a default 
type of 'text', however it can receive a new one from the parent.
- We have also added tests to account for this new change.
=> Refactored TextField component `type` prop

src/router.js, src/views/AddExerciseContacts.vue, tests/unit/journeys/page-titles.spec.js, tests/unit/journeys/signin.spec.js, tests/unit/views/AddExerciseContacts.spec.js
- Created a scaffold page using our new components, and the new prototype as a guideline. 
- Added a path to our router for this page. 
- Created tests in the View, and Journey folders. 
- Need to link up the 'Save and continue' button on the CreateAnExercise page to point to the AddExerciseContacts page. 
- Need to link up the 'Save and continue' button on the AddExerciseContacts page to point to the next page. 
- Need to make the 'add another' links operational (they currently do nothing).
=> Scaffold Add Exercise Contacts

src/components/RepeatableFields.vue, src/components/RepeatableFields/DraftingJudge.vue, src/components/RepeatableFields/StatutoryConsultee.vue, src/views/Exercises/Edit/Contacts.vue, tests/unit/components/RepeatableFields/RepeatableTextFields.spec.js
This PR adds two repeatable text fields that can be used as an example for all future repeatable text fields.
**Change log**
1) Update style of the repeatable component so only the first label in repeatableContainer is visible
2) Create two repeatable text fields components for a contact page and integrate them into a page
3) Add a test that can be reused for all future repeatable text fields
=> Add repeatableTextFields

src/firebase.js, src/helpers/convertFirestoreTimestampsToDates.js, src/helpers/vuexfireSerialize.js, src/store/exercise/collection.js, src/store/exercise/document.js, src/views/Dashboard.vue, tests/unit/helpers/convertFirestoreTimestampsToDates.spec.js, tests/unit/helpers/vuexfireSerialize.spec.js, tests/unit/store/exercise/collection.spec.js, tests/unit/store/exercise/document.spec.js
[Trello card](https://trello.com/c/YHpT0LHD/48-5-sanitize-firestore-timestamps)
Also resolves: [Trello card](https://trello.com/c/TFHD2w3G/99-stop-sorting-exercises-by-openat-field-on-the-dashboard-page)
---
This PR maps Firestore `Timestamp` objects to plain JavaScript `Date` objects.
Most [Firestore field data types](https://firebase.google.com/docs/firestore/manage-data/data-types) map to JavaScript primitive types. However timestamp fields (i.e. date & time) are returned as Firestore [`Timestamp` objects](https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp).
In this PR, I've implemented functionality to automatically convert each `Timestamp` instance returned by Firestore to an equivalent [JavaScript `Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript …
=> Convert Firestore Timestamp objects to Date objects

src/components/Form/TextField.vue
Hello Everyone!
In the TextField component: 
- On the label tag, I've added 'govuk-!-margin-bottom-2' in the class attribute, to make the bottom margin smaller.
- The label size is still medium.
The difference is small, however this is with the new margin:
This is it without:
Let me know if this isn't the right way to implement it, or if the margin needs resizing! 
Thanks 🌻
=> Edited Textfield Margin Bottom

src/components/Form/Currency.vue, tests/unit/components/Form/Currency.spec.js
We were receiving an error when using the currency component, due to it 
expecting a number rather than a string. 
- I've amended the component's Value Prop only, to expect a string. I've 
left the type as number in order to keep accessibility features that 
come with this. 
- I've amended the test to expect a string rather than a number to be 
more accurate (Not sure why the number ones were still passing tbh?)
Tests are passing and code has been linted
🌻
=> Amended the Currency component.

src/components/Page/Navigation.vue, src/main.scss, src/router.js, src/views/Exercises/Show.vue, src/views/Exercises/Show/Applications.vue, src/views/Exercises/Show/Contacts.vue, src/views/Exercises/Show/Eligibility.vue, src/views/Exercises/Show/Overview.vue, src/views/Exercises/Show/Shortlisting.vue, src/views/Exercises/Show/Timeline.vue, src/views/Exercises/Show/Vacancy.vue, tests/unit/components/Page/Navigation.spec.js, tests/unit/journeys/page-titles.spec.js, tests/unit/views/Exercises/Show.spec.js
This PR adds a parent Show page and empty templates for child components.
**Change log**
1) Create Navigation component 
2) Create Edit page that uses Navigation component and displays Overview child page by default
=> Add View parent page

src/router.js, tests/unit/journeys/page-titles.spec.js, tests/unit/journeys/signin.spec.js
Copied the scrollBehavior method from the router of the digital platform, and implemented it in the router of apply-admin. 
Tests have not been written for this, and will be addressed later when refactoring the router tests. 
When user testing this, the page will return to the top if the submit button redirects successfully to a new page, and will stay at the bottom on the new page if the scrollBehavior method is absent. It does not work however, if you manually change the urls 🤷‍♀. 
Code has been linted.
All tests are still passing however: 
We were getting a: 
```console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Not implemented: window.scrollTo
``` 
console error under the signin.spec.js and the page-titles.spec files. After consulting with Ollie and Alex, I've …
=> Scroll functionality

src/store/exercise/createJourney.js, src/store/exercise/document.js, src/views/Exercises/Edit.vue, src/views/Exercises/Edit/Contacts.vue, src/views/Exercises/Edit/Eligibility.vue, src/views/Exercises/Edit/Shortlisting.vue, src/views/Exercises/Edit/Timeline.vue, src/views/Exercises/Edit/Vacancy.vue, src/views/Exercises/New.vue, tests/unit/store/exercise/createJourney.spec.js, tests/unit/store/exercise/document.spec.js, tests/unit/views/Exercises/Edit.spec.js, tests/unit/views/Exercises/Edit/Contacts.spec.js, tests/unit/views/Exercises/Edit/Eligibility.spec.js, tests/unit/views/Exercises/Edit/Shortlisting.spec.js, tests/unit/views/Exercises/Edit/Timeline.spec.js, tests/unit/views/Exercises/Edit/Vacancy.spec.js, tests/unit/views/Exercises/New.spec.js
[Trello card](https://trello.com/c/kgY2pLws/53-implement-the-create-exercise-journey-functionality)
This PR adds functionality to power the 'Create an exercise' journey. From the 'Create an exercise' page (`/exercises/new`), the user creates a new exercise and can choose which additional information they want to add in the session.
The 'Save and continue' button at the bottom of each page will progressively save to the database and walk the user through their chosen journey.
At the end of the journey, or if the user chooses not to enter further information, they will be taken to the exercise overview page.
The journey navigation functionality is implemented as a Vuex module called `exerciseCreateJourney`. This is responsible for holding and managing the state of the user's chosen journey. …
=> 'Create an exercise' journey functionality

src/components/Form/CheckboxGroup.vue, src/views/Exercises/Edit/Eligibility.vue, src/views/Exercises/Edit/Shortlisting.vue, tests/unit/components/Form/CheckboxGroup.spec.js
This mighty bug 🐛 was causing our checkboxes to be plagued with a lack of flexibility. 
- Initially, the CheckboxGroup would have a lil fit if you initialised it with anything other than an empty array. To amend this, I've added a created method to the CheckboxGroup component that will emit it's value to be an empty array if it's set to anything that's not an array. This way, you can initialise it to whatever you fancy but at the end of the day, he'll be a big bad empty array, ready for some input. 
- Next issue was that the CheckboxItems were getting all picky about the CheckboxGroup value being set to null, but this was because they were checking the value of the CheckboxGroup before it had a chance to change itself to an empty array. To stop them being so damn hasty, we've added a v-if …
=> Checkbox Bug

src/views/Exercises/Edit/Eligibility.vue, src/views/Exercises/Show/Eligibility.vue, tests/unit/views/Exercises/Show/Eligibility.spec.js
[Trello link](https://trello.com/c/kThXxdMk/116-details-page-eligibility)
- I've changed some of the inputs on the eligibility edit page as part of this work. Mainly that was to change String `"true"` and `"false"` values to Boolean `true` and `false`.
- The way we handle 'other' (please specify) fields is probably something which we could extract out into a helper method or component. It seems quite common.
=> Exercise show eligibility page

src/views/Dashboard.vue
[Trello card](https://trello.com/c/Jxb3cXLN/120-link-to-the-exercise-overview-page-from-the-dashboard)
- Exercise names on the dashboard page now link to the exercise overview page
- I fixed a styling bug with the narrow summary list key (the `.govuk-summary-list__key` class was missing)
- I've hardcoded the reference number to be '118' – this makes the page consistent with the exercise show page, which also has a hardcoded reference number. We know that auto-generated reference numbers are still to be developed, but it looks odd without any reference number displayed on the dashboard.
=> Add links to exercise dashboard page

tests/unit/journeys/page-titles.spec.js, tests/unit/journeys/signin.spec.js
We've made router test files smaller and more readable by using `each` method and looping through the list of pages instead of writing tests for every route separately.
**Changelog:**
Refactor page-tiles and sign in journey specs
=> Refactor router tests

package-lock.json, package.json, src/store/exercise/document.js, src/views/Exercises/Edit/Contacts.vue, src/views/Exercises/Edit/Eligibility.vue, src/views/Exercises/Edit/Shortlisting.vue, src/views/Exercises/Edit/Timeline.vue, src/views/Exercises/Edit/Vacancy.vue, src/views/Exercises/Show/Contacts.vue, src/views/Exercises/Show/Overview.vue, src/views/Exercises/Show/Shortlisting.vue, src/views/Exercises/Show/Timeline.vue, src/views/Exercises/Show/Vacancy.vue, tests/unit/store/exercise/document.spec.js, tests/unit/views/Exercises/Edit/Contacts.spec.js, tests/unit/views/Exercises/Edit/Eligibility.spec.js, tests/unit/views/Exercises/Edit/Shortlisting.spec.js, tests/unit/views/Exercises/Edit/Timeline.spec.js, tests/unit/views/Exercises/Edit/Vacancy.spec.js, tests/unit/views/Exercises/Show/Contacts.spec.js, tests/unit/views/Exercises/Show/Eligibility.spec.js, tests/unit/views/Exercises/Show/Overview.spec.js, tests/unit/views/Exercises/Show/Shortlisting.spec.js, tests/unit/views/Exercises/Show/Timeline.spec.js, tests/unit/views/Exercises/Show/Vacancy.spec.js
To prevent modifying a record in the state we've added new getter that returns a clone of the state instead of an actual state object.
This change is implemented for add Edit and Show pages
=> Add getter to get clone of the state object

src/views/Exercises/Show/Eligibility.vue
In the previous PR, I added the missing conditional reveal TextareaInput component, under the Does ASC apply radios, into the Eligibility Edit page. This PR amends the Eligibility Show page to display the data entered into this TextareaInput component. 
- Added a V-if to display the data in the conditional reveal Textarea 
field under the 'Does ASC apply' radio. 
- Code has been linted.
- tests are passing.
🍁
=> Amended the Eligibility Show page to include 'Additional skills' field

src/helpers/booleanOrNull.js, src/views/Exercises/Edit/Eligibility.vue, src/views/Exercises/Edit/Vacancy.vue, tests/unit/helpers/booleanOrNull.spec.js, tests/unit/views/Exercises/Edit/Eligibility.spec.js, tests/unit/views/Exercises/Edit/Vacancy.spec.js
[Trello card](https://trello.com/c/A0GV0nrk/127-bugfix-unanswered-fields-cause-save-error-because-unsupported-field-value-undefined-on-firestore-update)
When saving a page which contained a boolean input:
- We can't auto-cast falsy field values to `null`, because boolean inputs might be `false`
- But we have to cast unanswered boolean fields to `null` because `undefined` is an invalid field type for Firestore
- I've included unit tests to assert that boolean fields are treated this way
Additionally:
- I updated the "Yes/No" question on the "Vacancy details" page to be a boolean value. I'm fairly sure this [closes a different Trello card](https://trello.com/c/4LGQMCuC/126-change-yes-no-edit-pages-fields-to-be-booleans) too.
=> Bugfix: save unanswered boolean fields

src/router.js, src/views/Exercises/Edit/Contacts.vue, src/views/Exercises/Edit/Eligibility.vue, src/views/Exercises/Edit/Shortlisting.vue, src/views/Exercises/Edit/Timeline.vue, src/views/Exercises/Edit/Vacancy.vue, tests/unit/journeys/page-titles.spec.js
[Trello card](https://trello.com/c/l6X40p9H/148-make-edit-page-headings-add-edit-agnostic)
---
The exercise edit pages now have add/edit agnostic headings.
Page headings used to read, for example, 'Add exercise contacts'
However, the same pages are used both in the 'Create an exercise' journey and the regular edit journey.
The UX team therefore made the decision that page headings on these edit pages should become 'agnostic' of whether they're in a 'create' journey or a regular 'edit' journey.
=> Make exercise page headings add/edit agnostic

src/components/Form/CheckboxGroup.vue, src/components/Form/DateInput.vue, src/components/Form/RadioGroup.vue, src/components/Form/TimeInput.vue
- For all components that have a typical 'heading like' label, I have 
added the `govuk-!-margin-bottom-2` style to it. This is to standardise 
the labelling across all components. Textfield, TextareaInput, and Currency already had this styling applied.
- I have left out Repeatable fields, CheckboxItem and RadioItem, as 
these components did not have a need for the styling to change. 
All code has been linted and tests are passing.
=> Refactored the components' 'label' styling

src/components/LoadingMessage.vue, src/router.js, src/views/Errors/ExerciseNotFound.vue, src/views/Errors/PageNotFound.vue, src/views/Exercises/Edit.vue, src/views/Exercises/Show.vue, tests/unit/components/LoadingMessage.spec.js, tests/unit/journeys/page-titles.spec.js, tests/unit/journeys/signin.spec.js, tests/unit/views/Errors/ExerciseNotFound.spec.js, tests/unit/views/Errors/PageNotFound.spec.js, tests/unit/views/Exercises/Edit.spec.js, tests/unit/views/Exercises/Show.spec.js
This PR adds two 404 pages:
- Main 404 ("Page is not found")
- Exercise 404 ("Exercises is not found")
Also, this PR changes the error message in LoadingMessage component to be "Something went wrong"
**Change log**
1) Create 404 pages
2) Redirect to Exercise 404 page if exercise data is null using Vur router replace() method
=> Create error pages

src/views/Exercises/Edit/Eligibility.vue, tests/unit/views/Exercises/Edit/Eligibility.spec.js
- Added a v-if to the 'does schedule 2(d) or Schedule 3 apply?' question 
that only shows if the `isCourtOrTribunal` field is equal to 'tribunal'. 
- Tests have been added to test this conditional reveal.
All code has been linted and tests are passing.
=> Added a conditional reveal to the schedule 2(d) field

src/components/RepeatableFields.vue
This PR changes the styling of the button only. I've used the GOVUK design to reflect the buttons that the UX team wanted.
- Changed the 'Add another' and 'Remove' button styling to match the 
V2.2 prototype. No tests have been written (Wasn't sure they were 
needed). 
All code has been linted and tests are passing.
=> Amended the styling of the Repeatable Fields component buttons

src/components/RepeatableFields.vue, tests/unit/components/RepeatableFields.spec.js
This PR restricts rendering of the Remove button in a case when only one repeatable field is rendered.
**Change log**
1) Render Remove slot only if there is more than one field
2) Tests
=> Add check for number of rows

src/views/Exercises/Edit/Eligibility.vue, tests/unit/views/Exercises/Edit/Eligibility.spec.js
This PR *also* contains amendments to the Eligibility Information page. This could cause a merge conflict, so treat it carefully. 
Things that have been completed:
- The 'Post Qualification Experience' question only renders if the role is _not_ 'non-legal'. (ie You will _not_ see the PQE question if typeOfExercise is equal to 'non-legal'.)
Tests have been written and are passing. 
Code has been linted.
=> Additional amendments to the Eligibility Information page - *Will cause merge conflicts*

src/views/Exercises/Edit/Eligibility.vue, tests/unit/views/Exercises/Edit/Eligibility.spec.js
This PR contains all amendments to the eligibility page. This work equates to multiple tickets. 
Things that have been completed:
- The Qualifications question will only render if the typeOfExercise is _not_ non-legal.
- The Memberships question will only render if the typeOfExercise _is_ non-legal or leadership
Tests for all these tasks have been written up, and are passing. The code has been linted too.
=> Amendments to the Eligibility Information page

src/views/Exercises/Show/Vacancy.vue
Removed the extra 'About the role' rendering on the Vacancy show page. 
Linted and tests are passing
=> Amended the Vacancy Show page to not list about the role twice

package-lock.json, src/views/Exercises/Edit/Vacancy.vue, src/views/Exercises/Show/Vacancy.vue
Update on things we discussed in last code review.
Generate download URL on the fly based on the value stored in: 
- this.exercise.uploadedJobDescriptionTemplate
- this.exercise. uploadedTermsAndConditionsTemplate
=> Show uploaded files in vacancy details page

src/helpers/Timeline/exerciseTimeline.js, src/views/Exercises/Edit/Timeline.vue
* I think this spans multiple tickets maybe? not sure 😬 *
- Added some more date fields to the Edit/Timeline page - collects some additional data we were missing. Ticket didn't specify what type of date, so I've left it as a full date but this can easily be changed to a month only date if needs be so keep ya eyes peeled for that. 
- Added this new and shiny collected data to the Show/Timeline page. It doesn't exactly match the wireframe given, because the wireframe excludes the preexisting data about QT's and Scenario tests. I can remove this if needed to however Warren and I felt it was worth leaving in for now until we get clarity. 
- What needs to be done: 
This PR doesn't include the whole candidate/admin timeline split thing. This PR just shows all the required fields to the Admins. …
=> Timeline Additions

src/components/DownloadLink.vue, src/views/Exercises/Show/Downloads.vue
I tried to use the standard govuk-link styling to get the download links to look like the gov ones, however that style required a href. When you gave it a href, it just redirected to it and didn't conduct the download which was dumb. I tried using fancy CSS styles but they were hard to implement the whole 'visited state' thing.
My (and Warren's) solution was to add in the href using ```href="javascript:void(0)"``` to make the govuk-link style happy but remove any unwanted side effects of the href. This however didn't make the download links that cute purple once clicked. Now we have a data object that has keys for each document, and an initial value of false. Once the @click triggers the data object to change that document's value to true, an object bound to the class will apply a new …
=> Added styling to the download links

src/helpers/Timeline/exerciseTimeline.js
Admin/staff side
-	on the timeline please amend "contact IAs" to "JAC Contacts IAs"
Show/Timeline now shows "JAC Contacts IA's" as the contact independent assessors entry
=> Timeline. Text changes

src/components/RepeatableFields/LeadJudge.vue, src/views/Exercises/Edit/Contacts.vue, src/views/Exercises/Show/Contacts.vue
Please can we add an "add another" button after the "Lead Judge" field on the Contacts page.
=> Add another option required for "Lead Judge" on Contacts

src/views/Exercises/Edit/Contacts.vue
We need to amend this help text to indicate that this is for email addresses only.  
Please amend to "You can return to this page later to add or change contact emails".
=> ADMIN: Change help text on Contacts Page

src/App.vue, src/views/Exercises/Edit/Vacancy.vue, src/views/Exercises/Show/Vacancy.vue
Please add this question between "Jurisdiction" fields and "Appointment type"
Is statutory consultation waived for this exercise?
Yes or No.
If Yes add text area with a title: "Explain why". 
- I've added this question to both edit and show pages, and I've added the new variables to the data sheet. Were you planning on adding yes or no to the look ups? I've left them out as other variables on the show page didn't use lookup for their yes/no rendering, but if you want me to add them in then I can?
=> ADMIN:  Add Question to "Vacancy Information" about Statutory Consultation

src/helpers/Timeline/exerciseTimeline.js, src/views/Exercises/Edit/Timeline.vue
Admin/staff side
•	On the ‘Timeline’ page there is no option to add a date for an Equal Merit Provision second interview/online tie break test.
Add additional date field for EMP Second Interview
=> Timeline. Add 'EMP Second Interview' date field

src/components/Candidates/EqualityAndDiversity.vue, src/views/Candidates/CandidatesView.vue, src/views/Exercises/Show/ApplicationFull.vue, src/views/Exercises/Show/Applications.vue, src/views/Exercises/Stages/HandoverList.vue, src/views/Exercises/Stages/RecommendedList.vue, src/views/Exercises/Stages/ReviewList.vue, src/views/Exercises/Stages/SelectedList.vue, src/views/Exercises/Stages/ShortlistList.vue
This PR deals with links to Candidade Detail page.
The links were added from:
- from Applications (applicationsFull)
Stages:
-  Review
-  Shortlisted
-  Selected
-  Recommended
-  Handover
=> #511 Links to candidate page detail

src/views/Exercises/Edit/Downloads.vue, src/views/Exercises/Show/Downloads.vue, tests/unit/views/Exercises/Edit/Downloads.spec.js, tests/unit/views/Exercises/Show/Downloads.spec.js
Add upload/download for: 
- Pensions Information
- Competency Framework
- Welsh Translation
=> #202 Exercise Document Downloads

src/views/Exercises/Stages/ShortlistList.vue
Adds an existence check up the object tree to ensure something exists before we try to use it. This has caused Sentry errors in the past.
=> #603 Add existence checking for .shortlisted

src/store/auth.js, src/views/SignIn.vue
Catch and handle errors that occur within the "sign in with Google" frontend process. 
This is most commonly caused by people mashing the button (which generates an exception as only one pop up will be opened). 
We now handle the exception and display it to the user, unless there is a more important `authError` which comes from the Store  (eg. not a valid Google account).
=> #605 Handle Google sign in errors

src/views/NotificationsList.vue
Adds the number of queued notifications to the end of the tab in brackets, to avoid manual counting (or people copying data into a spreadsheet etc.) 
This changes the `tabs` property from data to a computed prop. The length is only appended when there are queued notifications.
=> #631 Add number of queued notifciations

src/views/Exercises/Edit/Downloads.vue
Prevents more than one IA document being uploaded. 
Have confirmed with @ClaireTroughtonJAC that this is the expected behaviour. `assessments` cannot display more than one file (there is no "error" here - just that any more than a single file will be ignored) 
We'll leave the logic in to display multiple files in `admin` and `apply`, to avoid breaking anything on existing exercises.
=> #647 Enforce single file upload on IAs

src/main.js
We can't use the Node running environment to determine between prod and s101 as we build for prod in both environments. 
We can determine whether the subdomain is `admin` or `admin-staging` and use that to set the Sentry environment.
=> #635 Change to checking the URL to see which environment we're in

src/views/Exercises/Applications/Application.vue
This has been a bit confusing :sweat: 
The ASC should display regardless of whether SoS, CV etc. are required in addition. 
This change moves the ASC out of the SoE and SoS blocks so they always display when they exist. It also removes the SoE block which does not have a file upload, and therefore will be encompassed in the ASC block. 
This will show in the panel pack too.
=> #661 - Missing additional selection criteria in Application.vue

src/views/Exercises/Stages/HandoverList.vue, src/views/Exercises/Stages/RecommendedList.vue, src/views/Exercises/Stages/ReviewList.vue, src/views/Exercises/Stages/ShortlistList.vue
Draft PR for comments and thoughts :pray:  
Several things to note about the implementation: 
- This does not use [Firestore pagination](https://firebase.google.com/docs/firestore/query-data/query-cursors) deliberately for performance reasons. In order to paginate properly, we need to know how many records there are in the first place (ie. how many pages). As Firestore has no mechanism for us to retrieve just a count of the query, we have to load all the records any way (just to count them). It is therefore undesirable to initially request all the data, then continue making requests to Firestore each time a user changes page for the page of data we want - having loaded all of it, we might as well slice it ourselves. 
- There are no changes to the Store. It's easier to make these changes …
=> 669: try out pagination on ShortlistList

src/components/Page/Pagination.vue, tests/unit/components/Page/Pagination.spec.js
Hide the pagination component when we only have a single page to show, and thus don't need to display any page controls.
=> 677: Don't show pagination for a single page

src/App.vue
For an initialism which begins with _scaleable_, i had some real difficulty getting the SVG to adhere to the desired proportions. 
However i managed to get there in the end.
I have also made some changes to the formatting of the template in the App.vue, so now the template's single child contains only three elements; header, main, and footer. This was done in order to allow the footer to fill the full width of the screen, as shown in the prototype.
I have currently disabled all content within the footer, as i'd like some assurance that at JAC we are indeed offering 'All content is available under the Open Government Licence v3.0, except where otherwise stated' as the footer text suggests
=> footer inserted

src/App.vue, src/styles/main.scss
CSS additions to App.vue.
Previously the single child of the main template contained three elements, using positioning in the styles section within App.vue, ive now achieved the desired placements.
I coulda/shoulda/woulda extracted this CSS to the main files, this might need doing eventually.
=> Make footer stay at bottom of page

src/views/Exercises/Applications/Application.vue
Changes made to `views/Exercises/Applications/Application.vue`
- "download-as-pdf-div" id name changed to "panel-pack-div" as both download options now use this same html section
- Button for dl as doc added
- downloadAsDoc function added which seems to work as expected
Potential improvements could be made, the downloaded doc has all required info, but doesnt have the same styling and spacing as the webpage, which would be nice to have.
=> Download Panel Packs as Doc

src/views/Exercises/Applications/Application.vue
(i think) new ESlint rules mean that useless lets are NOT allowed, otherwise im not sure how this slipped through, regardless three offending let's have been changed to const's
=> Change let to const

src/filters.js, src/views/Exercises/Applications/Application.vue
This adds a couple of turnery checks to see if `application.createdAt` and `application.appliedAt` are null. 
The behaviour is now:
- If there is a valid date, the date is formatted and displayed
- If there is no date, we display "unknown" (new behaviour)
- If there is data in the field but it is not a valid date, "Invalid Date" will be shown (I think this is expected) 
The reason this took so long is Vue weirdness in it's overloading of bitwise-OR: https://github.com/vuejs/vue/issues/5449#issuecomment-294337677
Very much a TIL moment.
=> #595 - Add null check for application submitted/created dates

src/components/Form/FileUpload.vue, tests/unit/components/Form/FileUpload.spec.js
Changes the `FileUpload` component in admin to restrict the type of extensions that can be uploaded. This automatically works for anything that imports `FileUpload` eg. `MultiFileUpload`. 
Includes tests for the new functionality. 
Notes: 
- This is not enforced on the backend/in the bucket. (https://github.com/jac-uk/digital-platform/issues/327)
- This only checks the declared extension, not what the file content actually is 
- This only affects admin. I'll replicate the changes once approved (please monorepo soon!) 
Please let me know your thoughts :smile:
=> #206 - Restrict file uploads to certain extensions

src/components/Form/FileUpload.vue, tests/unit/components/Form/FileUpload.spec.js
Component change plus tests to limit files to 2MB. 
I'll copy this across to the others once agreed.  We _could_ make size an optional prop but since it's 2MB across all of the sites and I don't really see why we'd change that, so I would suggest this can be an improvement later if needed.
=> #728 Restrict files to 2MB

src/views/Exercises/Applications/Application.vue
- Extract functionality for removing print-none items into 'formatPrintReadyPanelPack' function.
- Have PDF + Doc export use new function for formatting to remove elements we dont want to show
All work localised to application.vue.
Perhaps this function might eventually want moving into a helper file where it can be accessed by multiple components, likewise **formatPrintReadyPanelPack** could perhaps be given a more catchy name
=> Extract remove print-none to function, make pdf+doc use formatting

src/helpers/date.js, src/store.js, src/store/assessment.js, src/views/Exercises/Tasks/IndependentAssessments.vue, tests/unit/helpers/date.spec.js
Helper functionality:
- New `isDateGreaterThan` date helper with tests
- 'Borrowed' the `assessment` store with modification to allow updating single assessment record 
- Register `assessment` in `store.js` 
Functionality: 
- Running late IAs (ie. those not submitted but past due date) show as `LATE`
- Submitted late IAs (ie. those submitted past due date) show as `LATE`
- Needing approval IAs (ie. those submitted past due date) have download button hidden and an approval button shown/
- Allows approval for late IAs to be approved (which allows them to be downloaded)
Rejection for late IAs is implicit (can be changed - ticket isn't clear on this)
=> #711 - Identifies late IAs in admin

src/views/Exercises/Edit/Downloads.vue
This fixes a bug where files were being uploaded with identical idents (ie. file names) and so uploading one of: 
- Pensions Information
- Competency Framework
- Welsh Translation 
would overwrite the Candidate Assessment Form, and all 4 would download the same file.
@warrensearle please could we roll this as a hotfix to admin? We'll also need to communicate this to teams I think @ClaireTroughtonJAC - any ideas?
=> #739 - Fix incorrect idents causing file overwrites

src/helpers/export.js, src/views/Exercises/Show/Applications.vue, src/views/Exercises/Show/Reports/Diversity.vue, src/views/Exercises/Show/Reports/Handover.vue, src/views/Exercises/Show/Reports/ReasonableAdjustments.vue, tests/unit/views/Exercises/Show/Applications.spec.js, tests/unit/views/Exercises/Show/Reports/ReasonableAdjustments.spec.js
Turns out Excel can't deal with sheet names longer than 31 characters.
=> Fixed XLSX exports being 'corrupted'

src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
Included a button to call the `activateQualifyingTest` cloud function.
Note a confirmation step/modal is still needed here.
=> #761 Activate button should call cloud function

src/views/Exercises/Show/Overview.vue
Includes another (temporary) button!
This one enables admin user to allow late applications to be processed in 'stages & status'.
When we have roles this can be for super admins only. That said there will be a point in the future when existing exercises have all been processed and so this button will no longer be relevant and can be removed.
=> #784 Enable processing late applications

src/components/Form/DateInput.vue
This removes again the `Date.UTC` call that was added in #848 and removed in #831.
Instead I have changed the default time to 13:00. Partly because JAC tends to use 13:00 as default time for launching an exercise, for example. Mainly because this means we bypass the BST daylight saving issue that was being experienced where a default time of 0:00 was (when in BST) being converted to 23:00 the previous day.
=> #860 Fix DateInput component not allowing datetime

src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
Ref num for QT downloads is sometimes missing and when working on a feature i hardcoded it to a string, ive now added a fallback default empty string which will show when the field isn't present and the same thing for the fullName field which will default to the name field
=> Fix reference number in qt score download

src/components/Form/Currency.vue, src/filters.js, src/views/Exercises/Edit/Vacancy.vue, src/views/Exercises/Show/Vacancy.vue, tests/unit/components/Form/Currency.spec.js, tests/unit/filters.spec.js
- New salary as text
- All new exercises will show a free text field where they can out the salary (no bands anymore)
Old exercises will show the Salary bands
=> #970 Update judicial salary bands

src/views/Exercises/Show/Reports/EligibilityIssues.vue
Issues are now on the applicationRecord, rather than application, so have updated to report to use correct data
=> #1071 Fix eligibility issues report

src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/Responses.vue
Testing instructions are in the ticket description along with test scripts for reference.
=> #1198 Fixed issue of a QT results  download unable to start if candidates skip questions and submit with no answers.

src/views/Exercises/Show/Reports/Handover.vue
As discussed with @KateMJAC, I've hidden the button until the JO Handover epic is complete, to avoid confusing users.
=> #1192 Hide the Transfer Handover button until the epic work is complete

package-lock.json, src/App.vue, src/main.js, src/store.js, vue.config.js
This PR grabs the version number from `package.json` and injects it into our app as follows:
- Sends the version number to Sentry. This will help track which versions introduce or fix errors 😄 
- Makes version number available in `$store.getters.appVersion`
- Displays the version number in the header
**Testing**
On develop (or localhost) check that version number is displayed in the header
On staging please check that errors in Sentry now come through with the version number
**Expected**
=> #1201 Include version number in UI and Sentry

src/components/ModalViews/LeadershipJudgeDetails.vue, src/views/Exercises/Applications/Application.vue, src/views/Exercises/Edit/AssessmentOptions.vue, src/views/Exercises/Show.vue
Enables staff to turn Independent Assessments off and to select a _new_ assessment method, Leadership Judge Assessment.
**To test**
- Go to Exercise > Assessment Options > Update
- Notice two new checkboxes
- Set them on or off and save
- In the side navigation notice that Tasks > Independent Assessments link only shows when the corresponding assessment option has been selected
- In Exercise > Applications > Application notice that IAs and Leadership Judge Details only show when the corresponding option has been selected
- Can edit IAs (still)
- Can edit Leadership judge details
**Note** 
This is the minimum viable and additional effort will eventually be needed on the following:
- Replace the current Assessment Options radios with a set of checkboxes instead so staff can select from the …
=> #1212 Enable leadership judge assessment

src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/TestBuilder.vue, src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
- redirect the user to add emails after creating the questions and before the review page
- disable the CREATE DRY RUN button when there are no emails, and add a link to add email as a hint message
Please check the ticket for images
✅ Developers
✅ UTG
1. Create a DRY RUN TEST without adding emails at the end
2. Check that, after adding the questions you are redirected to add emails before being redirected to the review stage
2. Approve the test and check that the link is disabled and a message is a link to add emails
3. Add emails
4. Go back and check that the link is enabled
Please check the ticket number
=> #1279 Disable the button ‘Create dry run tests’ if there are no candidates

src/views/Exercises/Show/Reports/CharacterIssues.vue
The character issues report was either blank or showing the wrong data.
This PR fixes that by ensuring we are looking at the `applicationRecords` collection instead of `applications`.
This un-blocks #1139 which will make further changes to this report
✅ Developers
View the character issues report and check that it is now displaying.
NOTE: #1139 will make further changes / fixes after which more thorough testing can happen
---
=> #1071 Fix character issues report

src/views/Exercises/Applications/Application.vue
Added numbers for location preferences, so order of preference is clearer to admins.
✅ Developers
✅ UTG
- Ensure location question is RANKED choice 
- Observe a candidates application
- Check numbers display next to correct location preference 
---
=> Display location preferences

src/router.js, src/views/Exercises/Tasks/QualifyingTests/Cover.vue, src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/NewFromClipboard.vue, src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
This PR adds a button to allow:
1.  the copy of a QT test to the clipboard
2. the paste of the clipboard when creating a new QT test
✅ Developers
✅ UTG
1. Go to any QT test, and a button "Copy QT to clipboard"
> when clicked, it will show as copying and then the success message will show up
2. On the QT list, a button with the text "Create new from clipboard" is showing up
> Paste the content of the clipboard and follow the instructions
---
=> admin#1203 Ability to copy a QT test

src/views/Exercises/Tasks/QualifyingTests/QualifyingTest/View.vue
Disabled OPEN TEST button if there is no candidates on the test
✅ Developers
✅ UTG
1. Create a MOP UP test
2. GO to the Qualifying test detail page and verify that the OPEN TEST button is disabled
3. Go to the original test where the mopup was created from, select a user and transfer it to the new mopup
4. Return to the MOPUP qualifying test detail page and check that the OPEN TEST button is enabled allowing the user to OPEN the test for users.
---
=> 1017 Mop up test won't start if the test is open before candidates added

.github/workflows/codeql-analysis.yml
---
A script that enables GitHub Code Scanning to run on a schedule.
✅ Developers
Once the code has been merged, GitHub should start scanning the main develop every day and alerting us when it finds vulnerabilities in code, i.e. code that could allow remote code injection attacks, unsanitised inputs to be maniuplated, etc.
---
=> Enable GitHub Code Scanning

src/views/Candidates/Actions.vue, src/views/Candidates/CandidatesView.vue
- ✅  Include primary ticket number in title - e.g. "#000 New styling for widget" - and any additional tickets in description
- ✅  Fill in the details below and delete as appropriate
---
I've created a new tab called 'Actions' in the Candidate view which only superadmins can see. When a superadmin goes to the tab, a callable function is called to retrieve the candidate's current login email address. When a superadmin enters the new address and clicks 'Update', a callable function is called and candidate's email address is updated.
✅ Developers
- Login to Admin,
- Select a candidate from Applications->Applied(any candidate)
- Go to Candidate view to Actions tab. The current email address will be visible.
- Enter a new email address and click Update.
- …
=> #1054 Added a new component to enable change of candidates login address

src/views/Exercises/Applications/Application.vue
The number of sitting days displayed in Full Information tab in Applications on Admin now matches the number of days requested in Eligibility Information section of the exercise.
✅ Developers
✅ UTG
1. Create an exercise on Admin, input the desired number of days under Eligibility Information section for the question "Does previous judicial experience (PJE) apply?" and note this number.
2. Apply for a vacancy on Apply.
3. Check the candidate application on Admin->Applications->Applied->(Candidate)->Full information tab->under the Judicial Experience section, note the label "Sat for at least (NUMBER) days". Number displayed here should match the number entered for "Does previous judicial experience (PJE) apply?" in step 1. …
=> #1324 Made changes to display correct number of days in Full Information view

src/views/Exercise/Stages/RecommendedEdit.vue
---
Currently, admins cannot move a candidate from Recommended stage to Handover stage if they have either eligibility issues or character issues.
This PR provides an option to override the warning presented when this is attempted
✅ Developers
✅ UTG
View an exercise with applications in the Recommended stage. Select one (or more) which has issues, then click `Set Status` and select `Approved for immediate appointment`.
You should see the warning and an option to proceed with change. This overrides the warning and moves the candidate to Handover.
---
=> Hot fix for recommended to handover

src/helpers/exerciseHelper.js
Fixes a bug where Statement of Eligibility is being requested when it has not been fully configured. See #1445 for more info.
**Note**
- the same fix has been applied to Apply in https://github.com/jac-uk/apply/issues/809
- the `exerciseHelper` file is identical between `apply` and `admin` repos. It will be moved to `jac-kit` once it has been in flight a little longer
✅ Developers
Please just code review.
=> #1445 Statement of eligibility fix

src/views/Exercise/Details/Timeline/Edit.vue
The time for IA hard limit on exercise Timeline was changed to 1pm.
✅ Developers
✅ UTG
Go to an exercise->Timeline, scroll down to Independent Assessors section. A label next to Independent Assessors hard limit field should say 'An assessor cannot submit after 1:00 pm on this date.'
Please see [the video here](https://drive.google.com/file/d/1P3Y72UGwh_UChdIDN0okkq73XKEmp_FE/view?usp=sharing).
---
=> Changed IA hard limit time

src/store/qualifyingTest/qualifyingTestResponses.js, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
The ability to reset a QT response via the admin portal
✅ Developers
✅ UTG
- Find an exercise with a past QT, which has responses.
- Select completed (finished) response.
- Observe the 'reset' button on the response page (only available for authorised digital accounts)
- Clicking the reset button should open a modal
- Warning appears in modal
⎿Clicking cancel closes the modal and prevents reset
⎿Clicking confirm resets the QT
- Once reset, a QT will be able to be marked as completed.
🟠 Medium risk - this does change code that is shared with other areas.
---
video: [here](https://drive.google.com/drive/u/1/folders/1-kkQ1_ArvpIiHIid7NBPDzwnPoss0TPR)
https://user-images.githubusercontent.com/44227249/126502388-b66c928d-a5e4-4dde-9a21-c132936f9360.mov
---
_can …
=> #730 QT response reset and confirmation modal

src/views/Exercise/Tasks.vue
Fixes a bug where the link to set up a Sift does not show for Name-blind sifts
✅ Developers (code review only)
**Prepare your exercise**
Set up your exercise to have 'Name-blind Sift' selected as a shortlisting method and **not have** 'Sift' as a shortlisting method. Also ensure the Timeline is populated with corresponding dates.
Begin processing applications for the exercise (if not already started).
**Expected** ([see this fix](https://jac-admin-develop--pr1473-fix-1472-sift-link-m-qkj73tyf.web.app/))
Visit Tasks and notice there's a link to Sift
**Previous to this fix** ([see admin-develop](https://admin-develop.judicialappointments.digital))
Visit Tasks and the Sift link is missing …
=> #1472 Fix: name blind sift link not showing up

src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue
During a QT we collect information about the user's platform, browser and local time. Here we are displaying that information in Admin.
✅ Developers
On a qualifying test response page notice there is a new tab called 'Client'.
The 'Client' tab **should not** be available before the test has been started (as we haven't been able to collect data from the user).
The 'Client' tab **should** be available during and after a test has been started.
When available the 'Client' tab should display key information about the user's local environment such as:
- Platform
- Browser
- Timezone
- Initial time offset. This is the difference in seconds between the user's local time and our server's time
- Latest time offset. A significant change here from the initial value indicates that the …
=> #1356 Display client details of QT participant

src/components/RepeatableFields/SelectionCriterion.vue, src/views/Exercise/Applications/Application.vue, src/views/Exercise/Details/Eligibility/View.vue
Options have been added to add a custom word limit to ASC, when a custom number is given this info is also shown in the the exercise eligibility information overview and on application overviews.
✅ Developers
- Set up/edit an exercise to have ASC.
- Add a question with a custom word limit
- Navigate to the applications
- Add a question with a custom word limit
- Observe the limit is presented and works
•note•  the word count functionality has already been tested this is strictly about the custom number
🟢 Low risk - this is a self-contained piece of work
---
=> Input custom ASC word limits

src/store/auth.js
Added another email address to the list of approved users.
✅  BA
The statistitian should be able to create an account and log in to the platform.
---
=> #1488 Added access for approved statistitian

src/components/PanelPacks/PanelPacks.vue, src/router.js, src/store/panels.js, src/store/stage/review.js, src/views/Exercise/Tasks.vue, src/views/Exercise/Tasks/PanelsNew.vue, src/views/Exercise/Tasks/PanelsView.vue, src/views/Exercise/Tasks/Scenario.vue
This PR closes #1497
---
This pull request exports scenario tests to a google drive folder.
Please also see https://github.com/jac-uk/digital-platform/pull/655
A new tab has been added to the tasks screen - with `Sift` and `Selection Day` we now have another one called `Scenario Responses`. The functionality is identical to these other two, except for when you click export, the process exports the scenario tests the candidate has taken into a google drive folder rather than their application data. Any person who has done no test does not have a folder created for them, and 1 file is created within that folder for every test that user has completed.
Candidates available to be put onto a panel on this screen must have the status of ` Passed scenario test` which is referred to in a few …
=> #1497 scenario test panel packs

src/filters.js, src/views/Exercise/Reports/Diversity.vue, src/views/Exercise/Stages/HandoverList.vue, src/views/Exercise/Stages/RecommendedEdit.vue, src/views/Exercise/Stages/RecommendedList.vue, src/views/Exercise/Stages/ReviewList.vue, src/views/Exercise/Stages/SelectedEdit.vue, src/views/Exercise/Stages/SelectedList.vue, src/views/Exercise/Stages/ShortlistedEdit.vue, src/views/Exercise/Stages/ShortlistedList.vue
This code enables EMP flag on the basis of 'ethnicity' or 'gender' to be added at the shortlisted and recommended stages. 
An accompanying digital platform ticket adds these stats to the diversity report.
These results are then displayed on platform on the diversity report page.
✅ Developers
✅ UTG
- Navigate to an exercise where applications are closed and candidates are being processed. 
- Progress a candidate or candidates, through the stages, adding EMP and observing available options.
https://user-images.githubusercontent.com/44227249/142028307-d2425aa1-3cc0-4484-af2f-d0d6b6af423d.mov
=> 1498 - record EMP basis 

src/views/Exercise/Applications/Application.vue
'schedule-2-d' questions and answers were not being displayed to admins. 
This must have been accidentally removed at some point, i've now inserted the fields into the application overview.
✅ Developers
✅ UTG
- Configure an exercise to ask schedule-2-d questions. (eligibility > schedule)
- [Apply side] apply/edit application to answer schedule-2-d questions
- ensure the answers are displayed on application overview
🟢 Low risk - this is a self-contained bug fix
---
=> #665 - show 2d questions and answers

.github/workflows/on-pull-request.yml, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Review.vue
Fixes cross-site scripting vulnerability raised by pen test team
✅ Developers
Create a qualifying test with html in the following field:
- Question Title
**Before the fix**, observe that the html is rendered on the QT Review screen and also on the QT Response View screen. This means that malicious html/javascript would also be rendered
**After the fix**, observe that the html is shown as plain text on the QT Review screen and also on the QT Response View screen.  Any malicious html/javascript would **not** be rendered:
---
PREVIEW:STAGING
=> #1533 Hotfix QT xss

src/components/Page/InformationReviewSectionRenderer.vue, src/views/Exercise/Applications/Application.vue, src/views/Exercise/Tasks/CharacterChecks.vue, src/views/InformationReview/CharacterInformationSummaryV2.vue, src/views/InformationReview/ExperienceSummary.vue, src/views/InformationReview/PreferencesSummary.vue
issues addressed
- Modal wont cancel 
- PQE blank fields bug 
- char info shows 'no info...' rather than no 
- Inputing custom othertask overwrites tasks 
- a few places relied on `obj.change` which was meant as a check for the existence of the value, currently doesnt accommodate false values 
=> - Modal wont cancel, PQE blank fields bug, char info shows 'no info...' rather than no

package-lock.json, src/components/Page/InformationReviewRenderer.vue, src/components/Page/InformationReviewSectionRenderer.vue, src/views/InformationReview/CharacterInformationSummaryV2.vue, src/views/InformationReview/ExperienceSummary.vue
Fixes issues with application view
The following issues have been addressed:
- Character Information. Only show details when candidate answered Yes
- Character Information. Other character issues. Show Yes|No rather than `code`
- Gaps in Employment. Show 'No answers provided' when data is empty
- Gaps in Employment. Show Details instead of Organisation and Job Title
Check that the preview url (below) solves the issues addressed by this PR
Compare with live/production
---
=> #260 Application view improvements

src/components/Page/InformationReviewRenderer.vue, src/views/Exercise/Applications/Application.vue, src/views/InformationReview/PreferencesSummary.vue
The application view was displaying answers for welsh questions according to some questionable logic, which ultimately meant that the collected answers werent being shwown to admins. 
I've made changes so that the application view shows answers based purely on exercise configuration. 
✅ Developers
✅ UTG
- Configure an exercise to have a welsh requirement (ANY)
- Ensure your requirement is reflected in application overviews
🟢 No risk - this is a self-contained bug fix
---
=> #664/welsh posts

src/views/Exercise/Applications/Application.vue, src/views/InformationReview/AssessmentsSummary.vue
Prior to #260 admins could edit both the assessors and self assessment sections, 260 limited this to superusers, this reenables all admins
✅ Developers
✅ UTG
- Go to application view as non super user
- Click Edit at the top of the page
- Edit IA
- Edit Self Assessment
---
https://user-images.githubusercontent.com/44227249/148557980-208703ae-cb1a-46f3-aafd-484cf0bb522a.mov
(NOTE VIDEO RECORDED AS SUPER USER)
(SCREEN SHOT FROM NON SUPER USER)
---
=> enable all admins to edit assessments

src/views/InformationReview/CharacterInformationSummaryV2.vue
Dodgy data going into driving disqualifications.
This small change change mean the actual data, not a conditional as was erroneously being passed in is being displayed.
✅ Developers
✅ UTG
- View driving disqualifications on a application who has answers to the v2 character form, 
- The answer to DD should no longer always be yes.
---
---
=> Repair display of driving disqualification answers

src/views/Exercise/Applications/Application.vue, src/views/InformationReview/CharacterInformationSummaryV1.vue
Revision of `isVersion2` computed, which had an oversight causing the wrong version to show.
Detail field in v1 character from on application view now only shows if true, or in edit mode.
✅ Developers
✅ UTG
- Observe Character form is displaying correct Qs and As
- Ensure 'details' only show when an character issue has been marked as true
=> #1545 - Revise Character issues version logic

src/components/PanelPacks/PanelPacks.vue, src/helpers/authUsers.js, src/store/auth.js, src/views/Exercise/Tasks/PanelsView.vue
panel pack needed Table Component to be updated to work with latest jac-kit version
✅ Developers
✅ UTG
- Go to an exercise ready for panel pack creation
- Create or view a panel
- Add a candidate if needed
-  ensure candidate table appears
---
=> Fix tables display of candidates within panel pack

src/views/InformationReview/AssessmentsSummary.vue
`AssessmentsSummary` component was erroring on certain application overviews preventing it from being edited.
This fix adds an additional check for the expected value.
✅ Developers
✅ UTG
- Visit an application such as this one [https://admin-develop.judicialappointments.digital/exercise/QMrEnj3xZITwvJG0WK12/applications/applied/application/6Rx2gynLlaAd14BrE49R] on the current development environment.
- observe that the last blocks of application data are not editable.
- visit the same application on this branch
- observe data now editable (file uploads etc)
Have permissions been considered for …
=> fix assessments edit

src/views/Exercise/Reports/Custom.vue
---
Add candidate reference number to custom report
✅ Developers
Enter an Exercise, go to Reports and then Custom Report. Click the drop down for Select a column to display and click on Add candidate reference number. The Candidate reference will then load on screen, just below the drop down box. 
Demo:
---
=> #1555 Add candidate reference number to custom report

src/views/Exercise/Applications/Application.vue, src/views/InformationReview/CharacterInformationSummary.vue, src/views/InformationReview/CharacterInformationSummaryV1.vue, src/views/InformationReview/CharacterInformationSummaryV2.vue
a few tweaks and fixes to keep #260 working
✅ Developers
✅ UTG
- Applications which had not completed the char-survey couldn't be edited by admins, `v-if` was only checking the data, not the edit mode toggle
---
=> Edit application fixes

src/filters.js, src/views/InformationReview/EqualityAndDiversityInformationSummary.vue
Update to support the change to PAJE answers, as outlined in https://github.com/jac-uk/digital-platform/issues/666
There's a corresponding change in Apply here: https://github.com/jac-uk/apply/pull/849
✅ Developers
✅ UTG
Admin changes can be previewed here: https://jac-admin-develop--pr1554-feature-666-paje-iw2wa8lq.web.app/
Apply changes can be previewed here: https://jac-apply-develop--pr849-feature-666-paje-dbsqxipr.web.app/
In the Equality and Diversity Survey the question 'Have you taken part in the Pre-Application Judicial Education Programme (PAJE)?' should now offer the following answers:
- Yes - online resources and judge-led discussion group course
- Yes - online resources only
- No
- Prefer not to say
We need to check that this change is reflected in both Apply …
=> digital-platform#666 Change to PAJE answers

src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Responses.vue, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/View.vue
Simple change to replace the wording "Out of time" and "DNF" with "(auto-submitted)" for QTs.
See /jac-uk/digital-platform/issues/657 for details
✅ Developers
✅ UTG
Log in to admin.
Locate a QT which has completed and has responses.
Notice that 'Out of time' has been replaced by 'Auto-submitted' on the following pages:
- QT dashboard
- QT responses list
- QT response
See screen grabs below.
**QT dashboard. Before**
**QT dashboard. After**
**QT responses list. Before**
**QT responses list. After**
**QT response. Before**
**QT response. After**
---
=> digital-platform#657 Identify auto-submitted QTs

src/views/Exercise/Reports/Custom.vue
---
Add qualified date and post-qualification experience date columns to custom report
✅ Developers
Enter an Exercise, go to Reports and then Custom Report. Click the dropdown for Select a column to display and click on Add `Qualifications` and `Post-qualification experience`. The two columns will then load on screen, just below the dropdown box. 
Demo:
---
=> #1525 Static Report

src/views/InformationReview/PreferencesSummary.vue
Some exercises are erroring due to having no additional working preferences, not a critical error, but good for housekeeping
✅ Developers
???
This should remove the sentry error
- See attached ticket and sentry issue
---
=> Prevent error on exercises w/o additional working preferences

src/main.js, src/store.js, src/views/Exercise/Details/Overview.vue
- Closes #1614 so Process Application buttons now display correctly
- Hidden the Create Test Applications button on the Production environment
- Consolidated environment logic
✅ Developers
✅ UTG
On the Exercise Overview page for an exercise which has received applications observe the following:
- 'Process applications' button is present and working
- 'Create test applications' button is present on develop and staging environments but not present on production
🟢 Low risk - this is a self-contained piece of work 
---
=> #1614 Process applications button missing from exercise overview

src/firebase.js
The initialisation of the app check had some redundancy issues when the token isn't present. 
Changing the chronology and setting the appCheck constant with `let` means it will work with or without
✅ Developers
???
- Ensure app check works with or without recapcha token.
---
=> Amend appCheck logic

src/views/Exercise/Applications/Application.vue, src/views/Exercise/Applications/List.vue, src/views/InformationReview/QualificationsAndMembershipsSummary.vue
[An issue was raised regarding General Medical Council membership not showing correctly](https://judicial-appointments.slack.com/archives/C033NNNU5TP/p1651751762050909).
After a review of the `QualificationsAndMembership.vue` code, it appears i had missed the display and edit of certain memberships, GMC being one. 
This PR should fix to include these memberships and allow their editing by admins as per application edits.
✅ Developers
✅ UTG
- Find an application which declares membership to GMC or other membership.
- Observe correct display and edit of given information.
🟠 Medium risk 
See above link to slack.
---
=> membership display and edit

src/components/ModalViews/IndependentAssessmentsRequests.vue, src/views/Exercise/Tasks/IndependentAssessments.vue
---
Add a popup confirmation modal before sending independent assessments request.
✅ Developers
✅ UTG
Preview URL: https://jac-admin-develop--pr1648-feature-1647-confirm-bht4uxg6.web.app
1. Go to an exercise.
2. Go to `Independent Assessments` on `Tasks`.
3. Check the popup confirmation after clicking the following buttons:
- Send to all
- Send reminders
- Test Request
- Request
- Reminder
Demo:
https://user-images.githubusercontent.com/79906532/174618016-7a057a6a-3c18-4646-9876-6335b697af5b.mov
Screenshots:
1. Send to all
2. Send reminders
3. Test Request
4. Request
5. Reminder
---
_can be OFF, …
=> #1647 Add confirmation before sending independent assessments request

src/views/Exercises.vue
---
Add a search to enable a user to search for an exercise by name.
Note: Since Firestore doesn't support fuzzy search, the search value must be exactly same as the exercise name. 
Related issue: [ #65 Bugfix. Search clear button doesn't update value](https://github.com/jac-uk/jac-kit/pull/65)
✅ Developers
✅ UTG
Preview URL: https://jac-admin-develop--pr1650-feature-1649-search-i301sem8.web.app
1. Go to exercises.
2. Check search functionality.
Demo:
https://user-images.githubusercontent.com/79906532/174787921-0caaca6a-596c-42c2-a8bf-7dc20e5ae7be.mov
---
=> #1649 Search functionality for exercises

src/views/Exercise/Reports/Handover.vue
Fix the table loading state on handover report.
Note: when Handover.vue is created, it will bind to firestore document and get the report data before Table component is rendered. And when Table component is mounted, it will set loading state to true. That's why the table already got data but the loading state is still showing. 
✅ Developers
✅ UTG
1. Go to Handover report of an exercise
2. Check the table is not stuck in loading state
Demo:
https://user-images.githubusercontent.com/79906532/181294424-f3b8a7ea-ec86-444c-93b8-81840f3b02fe.mov
---
=> #1693 Bugfix: handover report table is stuck in loading state

src/store/exercise/collection.js, src/views/Exercises.vue
✅ Developers
✅ UTG
1. Open exercises page
2. Check it will load all exercises as default
3. Check `Your exercises` is changed to `Favourite exercises`
Demo:
https://user-images.githubusercontent.com/79906532/180750932-af65bf77-ee9a-4ebb-a57a-cf79c55c65ad.mov
---
=> #1685 Exercise list default screen

src/components/PanelPacks/PanelPacks.vue, src/views/Exercise/Applications/List.vue, src/views/Exercise/Stages/HandoverList.vue, src/views/Exercise/Stages/RecommendedList.vue, src/views/Exercise/Stages/ReviewList.vue, src/views/Exercise/Stages/SelectedList.vue, src/views/Exercise/Stages/ShortlistedList.vue, src/views/Exercise/Tasks/CharacterChecks.vue, src/views/Exercise/Tasks/IndependentAssessments.vue
The Candidate Details screen is linked to from some places in the system but not others. Some Candidate names are a link to the profile and we would like to make all link to the profile and open in a separate tab.
Note: this issue is related to [Application link open in new tab #71](https://github.com/jac-uk/jac-kit/pull/71).
✅ Developers
✅ UTG
Click on a candidate name link on `Character checks`, `Selection day`, `Stages`, `Applications` and see if it opens candidate details in a new tab
Demo:
https://user-images.githubusercontent.com/79906532/180766632-9066f5bb-6ffb-49aa-af92-2a4ecbe570f3.mov
---
=> #1686 Candidate details

src/components/PanelPacks/PanelPacks.vue
When click the panel name link it just loops back around to the same screen. The current solution is to remove the `target="_blank"` on the anchor link.
Note: when `PanelsView` component is created, it will check the selected panel state and redirect to the previous page if it's empty. That's why the link will loop back when we open it in a new tab.
✅ Developers
✅ UTG
Go to Task `Sift` or `Selection day` page and check if panel name link works.
Demo:
https://user-images.githubusercontent.com/79906532/182655577-293138ed-39db-47f1-82e2-c24a9c6e0243.mov
---
=> Hotfix: #1705 Panel name link not working

src/filters.js, src/views/Candidates/CandidatesList.vue, src/views/Exercise/Applications.vue, src/views/Exercise/Details/Overview.vue, src/views/Exercise/Reports/Custom.vue, src/views/Exercise/Reports/Diversity.vue, src/views/Exercise/Reports/Handover.vue, src/views/Exercise/Reports/Outreach.vue, src/views/Exercise/Reports/ReasonableAdjustments.vue, src/views/Exercise/Stages.vue, src/views/Exercise/Tasks/IndependentAssessments.vue, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/View.vue, src/views/Exercises.vue, tests/unit/filters.spec.js
Add commas to numbers so they are easier to read, e.g., `1000 -> 1,000`.
This will be anywhere we display numbers on the platform:
✅ Developers
✅ UTG
Go to the admin platform and check number display
Demo:
https://user-images.githubusercontent.com/79906532/181252919-f982bec6-97c2-47dd-b256-17bdf9f6f5b6.mov
---
=> #1694 Add commas to numbers

src/views/InformationReview/QualificationsAndMembershipsSummary.vue
A number of fixes have been applied to stop errors in the memberships section.
The production data and develop data may have some differences, however this fix is working for, at least some production data.
We should consider, maybe, reviewing the schema before merging this code.
✅ Developers
✅ UTG
Check that under any given application in a given exercise, memberships/qualifications show where relevant. 
---
=> ADDITIONAL MEMBERSHIPS PR

src/views/Exercise/Details/Downloads/Edit.vue, src/views/Exercise/Details/Downloads/View.vue
Add the "Statutory Consultation Guidance Letter" to the exercise downloads page.
✅ Developers
✅ UTG
Go to exercise downloads of an exercise and upload "Statutory Consultation Guidance Letter".
Demo:
https://user-images.githubusercontent.com/79906532/197239808-27f51ee9-2a4f-4ee7-9eec-2824e1179884.mov
---
=> #1751 Stat Con Letter Guidance

src/helpersTMP/Timeline/exerciseTimeline.js, src/helpersTMP/date.js
Update the wording of "Return date for independent assessments" in the timeline. E.g. `1 pm on 1 October 2022`.
✅ Developers
✅ UTG
Go to the timeline of an exercise and check the date format of "Return date for independent assessments".
Screenshot:
---
=> #165 Change of wording for IAs

src/views/Candidates/Actions.vue, src/views/Candidates/CandidatesView.vue
Allow a user to access `Candidates - Actions` and change an email address.
The right to do this should then be added to these User Roles:
- Operations Team Member
- Operations Senior Manager
- Digital Super User
Note: this changes will remove hard coded permission control in "Candidates - Actions" page.
✅ Developers
✅ UTG
1. Go to a candidate page.
2. Check if the current user which the user role is one of above roles can amend the candidate's email address.
User role: Operations Senior Manager
User role: Other JAC Staff
- Permissions have been added / updated. Details: `canUpdateCandidates`
---
=> #1770 Admin Amending Email Addresses for Candidates

src/views/Exercise/Applications/Application.vue
Allow admins to amend applications by removing hard-coded email permission control. The following user roles will be able to perform the amending action:
- Operations Team Member
- Operations Senior Manager
- Digital Super User
✅ Developers
✅ UTG
1. Go to an application of an exercise.
2. Check if the current user which the user role is one of above roles can amend the application.
User role: Operations Senior Manager
https://user-images.githubusercontent.com/79906532/198006819-28b4f954-420d-4ac3-8e5e-585098c33e5f.mov
User role: Other JAC Staff
https://user-images.githubusercontent.com/79906532/198006848-25ddab23-b0b7-41b1-be02-8fc399e6df94.mov
---
=> #1762 Admin Amending Application Data

src/permissions.js, src/views/Exercise/Applications/List.vue
Send a reminder email to all applications in Draft.
The application reminder template:
Note: this PR is related to [[digital-platform] Send application submission reminders](https://github.com/jac-uk/digital-platform/pull/789).
✅ Developers
✅ UTG
1. Go to the draft application list of an exercise.
2. Click "Send reminders" to send reminder email.
3. Go the Notification page and check if the "Application Submission Reminder" is in the queue.
Demo:
https://user-images.githubusercontent.com/79906532/201130910-d14a7fc2-ae3b-4e91-84e3-af740a8e8b55.mov
- `canSendApplicationReminders `
---
=> #1764 Application Submission Reminder

.env.test, package-lock.json, package.json, src/App.vue, src/firebase.js, src/helpers/authUsers.js, src/main.js, src/store/auth.js, src/store/qualifyingTest/qualifyingTestResponses.js, src/views/Exercise/Tasks/QualifyingTests/QualifyingTest/Response/View.vue, src/views/SignIn.vue, tests/unit/store/qualifyingTest/qualifyingTestResponses.spec.js
Changes our code base to enable the use of local emulator suite.
This will enable faster local development and will be useful for user testing
See related work on [digital-platform#795](https://github.com/jac-uk/digital-platform/pull/795)
Note: here we have also included the following fixes:
- Bugfix: use correct firebase instances
- Bugfix: fix unit tests and simplify mocks
✅ Developers
Amend your `env.develop.local` file to include the following line:
```
VUE_APP_FIREBASE_USE_EMULATORS=true
```
When running `npm run serve` a value of `true` for the above line will mean the Admin UI connects to the local emulator suite. A value of `false` will mean the Admin UI connects to the `develop` environment.
Include screen …
=> digital-platform#794 Use local emulator suite

src/views/InformationReview/QualificationsAndMembershipsSummary.vue
When an admin user amends a candidate's qualifications on the admin site, it will not show correctly on the apply site due to the data structure changing from array to object in Firestore. This PR will fix this problem.
✅ Developers
✅ UTG
Scenario 1
1. [admin] Find an application and add new qualifications
2. [apply] Go to the qualification section and check if the information shows correctly.
Scenario 2
1. [apply] Go to the qualification section and fill in some qualifications
2. [admin] Go to the application and check if the information shows correctly.
3. [admin] Amend the qualifications (e.g. location, date)
4. [apply] Go to the qualification section and check if the information has been amended correctly.
🟠 Medium risk - this does change code that is shared with other …
=> #1834 Bugfix: show no qualifications after amend

src/views/Exercise/Details/Downloads/View.vue
'Other Downloads' were missing from the additional content section of the vacancy details page. 
I have re-added them so that uploaded files can be accessed by candidates. 
This PR makes these downloads more visible on the admin platform
[Partnering apply side PR here](https://github.com/jac-uk/apply/pull/949)
✅ Developers
✅ UTG
- Upload a document (or multiple) under 'other downloads' [admin side]
- Check the file appears, named correctly and downloadable on the apply side 
APPLY >>>
---
=> Other Downloads

src/router.js, src/views/Exercise/Reports.vue, src/views/Exercise/Reports/StatutoryConsultation.vue
1. Add statutory consultation under the reports section.
2. Add a button to export the statutory consultation report.
Sample excel file: https://app.zenhub.com/files/201485031/3d829019-e50f-4daa-9a53-f70597b28eb6/download
Note: this PR is related to [digital-platform: Generate statutory consultation report #823](https://github.com/jac-uk/digital-platform/pull/823).
✅ Developers
✅ UTG
1. Find an exercise and go to `Statutory Consultation` under the reports section.
2. Click `Refresh` and `Export data` to download the excel file. 
Demo:
https://user-images.githubusercontent.com/79906532/212359326-8a4f7961-1cb7-4abf-86c3-5fb7eb4e995c.mov …
=> #1846 Statutory consultation report 

package-lock.json, package.json
Fix the `Previous` and `Next` buttons do not show when using the default pagination.
✅ Developers
✅ UTG
[Default pagination]
1. Go to the exercises page (with over 50 exercises) and check if `Previous` and `Next` buttons work properly.
2. Go to the selected list under `Stages` section (with over 50 applications) and check if `Previous` and `Next` buttons work properly.
[Letter pagination]
1. Go to `Applications` tab of an exercise and check if there are no `Previous` and `Next` buttons.
---
=> Bugfix: previous and next buttons not show in default pagination

package-lock.json, package.json
Upgrade `jac-kit` to `0.1.13` to fix the table pagination with the optional page size.
Note: this PR is related to [jac-kit: #90 Bugfix: Page size should be an optional prop](https://github.com/jac-uk/jac-kit/pull/91)
Before:
After:
✅ Developers
1. Go to the `Notes` tab under a candidate and check if the `Next` button does not show.
2. Go to the `Qualifying Test Report` tab under the Reports section of an exercise and check if the `Next` button does not show.
---
=> Bugfix: table pagination with optional page size

src/components/Previews/DetailPreview.vue, src/components/Previews/ListingPreview.vue, src/filters.js, src/helpersTMP/Timeline/createTimeline.js, src/router.js, src/views/Candidates/TargetedOutreachReport.vue, src/views/Exercise/Details/Summary/Edit.vue, src/views/Exercise/Details/Summary/View.vue, src/views/Exercise/Details/Vacancy/Edit.vue, src/views/Exercise/Details/Vacancy/View.vue, src/views/Exercise/exerciseMixin.js
Initial work for creating and implementing components to preview apply side exercise 'listing' and 'detail' sections before taking an exercise live.
✅ Developers
✅ UTG
Try a variety of exercise states, listing types, legal, non-legal and other configurations and check listing show successfully and correctly under the website listing section of an exercise.
🟠 Medium risk - this work contains new components which need thorough testing.
---
=> preview 'listing' and 'detail'

src/views/Exercise/Reports/Diversity.vue, src/views/Exercise/Reports/QualifyingTestReports/QualifyingTestReport/View.vue, src/views/Exercise/Reports/QualifyingTestReports/QualifyingTestReport/ViewScore.vue
Change the term `BAME` and `BME` to `Ethnic minorities` according to the latest government guidance.
✅ Developers
✅ UTG
Diversity report:
1. Go to the `Diversity` under the Reports section of an exercise and check if the term `BAME` is changed to `Ethnic minorities`.
2. Click `Export all data` and then open the excel file. Check if the term `ethnicity:bame` is changed to `ethnicity:ethnic minorities`.
Qualifying Test report:
1. Go to the `Qualifying Test Report` under the Reports section of an exercise and check if the term `BAME` is changed to `Ethnic minorities`.
3. Click `Download data` and then open the excel file. Check if the term `BAME` is changed to `Ethnic minorities`.
Screenshot of the diversity report:
* Before: …
=> #772 Ethnicity language changes

src/views/Candidates/Actions.vue
Update the error message when amending the candidate's login email address.
If the new email is already on the platform, the error message will be: 
```
An account already exists with this email address. To update the candidate login email address with this email address the other account will need to be removed. Please contact the Digital Team for assistance.
```
Note: this PR is related to [digital-platform: 1839 Error message when update candidate email](https://github.com/jac-uk/digital-platform/pull/832).
✅ Developers
✅ UTG
1. Find an email address already on the platform.
2. Go to a candidate page and update the candidate login email address with the email.
3. Check if the error message shows correctly.
Demo: …
=> #1839 Bugfix: Update candidate login email

src/helpersTMP/Timeline/exerciseTimeline.js
On admin side view of exercise timeline, selection process outcome was shown to the day, this has been formatted to match input: showing month and year rather than day, month and year.
✅ Developers
✅ UTG
- Go to timeline page on any exercise
- view the selection process outcome date 
- ensure it shows month and year, but not day
---
=> selection process outcome date format

src/views/Exercise/Tasks/Task/New/default.vue, src/views/Exercise/Tasks/Task/TestActivated.vue, src/views/Exercise/Tasks/Task/TestInitialised.vue
Enable QTs to be set up while an exercise is still open or processing applications has not yet started.
Closes #1911 
✅ Developers
Locate an exercise which is open, has some applications, will be running a QT and is not yet closed for applications.
Navigate to Tasks and select Critical Analysis or Situational Judgement test.
**Before this change/fix**
It was not possible to 'Continue' with the task and prepare the live QT
**After this change/fix**
The user must confirm key details of the task and can then 'Continue' with the task and prepare the live QT
---
=> #1911 Enable QTs to be set up while exercise is still open

src/filters.js, src/views/Exercise/Reports/ReasonableAdjustments.vue
Closes #1901 
✅ Developers
✅ UTG
Go to Reasonable Adjustments Report and check if the above items work.
Demo:
https://user-images.githubusercontent.com/79906532/220909375-fcb027ea-6a26-4700-b94e-0f4d2d0c450e.mov
---
=> #1901 Reasonable Adjustments - Additions to ticket 1842

src/views/Candidates/Actions.vue
HTTP Response was being shown on the page, `currentEmailAddress` was being set as `response.data` missing a `.email` 
✅ Developers
- Update an email address under candidates > actions 
- take note of the email address (so it can be changed back)
- Make a valid change (.ie `.digital` > `.com`)
- Ensure confirmation message and response are correctly formatted
---
=> Format confirmation message

src/views/Exercise/Details/Summary/Edit.vue, src/views/Exercise/Details/Summary/View.vue, src/views/Exercise/Details/Vacancy/Edit.vue, src/views/Exercise/Details/Vacancy/View.vue
Wording changes.
Occurrences of;
'Role Summary' >>> 'Brief Overview'
'About the role' >>> 'Full Details'
Variable names still `roleSummary` and `aboutTheRole`
✅ Developers
✅ UTG
Check changes are present under exercises > vacancy information.
>>>
---
=> wording changes

package-lock.json, src/views/InformationReview/QualificationsAndMembershipsSummary.vue
Custom 'Other' qualifications from admin were not pulling thru and showing on apply.
They were equally not showing upon admin edit of applications either.
✅ Developers
✅ UTG
- Using a legal exercise on admin with a custom "other" qualification
- Edit an applications qualifications and ensure this custom qualification appears as an enterable option
---
=> include other qualfications

src/views/Exercise/Details/Timeline/Edit.vue
Removes the 'View key dates...' link from Exercise Timeline as it doesn't go anywhere!
✅ Developers
Navigate to Exercise > Timeline > Edit and see that the link and associated text has been removed
---
=> Bugfix: Remove broken link to 'View key dates of all exercises'

src/views/Exercise/Details/Overview.vue
Fixes recent problems with the 'Process (late) applications' button.
Closes #1942 
✅ Developers
✅ UTG
Visit an exercise which has applications, but processing hasn't been started yet.
Press the 'Process late applications' button. Observe that:
- There are no on screen errors
- The Stages & Status menu appears and applications are available in Review stage
---
=> #1942 Bugfix: Process (late) applications button

src/views/Exercise/Details/Summary/View.vue, src/views/InformationReview/AssessorsSummary.vue
On the website list page the 'Publish on website' button was always disabled. This PR fixes that so that the button will be enabled (providing the exercise has completed data for 'Website listing').
Closes #1953 
✅ Developers
✅ UTG
View an exercise via the preview URL and https://admin-develop/judicialappointments.digital so that you can compare and see the fix.
Navigate to Website listing
See that the 'Publish on website' button works (providing the exercise has completed the Website Listing data).
Previously the button was always disabled.
---
_can be OFF, DEVELOP or …
=> #1953 Bugfix: 'Publish on website' button is always disabled

src/views/Exercise/Applications/List.vue, src/views/InformationReview/AssessorsSummary.vue
Closes #1947 
✅ Developers
✅ UTG
Go to the application list of an exercise and check if the `Applied in Welsh` shows correctly.
Screengrab:
---
=> #1947 Welsh application - applied list

src/filters.js, src/views/Exercise/Tasks/Task/Finalised.vue, src/views/Exercise/Tasks/Task/Finalised/View.vue, src/views/InformationReview/AssessorsSummary.vue
A couple of changes following feedback from a SET:
Part of #1955
✅ Developers
✅ UTG
For an exercise which has completed CAT and SJT:
- Check that the side menu and page title now says 'QT merit list' where previously it said 'CA + SJ Scoring'
- Check that overriding a candidate pass/fail status correctly displays on both the 'individual score' view and the 'list of all scores'
---
=> #1955 QT Merit List feedback

src/App.vue
Add check that user can read messages before including the Messages component and fetching the messages
Closes #1962 
✅ Developers
✅ UTG
Note the following:
- permissions can be set via the 'Users' section of the site.
- a message is generated for a late application request
- below, for clarity, we'll refer to the two users as User A and User B
- no errors should appear in the chrome/firefox developer console
Go into the Users section and remove the 'read message' permission for a user who receives messages for late application requests (User A)
Login as a user who can create a late application request (User B) and create one, then logout.
Login as User A and ensure that they don't see a message for late application requests.
Then add the 'read message' permission for User …
=> Check can read msgs before loading msgs

src/store/events.js
the `events.js` store was seemingly copied over from the `notifications.js` store and as a consequence was using some incorrect variables which weren't defined.
This fix should mean pagination on the `events`, `warnings`, and `errors` lists work.
✅ Developers
use pagination on the events list.
next,prev - next, next, prev, prev - etc
---
=> Fix events list

src/views/InformationReview/ExperienceSummary.vue
The changes to the experience section for applicants of 00164 are reflected on admin.
see #1974 
✅ Developers
Apply for one of the following vacancies and see that the application review includes the changes in [jac-uk/admin#1974](https://github.com/jac-uk/admin/issues/1974):
Develop: JAC00507
Staging: JAC00660
Production: JAC00164
---
=> Medical Members questions for 00164

src/main.js
Force admin users to sign out and then sign in again as the current user token will be revoked by the cloud function `adminSyncUserRolePermissions` if the permissions have been changed.
✅ Developers
1. Change the user role or permission of an user.
2. Refresh the page and check if it redirects to the sign in page.
Demo:
https://github.com/jac-uk/admin/assets/79906532/2c880244-63ee-4540-9a12-fe1498480eb2
---
=> Bugfix: user permissions not updated

package-lock.json, package.json
Use latest version of jac-kit which trims whitespace from inputs.
Closes jac-uk/jac-kit#107
✅ Developers
✅ UTG
Add whitespace at beginning or end of any text or textarea input field. When the data is re-displayed you should see no whitespace at the beginning nor end of the data. eg update the candidate first name with leading or trailing whitespace and ensure it doesnt appear when re-displayed.
- 
---
=> JAC-KIT#107 Use latest version of jac-kit which trims whitespace from inputs

src/views/Exercise/Tasks/CharacterChecks.vue
In this PR [1840/remove HMRC check](https://github.com/jac-uk/admin/pull/1881) we removed HMRC checks and `CharacterChecksEdit.vue` component. Originally, it will create a field `characterChecks.HRMC` in the exercise document after `Will HMRC checks be required?` question is answered. Since we have removed `CharacterChecksEdit.vue` component, the field will not be created, which causes the contact and due date of character checks will not display. This PR will fix this problem.
✅ Developers
Go to Character checks and check if the contact and due date display correctly.
--- …
=> Bugfix: character checks dates not populated

src/components/RepeatableFields/AssignedCommissioner.vue, src/components/RepeatableFields/SelectionExerciseManager.vue, src/components/RepeatableFields/SelectionExerciseOfficer.vue, src/components/RepeatableFields/SeniorSelectionExerciseManager.vue
Closes #1998 
✅ Developers
✅ UTG
1. Go to Contacts of an exercise and edit the following fields:
- Senior selection exercise manager
- Selection exercise manager
- Selection exercise officer
- Assigned commissioner
2. Check if the hint `An email address is required.` appears underneath the text box
Screenshot:
---
=> #1998 Exercise Contacts - Not Clear Email Address is needed

src/views/Exercise/Details/Vacancy/Edit.vue, src/views/Exercise/Details/Vacancy/View.vue
At the moment users translate the vacancy information (brief overview, full details) into Welsh and either dump it into a word doc as a download or put it at the end of the English version. In this PR an input box will be added to allow users to store the Welsh version of vacancy information.
Closes #1976 
✅ Developers
✅ UTG
1. Go to an exercise with Welsh posts.
2. Go to Vacancy information and check if you can amend `Brief Overview (Welsh)` and `Full Details (Welsh)`.
Demo:
https://github.com/jac-uk/admin/assets/79906532/dec05b58-8ac2-4123-8eef-89e8b307f899
---
=> #1976 Vacancy details in welsh

src/views/Candidates/CandidatesView.vue, src/views/Candidates/UpdateLoginEmail.vue
Renamed the 'actions.vue' and accompanying labelling and imports.
✅ Developers
✅ UTG
- Go to Candidates > [any candidate]
- Look for the Log in Email tab
- Check the link works labelling is correct
---
=> rename to update email address

src/components/ModalViews/OverrideExercise.vue, src/store/exercise/collection.js, src/store/exercise/document.js, src/views/CreateExercise.vue, src/views/Exercise.vue
Add a dropdown to select which draft exercise will be overridden.
Closes #1967 
✅ Developers
✅ UTG
1. Find an exercise and hit the `Copy to clipboard` button.
2. Go to `Create Exercise` page.
3. Hit the `Override an exercise` button and select a target draft exercise. Only draft exercises will list in the dropdown.
4. Hit the `Override` button and check if the data is copied correctly.
Demo:
https://user-images.githubusercontent.com/79906532/233940590-3c543838-c558-42f4-961e-49fbb8619128.mov
---
=> #1967 Exercise copying improvements

src/store/panels.js
Fix the issue that candidates do not load properly since we moved it from Tasks to Reports.
✅ Developers
✅ UTG
Go to Sift, Selection under Reports and check if candidates show properly. 
---
=> Hotfix: panel candidates not show

package-lock.json, package.json, src/components/ModalViews/UploadFiles.vue, src/views/InformationReview/QualificationsAndMembershipsSummary.vue
Currently, when a candidate states "No" to completing pupillage in their application they will need to upload an exemption and/or practicing certificate. These documents should also be made available on admin, so admins can see and manage this information.
Added the ability to view and replace the files uploaded in association with no pupilage.
This PR is linked to the associated admin changes in the following PR: https://github.com/jac-uk/apply/pull/1022
Closes #2029 
✅ Developers
✅ UTG
Apply for a vacancy and when you get to the Relevant Qualifications do the following:
- Set the qualification to 'Barrister'
- Set "No" to completing pupillage
- FIll in the other inputs
- When you get to the bottom of the form only upload a single file for 'Exemption Certificate'
- Press …
=> #2029 Barrister - Pupilage Exemption Manage Upload

.github/workflows/manual-deploy.yml, .github/workflows/on-merge.yml, .github/workflows/on-pull-request.yml, .github/workflows/on-release.yml
Urgently commented out 'npm audit --omti=dev' in github actions as blocking release whilst there are high vulnerability errors.
In future we will need a process for dealing with this.
See:
https://github.com/advisories/GHSA-h755-8qp9-cq85
✅ Developers
✅ UTG
---
=> Remove NPM Audit Checks

package-lock.json, package.json, src/main.js, src/views/Exercise/Details/Summary/Edit.vue, src/views/Exercise/Details/Vacancy/Edit.vue
Removed ck editor refs from admin as they belong in the jac-kit and fixed issues with rich text editor input text.
✅ Developers
✅ UTG
Ensure the rich text editor works ok.
- Open a draft exercise
- Select 'Website Listing' from the side navigation panel
- Select the 'Update website listing' link from the right hand side
- Scroll down to the 'Brief Overview' and edit the text
- Scroll to the bottom of the page and press the 'Save And Continue' button
- Check that the change has been saved in the 'Brief Overview' section
---
=> Fix Rich Text Editor

.github/workflows/manual-deploy.yml, .github/workflows/on-merge.yml
Removed the command to run the tests from the manual deployment and merge github workflows. This is until we have tests running with vite.
---
=> Prevent running of tests when github runs the merge and manual deployment workflows

src/views/Candidates/TargetedOutreachReport.vue, src/views/Exercise/Applications/Application.vue
Fixes application view so it shows the status correctly. Previously 'Withdrawn' applications were displaying as 'Draft'
Closes #2039 
Also includes a lint fix
✅ Developers
✅ UTG
Go to application view for draft, applied and withdrawn applications.
Check that application view displays correctly for each application.
In particular for withdrawn application check that status says 'Withdrawn' rather than 'Draft'
---
=> #2039 Bugfix: Application View should show withdrawn status

src/helpers/exerciseHelper.js, src/store/exercise/document.js
When an exercise has been unlocked for editing the vacancy should not be updated.
To achieve this I did the following:
Prevent exercise _approval from being reset when approval is rejected/requested so that it persists and we can use it to check if the exercise was previously approved.
Also prevent published and _approval from being reset when an exercise is unlocked.
(In exercise helper isApprovalRejected should also include the 'ready' state - this is a bugfix!)
THIS TICKET RELIES ON CHANGES IN THE DIGITAL PLATFORM PR: https://github.com/jac-uk/digital-platform/pull/907
Closes #2065
✅ Developers
✅ UTG
On Admin Site:
- Create a new exercise
- Get the exercise approved and published
- Unlock the exercise
- Modify the exercise title
On Apply
- Check that the exercise title …
=> #2065 Editing Live Exercises

src/components/RepeatableFields/AssignedCommissioner.vue
Closes #2092 
✅ Developers
✅ UTG
Sample exercise: https://jac-admin-develop--pr2093-feature-2092-exercis-5ffew8rm.web.app/exercise/FzIIFtYhcv0wVXGfDvks/details/overview
1. Go to "Contacts" of an exercise and click "Update exercise contacts" button.
2. Go to "Assigned commissioner" field and check if the commissioner's email addresses appear in the dropdown list.
3. Edit "Assigned commissioner" and click "Save and continue" button.
4. Check if the selected email address appears correctly.
Demo:
https://github.com/jac-uk/admin/assets/79906532/fd5fcc5e-75a4-4944-8d88-770ed103a151
--- …
=> Feature/2092 Exercise contacts - Assigned commissioner field

src/views/Exercise/Tasks/Task/Data/Initialised.vue, src/views/Exercise/Tasks/Task/Finalised/List.vue, src/views/Exercise/Tasks/Task/Finalised/View.vue
Some exercises are showing white screens, here we are fixing that!
Example:
Error message:
✅ Developers
Here's an exercise that currently has a white screen:
https://admin.judicialappointments.digital/exercise/BpEL3HgHEyHCvDMI5E9s/tasks/qualifyingTest/finalised
Check the following preview url to see that the page has been fixed:
https://jac-apply-admin-production--pr2112-bugfix-exercise-tas-87qzwr51.web.app/exercise/BpEL3HgHEyHCvDMI5E9s/tasks/qualifyingTest/finalised
---
=> Bugfix: exercise tasks should use $filters

src/views/InformationReview/EqualityAndDiversityInformationSummary.vue
Removed 'gender-neutral' and 'other' from diversity summary so that admin users no longer have it as an option.
Closes #2125 
✅ Developers
✅ UTG
**Test 1**
- Go to the following test for a user who has selected 'gender-neutral'.
See: https://admin-develop.judicialappointments.digital/exercise/4xP8RY7GeoaS1yKqYJLw/applications/applied/application/0GEfgpjwxEH679YTK2we
- Ensure the gender is displayed as: Gender neutral
- Click the 'Edit' button at the top of the page.
- Ensure the gender is still displayed as: Gender neutral
- Ensure when you click the gender dropdown neither 'gender neutral' nor 'other' appear
**Test 2**
- Go to the following test for a user who has selected 'gender-other'.
See: https://admin-develop.judicialappointments.digital/exercise/5r40soW2fFmv50UEmkxP …
=> #2125 Diversity Monitoring Report

src/views/Exercise/Applications/List.vue
Fixes a bug / misconfiguration where the applications list was defaulting to A - Z paging. This is particularly confusing if there are only a few applications as it looks like there are no applications (as the list defaults to only show applications with surname beginning A)
We now default to showing all records, showing 50 at a time and if there are 500 or more applications then we default to A-Z paging.
Closes #2130
✅ Developers
✅ UTG
From the Exercises list choose an exercise with more than 500 applications - [example](https://jac-admin-develop--pr2131-bugfix-2130-u23d7fjh.web.app/exercise/4xP8RY7GeoaS1yKqYJLw/applications/applied)
- Check that the Applications lists use A-Z paging
From the Exercises list choose an exercise with only a few (less than 500) applications - …
=> #2130 Bugfix: Application list should default to regular paging

src/views/Exercise/Applications/List.vue
Following feedback from live SETs we have included the Export Contacts button on the Draft Applications list.
Closes #2129
✅ Developers
✅ UTG
For an exercise with draft applications - [example](https://jac-admin-develop--pr2132-bugfix-2129-asj2dmoc.web.app/exercise/2M7yxJySfXpINFwvhnnW/applications/draft) - navigate to Applications > Draft
- Check that there is an Export Contacts button
- Press the button and check that the download works and contains the expected content
_Note: you may need to click the `[ 1 2 3 4 ]` button in order to view applications on screen_
---
=> #2129 Bugfix: Export contacts on Draft Applications

package-lock.json, package.json
This fix relies on the jac-kit v3.0.37.
The problem was that the scrollIntoView was somehow causing the page content to shift to the left. It's difficult to say exactly why.
The fix involved changing the element being scrolled into view.
Closes #2120 
✅ Developers
✅ UTG
- Go to the following page: https://jac-admin-develop--pr2152-hotfix-hotfix-2120-m-6ctuhch9.web.app/exercise/q3r80nVrmVFhB2ML03qq/details/timeline/edit
- Remove one of the dates
- Scroll to the bottom of the page and press the 'Save and Continue' button
The page should scroll back up to display the error summary and the left side of the page should NOT have the display bug as shown in the image below.
---
=> #2120 Exercise page alignment is breaking after on-screen error messages are displayed

src/components/PanelPacks/PanelPacks.vue
Fixed search for panel packs.
Closes #2163 
✅ Developers
✅ UTG
Go to the panel packs search. Ensure you can search by the following fields:
- candidate national insurance number
- candidate email
- candidate full name
- application reference number
So, for example you can use this test link: https://jac-admin-develop--pr2164-hotfix-2163-search-n-ue7wk0py.web.app/exercise/mgiIdf4ccm3z7Q3jsZKb/reports/selection#candidates
And one of the candidates has the following details:
Fullname: Yesim Sharp
NI: (has the following characters in it: 359)
Email: (has the user's name in it)
Application ID: JAC00545-kun0002
See video below:
https://github.com/jac-uk/admin/assets/115651787/3aad84e7-be8a-4e3a-93d5-c8b8972938e5
--- …
=> #2163 Search Not Working For Panel Packs

src/views/Exercise/Dashboard/OverviewPanels/TotalApplications.vue, src/views/Exercises.vue
Amendments to the display of application counts
Closes #2147 
✅ Developers
✅ UTG
Example exercise: JAC00666 on Develop
Please check the following changes:
**On the Exercises list**
- the number displaying under Applications Count should reflect the number of completed applications
- the column title should be amended to 'Submitted Applications'
**On the Exercise Dashboard**
- show application counts for Draft, Applied and Withdrawn
---
=> #2147 Application counts

src/views/Exercise/Reports/PanelsView.vue
Closes #2170 
Update post-qualification experience in the following downloads:
- Panel packs
Note: This work is related to [digital-platform: Feature/Admin#2170 Update Downloads in line with Application Form updates](https://github.com/jac-uk/digital-platform/pull/968).
✅ Developers
✅ UTG
Example exercise: https://jac-admin-develop--pr2220-feature-2170-update-151wfhz5.web.app/exercise/6LHFYxCon9P6u96QLvwe/reports/selection
1. Go to a panel of an exercise.
2. Click "Export to google drive" and wait until the status changes to "created".
3. Go to Google Drive (https://drive.google.com/drive/folders/1dOhgREFvqG6gk20-dwRj1y4jHWjCfJrB).
4. Go to the "application-0002 Jac JAC00683-vay0002" folder in the latest "00683 Test" folder.
5. Open the doc "Application Data".
6. Check if …
=> #2170 Update Downloads in line with Application Form updates

src/store/candidateForms/document.js, src/views/Exercise/Tasks/Task/CandidateForm/Configure.vue, src/views/Exercise/Tasks/Task/CandidateForm/LocationDate.vue
If the Pre Selection Day Questionnaire has been configured to ask for Candidate Availability we now enable dates and locations to be configured. It is these dates and locations which will be presented to the candidate in order to check their availability.
Closes #2226
✅ Developers
✅ UTG
Example exercise: JAC00684 Exercise with Pre Selection Day Questionnaire
- Configure the Pre Selection Day Questionnaire to request Candidate Availability.
- Notice that an additional question appears requesting "Which dates would you like to check for candidate availability?"
- Try to add, edit and remove dates
- Check that at least one date must be configured before you're able to 'Save and continue' successfully
Example set of dates & locations
🟢 No risk - this is a self-contained piece …
=> #2226 Configure Candidate Availability

src/App.vue, src/store/exercise/document.js, src/views/Exercise.vue, src/views/Exercise/Details/Overview/ApprovalProcess.vue, src/views/Exercise/Details/Summary/View.vue, src/views/Exercises.vue
Disallow archiving until exercise is unpublished from website.
Here I'm actually un-publishing at the same time as archiving!
Closes #2159 
✅ Developers
✅ UTG
- Goto the following url (it may prompt you to login first): https://jac-admin-develop--pr2215-feature-2159-disallo-5vj3g8aa.web.app/exercise/VG7qW7osx4eWUSIxFcT5/details/overview
- find an exercise that has been published and ensure the vacancy appears in the apply site
- archive the exercise and ensure a message appears saying 'This application is currently within the application window and is not published on the website' AND it no longer appears as a vacancy 
- unarchive the exercise and check that a message appears saying 'This exercise has been approved. Now you can publish it on the website' AND ensure it …
=> #2159 Disallow archiving until exercise unpublished from website

src/components/ModalViews/IndependentAssessmentsRequests.vue
Closes #2173
Note: This PR needs changes on Digital Platform [#2173 Admin Independent Assessments](https://github.com/jac-uk/digital-platform/pull/981)
✅ Developers
✅ UTG
1. Go to preview link: https://jac-admin-develop--pr2244-feature-2173-indepen-wskxjm6y.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/tasks/all/independent-assessments#notrequested
2. Go to "Not Requested" tab
- Select one assessment
- Click "Send Request" button
- It should appear a pop-up with related information (changed to X assessor(s)): 
3. Go to "Requested" tab
- Select one assessment
- Click "Send reminders" button
- It should appear a pop-up with related information (changed to X assessor(s)): 
4. Go to preview link: https://jac-admin-develop--pr2244-feature-2173-indepen-wskxjm6y.web.app/exercise/ONqUjAzhD …
=> #2173 Independent Assessments

src/views/Exercises.vue
Closes #2161 
✅ Developers
✅ UTG
1. Go to Live Exercises page.
2. Check if the "Status" column (it will reflect the timeline stage) displays correctly.
Screehshot:
---
=> Feature/2161 Changing Live Exercises page to display exercise status and stage

src/components/RepeatableFields/SelectionExerciseManager.vue, src/components/RepeatableFields/SelectionExerciseOfficer.vue, src/components/RepeatableFields/SeniorSelectionExerciseManager.vue, src/store/users.js
Fixes #2261 
✅ Developers
Using the preview URL:
https://jac-admin-develop--pr2263-bugfix-2261-d69tpw4d.web.app/
- Go to the following exercise:
- JAC00693, Pre selection day test exercise 7
- Navigate to Exercise > Contacts > Update exercise contacts
- Check that the following dropdowns are populated:
- Senior selection exercise manager
- Selection exercise manager
- Selection exercise officers
- Observe that the dropdown options are only for active JAC staff
- Observe that the dropdown options include Name and email (e.g. `Jim Bob (jim.bob@judicialappointments.gov.uk)`)
- Observe that the dropdown options are ordered alphabetically
---
=> #2261 Bugfix: Staff user dropdowns are not populated in Contacts section

.github/workflows/manual-deploy.yml, .github/workflows/on-merge.yml, .github/workflows/on-pull-request.yml
test-ci command was commented out of the pull request workflow when the vue3 upgrade was happening. Here i'm putting it back in.
✅ Developers
Ensure the test-ci command runs when a pull request is made
=> Add test-ci command back into pull request github workflow

package-lock.json, package.json, src/views/Exercise/Reports/Handover.vue, vite.config.js
Closes #2225 
- Make the Judicial Experience field can be multi-line
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2269-fix-2225-update-hand-id9x8gal.web.app/exercise/6LHFYxCon9P6u96QLvwe/reports/handover
- Hit 'Refresh' button to generate report data
- Hit 'Export data' button to download the file
- Check the file, the Judicial Experience field should be multi-line
---
=> #2225 Update Handover report in line with application form improvements - Make Judicial Experience to be multi-line

src/store/users.js, src/views/Users/Users.vue
Closes #2272 
Note: Required the changes of Firestore indexes in [digital-platform: Feature/admin#2272 Users indexes](https://github.com/jac-uk/digital-platform/pull/994).
✅ Developers
Go to the user list under "User Management" and check if the role filter works properly.
---
=> Feature/2272 Add role filter to user list

src/helpers/exerciseHelper.js, src/views/Exercise/Applications/Application.vue, src/views/InformationReview/ResignationFromDWPSummary.vue
Closes #2276 
✅ Developers
Example application: https://jac-admin-develop--pr2277-feature-2276-candida-ed5kqmxt.web.app/exercise/09zuw8tcILdrH2DJZA2g/applications/draft/application/aYWsPP6QjSVD9mmhGYtR
1. Go to the application.
2. Check if "Resignation from the Department for Work and Pensions (DWP)" section appears.
3. Check if you are able to edit the answers under "Resignation from the Department for Work and Pensions (DWP)" section.
- apply site
- admin site
---
=> Feature/2276 Make candidate responses to bespoke question on Ex.187 visible

src/helpers/exerciseHelper.js
Closes #2246 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2286-fix-2246-disable-rel-ct8jo8or.web.app/exercise/aDxEqK36807d0Nhpugo3/details/application-content
- The `Relevant Qualifications` is not added to application process of non-legal exercise.
---
=> #2246 Disable Relevant Qualifications being added to application process for non-legal exercises

src/components/ModalViews/UploadFiles.vue
Closes #2283 
✅ Developers
✅ UTG
Example exercise: https://jac-admin-develop--pr2288-feature-2283-add-wor-4r8po8y6.web.app/exercise/qxj0UCVXoDGbdNuj4qRi/details/downloads
1. Go to "Exercise downloads" and click "update downloads".
2. Click the "Add" of "Candidate Assessment Form".
3. The pop-up of "Candidate Assessment Form" will appear and check if there is a guidance link "Preparing SA template for upload".
4. Check if you can access the file.
---
=> Feature/2283 Add MS Word guidance to Self-assessment Exercise Downloads

src/helpers/vuexfireJAC.js
Fixes a bug where our `vuexfireJAC` library was not handling `collection` queries correctly.
Closes #2312 
✅ Developers
Code review only
---
=> #2312 Enable vuexfire to handle collections

src/styles/main.scss
Replace use of background image with alternative css solution to ensure the down arrow appears on the button.
✅ Developers
✅ UTG
- Go to the following page: https://jac-admin-develop--pr2317-bugfix-ts-198-broken-t6klw0n5.web.app/exercise/mgiIdf4ccm3z7Q3jsZKb/applications/applied/application/ycyHRYDhsz4XIP87Y2YS
- Ensure the Action button has a downward facing arrow in it (see screenshot below)
---
=> Ticketing System #198 - BugFix MOJ Image Not Found As Not part Of Build

src/views/InformationReview/CommissionerConflictsSummary.vue
Added the optional chaining operator on the attribute and find method so that it works when no commissionerConflicts in additionalInfo in the application record.
Closes jac-uk/ticketing-system#194
✅ Developers
✅ UTG
**Test 1**
- Go to the following url: https://jac-admin-develop--pr2316-bugfix-ts-194-commis-zs8iqa2a.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/applied/application/LinokWzjBmo6uNykztEa
- Scroll to the bottom of the screen
- Ensure there are some commissioner conflicts set to 'no', see screenshot below:
**Test 2**
- Go to the following url: https://jac-admin-develop--pr2316-bugfix-ts-194-commis-zs8iqa2a.web.app/exercise/wdpALbyICL7ZxxN5AQt8/applications/applied/application/XJ9oRckhw2Kf0hQAHOpM
- Scroll to the bottom of the screen
- Ensure all of the …
=> Ticketing System #194 - BugFix Commissioner Conflicts Summary When No Commissioner Conflicts

src/views/Exercise/Reports/CharacterIssues.vue
For issue: https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/ticketing-system/199
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2336-bugfix-issue-199-cha-pj840g0x.web.app/exercise/aDxEqK36807d0Nhpugo3/reports/character-issues
- Change status and check the character issue table displays applications
---
=> Bugfix/TS 199 Character Issues Report No Data

src/App.vue, src/store.js
Ensure the user feedback link is not displayed on the staging environment (until the env is made compatible with staging).
✅ Developers
✅ UTG
Ensure the 'Report An Issue' button does not appear on any pages.
---
=> Disable user feedback link for staging

package-lock.json, package.json, src/views/InformationReview/EqualityAndDiversityInformationSummary.vue
Closes #2305 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2343-feat-2305-align-cand-4my1zlmx.web.app/exercise/b96p6e9GTAkVUhbggHom/applications/applied/application/KbaGWWL5C6oTiOHa64Sg
- Click `Edit` to enter editable mode
- Find  the `Ethnic group` section, click `change`, the `Roma`, `Arab` should appear  in the selection list
- Go to the preview link: https://jac-admin-develop--pr2343-feat-2305-align-cand-4my1zlmx.web.app/exercise/b96p6e9GTAkVUhbggHom/reports/diversity
- Click `Refresh` to generate diversity report with latest data
- Check stats of `Ethnic minorities` and `White`,  `Roma` candidate should count as `White`, `Arab` should count as `Ethnic minorities`
Include screen grabs, …
=> add new ethnic options

src/views/Exercise/Details/Vacancy/Edit.vue, src/views/Exercise/Details/Vacancy/View.vue
Issue: [User Raised Issue BR_000047](https://github.com/jac-uk/ticketing-system/issues/237)
- Add `Location (Welsh)` to the exercise.
✅ Developers
Example exercise: https://jac-admin-develop--pr2349-bugfix-ts-237-exerci-r9gcy8w6.web.app/exercise/cGgGaguvcdSVb7SsTD7Y/details/vacancy
1. Go to the "Vacancy information" of an exercise.
2. Edit the field "Location (Welsh)".
3. Check if "Location (Welsh)" is saved correctly.
---
=> Bugfix/TS 237 Exercise Location in Welsh

src/filters.js, src/views/Exercise/Reports/EligibilityIssues.vue
Closes #2231.
- Fix the "Recommendation" dropdown and "Reason for recommendation" textbox.
- Remove "Reject Non-declaration" from the issue status options.
- Add a checkbox at the top with the text "Display only candidates with Eligibility issues". This checkbox toggles between all candidates being displayed and just the ones that don't meet some or all of the criteria.
- Add a "Download SCC Annex report link" at the top of the page. The functionality will be implemented in #2300.
- Show the information as shown below with Met / Not met returned for each criterion (not met would require further manual consideration by the SET).
Note: This PR requires changes in [digital-platform: Feature/admin 2231 Eligibility Report](https://github.com/jac-uk/digital-platform/pull/1024). …
=> Feature/2231 Improve Eligibility Report functionality

src/filters.js, src/reports.js, src/views/Exercise.vue, src/views/Exercise/Dashboard/Dashboard.vue, src/views/Exercise/Reports/Diversity.vue, src/views/Exercise/Reports/Outreach.vue
Related Issue: #2275.
- Fix the diversity report when switching different processing versions.
- Fix the outreach report when switching different processing versions.
Note: This PR needs the changes in [digital-platform: Feature/admin 2275 Update reports which include stage status](https://github.com/jac-uk/digital-platform/pull/1047).
✅ Developers
✅ UTG
Example exercise: https://jac-admin-develop--pr2350-feature-2275-update-plb1q8v0.web.app/exercise/Oy4hPcHarUc0CMQau7Hh/details/overview
1. Go to an exercise and change the processing version.
2. Go to "Diversity" report and hit the "Refresh" button. Check if the stages show correctly.
3. Go to "Outreach" report and hit the "Refresh" button. Check if the stages show correctly.
🟢 No risk - this is a self-contained piece of …
=> Feature/2275 Update reports which include stage status

src/views/Exercise/Applications/Application.vue
#2326 
- Avoid calculating `fullName` twice.
✅ Developers
Example application:  https://jac-admin-develop--pr2354-feature-2326-address-0lntfdbu.web.app/exercise/b96p6e9GTAkVUhbggHom/applications/applied/application/KbaGWWL5C6oTiOHa64Sg
- Amend first name or last name.
- Check if the full name shows correctly in the application list: https://jac-admin-develop--pr2354-feature-2326-address-0lntfdbu.web.app/exercise/b96p6e9GTAkVUhbggHom/applications/applied
- Check if the full name shows correctly in the stage list: https://jac-admin-develop--pr2354-feature-2326-address-0lntfdbu.web.app/exercise/b96p6e9GTAkVUhbggHom/stages/selected
Have permissions been considered for this …
=> Feature/2326 Address candidate naming inconsistencies

src/store/assessment.js, src/views/InformationReview/AssessmentsSummary.vue
Issue: [User Raised Issue BR_000058 #247](https://github.com/jac-uk/ticketing-system/issues/247)
- Fix Firebase syntax in the store `assessment.js`.
- Check the assessment question before accessing it.
Note: The PR required the changes in [digital-platform: Bugfix/TS 247 Update Assessor Info #1054](https://github.com/jac-uk/digital-platform/pull/1054).
✅ Developers
Example exercise: https://jac-admin-develop--pr2355-bugfix-ts-247-update-qejdbf0q.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/tasks/all/independent-assessments
Example application: https://jac-admin-develop--pr2355-bugfix-ts-247-update-qejdbf0q.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/applied/application/X5ToXRooJbu9h6AVRtuA
1. Go to the application and update the information (type, full name, email) of the …
=> Bugfix/TS 247 Update Assessor Info

src/router.js, src/views/Exercise/Reports.vue, src/views/Exercise/Reports/Deployment.vue
Closes #2260 
Note: This PR needs changes in [digital-platform: Feature/admin 2260 Create Deployment Report](https://github.com/jac-uk/digital-platform/pull/1032).
✅ Developers
✅ UTG
Example exercises:
- Working preferences with ranked choice: https://jac-admin-develop--pr2348-feature-2260-create-k8ed2wp8.web.app/exercise/9JP3KOJHxrKyj2VLDiTG/reports/deployment
- Working preferences with multiple choice: https://jac-admin-develop--pr2348-feature-2260-create-k8ed2wp8.web.app/exercise/NebJYlQl4fxnUXWmrWOa/reports/deployment
- Working preferences with single choice: https://jac-admin-develop--pr2348-feature-2260-create-k8ed2wp8.web.app/exercise/vzReRrA5LPZ3sGvZKWvM/reports/deployment
1. Go to the report page and check if there is a new link "Deployment" under "Handover" in …
=> Feature/2260 Create Deployment Report

src/helpers/constants.js
Closes #2361 
- Add `Career Highlights` to the dropdown of Self Assessment with competencies.
✅ Developers
Example exercise: https://jac-admin-develop--pr2362-bugfix-2361-sa-uploa-826z1cyu.web.app/exercise/kGW2SkyaMb7M68OAN5fR/details/assessments
1. Go to "Assessment options" of an exercise.
2. Update the assessment options.
3. Tick "Self Assessment with competencies" and check if "Career Highlights" appears in the dropdown.
Screenshot:
---
=> Bugfix/2361 Ensure SA upload can handle 6 questions

src/components/ModalViews/LateApplication/Request.vue, src/store/baseClasses/messageBase.js, src/views/Exercise/Applications/List.vue
fix bug for create a late application.
✅ Developers
✅ UTG
- exercise > applications > draft > late application.
- submit form 
> no errors
---
=> Fix late application

src/views/Exercise/Externals/View.vue
closes #2254 
The problem here is that we don't want all users to be able to publish all exercises; we want Ops senior managers (but not Ops team members) to be able to publish all exercises, but we want 2/3 users to be able to publish only external exercises without having to gain approval.
we would only want Adela and Gemma (Operations  Team Member) plus Ops Senior Leaders to publish external exercises.
✅ Developers
✅ UTG
Test as user in `Operations  Team Member` group, without `Can publish an exercise as live` permission, but has following permissions:
- Can read exercises
- Can create exercises
- Can update exercises
- Change the user role  of log-in account to `Operations  Team Member` which should be `without` `Can publish an exercise as live` permission.
- Go to …
=> Allow users can edit external exercise if having update permission

src/views/Exercise/Tasks/IndependentAssessments.vue
The IA table was being rendered twice when the Requested tab was pressed and also when pressing the pagination links.
This second render was without the params so any sorting was lost.
The fix entailed removing the beforeRouteUpdate lifecycle hook from the component.
Closes jac-uk/ticketing-system#285
✅ Developers
✅ UTG
Go to an exercise which has content in its Independent Assessments table (found under the Tasks tab).
Ensure you can reorder the table by pressing the sort links at the top of each column then, while sorted, press the pagination links at the bottom of the page to ensure the sorting is maintained as you navigate through the records.
---
=> TS 285 IA Table Not Sorting Nor Paginating Properly

src/views/Exercise/Details/Eligibility/Edit.vue
A user requested that the authorisations should not be a required field, ie they should not have to specify s9(1) nor Class 1 Ticket.
Closes jac-uk/ticketing-system#288
✅ Developers
✅ UTG
1) Open a draft exercise
2) Click on the 'Eligibility Information' link in the left sidebar
3) Ensure neither of the Authorisations check boxes are checked
4) Submit the form
Repeat above checking one and both of the checkboxes can be checked and the form submitted.
---
=> Remove the required condition for the authorised field

src/views/Exercise/Reports/Agency.vue
Describe the changes included in this pull request and highlight dependencies with other repos/tickets
closes #2290 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2366-feat-2290-update-jci-t2buxw9l.web.app/exercise/6LHFYxCon9P6u96QLvwe/reports/agency#jcio
- Click `Refresh` to generate latest report data
- Check if all the applications needs JCIO are listed in the JCIO report
- Click `Export Data` to download the report, and check if the contents is correct
---
=> Update JCIO Agency Report

src/filters.js, src/helpers/constants.js, src/helpers/exerciseHelper.js
Closes [User Raised Issue BR_ADMIN_PR_000108 #305](https://github.com/jac-uk/ticketing-system/issues/305)
✅ Developers
Example exercise: https://jac-admin-develop--pr2394-bugfix-ts-305-shortl-xpjwkr7r.web.app/exercise/oNX74wd8yTHohVauj9UW/stages/review
1. Select candidates and then set status.
2. Check if `Other Passed` and `Other Failed` are available under New status.
Demo:
https://github.com/jac-uk/admin/assets/79906532/de60929d-07d0-499a-b30a-983d4950c14a
---
=> Bugfix/TS 305 Shortlisting Other Statuses

src/components/ModalViews/UploadFiles.vue
closes #2391 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2402-feat-admin-2391-limi-kdfniodr.web.app/exercise/S9V9R15MGRjCDHdcRQRZ/details/downloads/edit
- Upload the `Candidate Assessment Form` (self assessment template), is should only accept .docx.
---
=> Limit format of SA template uploads to .docx

package-lock.json, package.json, src/App.vue, src/permissions.js, src/router.js, src/store.js, src/store/releases.js, src/views/ReleasesList.vue
Added new page and route for displaying the latest releases.
Added dedicated permission to view releases.
Optionally showing link to releases page if permission applies.
**This PR relies on the following PR being deployed on the Digital Platform: https://github.com/jac-uk/digital-platform/pull/1093**
Closes #2398 
✅ Developers
✅ UTG
Go to: https://jac-admin-develop--pr2405-feature-2398-display-bdzye2m7.web.app/
**Test 1**
- Login as a Digital Super User
- Go to the Exercises page
- Click on the releases link at the top of the page (see Figure 1 below)
- The Latest Releases page should open (see Figure 2 below)
**Test 1**
- Login as a user who is NOT a Digital Super User
- Go to the Exercises page
- If you click on the releases link at the top of the page nothing should …
=> Make last release of each repo visible

package-lock.json, src/components/ModalViews/IndependentAssessorChange.vue, src/store/assessment.js, src/views/Exercise/Details/Timeline/Edit.vue
Remove hard limit date for assessments. 
Allow IA details to be changed after requests have been sent.
✅ Developers
✅ UTG
- Ensure there is no place for assessment hard limits to be entered into exercise details.
- Verify that an assessment can be submitted after the due date.
- Amend assessor details after request and see that they are reflected under the IA task.
https://github.com/jac-uk/admin/assets/44227249/abaaa549-3170-4a6d-9886-2f22abe72027
https://admin-develop.judicialappointments.digital/exercise/GYysuH7M4V21MFVM8Dzg/dashboard
---
=> 2399 IA improvments

src/store/application.js, src/views/Exercise/Applications/Application.vue, src/views/Exercise/Applications/List.vue, src/views/Exercise/Stages/Edit.vue
Updates to `store/application.js` so that a check for an accompanying `applicationRecord` can be accessed and used when withdrawing an application from the application view. 
Using this, the button now updates the withdrawn status to both if both exist, if not, only the application status is updated. 
Withdraw an application from an application view. Ensure that the status is updated and reflected in all application lists.
---
=> Statuses for withdrawn candidates

src/components/ModalViews/ReportInfo.vue, src/views/Exercise/Reports/Deployment.vue, src/views/Exercise/Reports/Handover.vue
Change titles on handover and deployment report pages and add modals with some info text.
Closes #2416 
✅ Developers
✅ UTG
**Test 1**
- go to the handover page: https://jac-admin-develop--pr2418-feature-2416-signpos-mufjgmf7.web.app/exercise/fTacPXarp6IcSonlh2VH/reports/handover
- a popup should open immediately saying: "There are now two reports for JO. The new Handover report, which contains HR details of candidates only, and the new Deployment report, which contains Location and Jurisdiction details, where relevant, only."
- see that the title has changed to: "Handover Report - HR Details only"
**Test 2**
- go to the deployment page: https://jac-admin-develop--pr2418-feature-2416-signpos-mufjgmf7.web.app/exercise/fTacPXarp6IcSonlh2VH/reports/deployment
- a popup should …
=> Signpost users to changes in Handover report

src/filters.js, src/store/applicationRecords.js, src/views/Exercise/Tasks/IndependentAssessments.vue
Closes #2419 
Related PRs:
- [digital-platform: Feature/admin 2419 Reference statuses in Independent Assessments task #1110](https://github.com/jac-uk/digital-platform/pull/1110)
- [digital-platform: Feature/admin 2419 Reference statuses in Independent Assessments task #1114](https://github.com/jac-uk/digital-platform/pull/1114)
✅ Developers
✅ UTG
Example exercises: 
- [Ryan test 1 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/IbeEVi4Vtrpv9eVFzhZq/tasks/all/independent-assessments)
- [Ryan test 2 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/FpV4enhw0yWFb9htWO7y/tasks/all/independent-assessments)
- [Ryan test 3 (Character …
=> Feature/2419 Reference statuses in Independent Assessments task

package-lock.json, package.json, src/components/Page/InformationReviewRenderer.vue, src/components/RepeatableFields/AssessmentSection.vue, src/store/application.js, src/views/Exercise/Applications/Application.vue, src/views/InformationReview/AssessmentsSummary.vue
Added ability for admin to upload/replace self assessment file and extract the content.
Added flag to application store to track status of extraction.
Closes #2411 
✅ Developers
✅ UTG
- View the following application in Admin: https://jac-admin-develop--pr2417-feature-2411-support-5ws5j0mb.web.app/exercise/Vxit8ipY8Xij340SIdrJ/applications/applied/application/L6JeIMFEdxortJAYyKOo
- Replace the uploaded self assessement file with another one
- The file should upload ok and a spinner should display whilst the content is being extracted
- Once the content is extracted it should be displayed in editable text input fields
- The word limit should be displayed next to each field (defaults to 250 words)
- Modify one of the fields until the word limit is exceeded. The save button …
=> Support self-assessment extraction on Admin

src/views/Exercise/Reports/CharacterIssues.vue
Closes #2455 
Related PR: [digital-platform: Feature/admin 2455 Add blank option to status filter menu on Character report page #1120](https://github.com/jac-uk/digital-platform/pull/1120)
✅ Developers
✅ UTG
Example exercise: [Ryan test 1 (Character issues)](https://jac-admin-develop--pr2456-feature-2455-add-bla-k48oo9hx.web.app/exercise/IbeEVi4Vtrpv9eVFzhZq/reports/character-issues)
1. Go to the "Character Issues" report.
2. Check if the "Blank" status appears in the status dropdown.
Screenshot:
---
=> Feature/2455 Add blank option to status filter menu on Character report page

src/views/Exercise/Tasks/Task/Finalised.vue
Closes #2392
✅ Developers
✅ UTG
Example exercise: https://jac-admin-develop--pr2430-feature-2392-limit-z-9rdeeby0.web.app/exercise/NmzLHCZMAsKjH3GwrCxb/tasks/all/qualifyingTest/finalised/
1. Go to "QT Merit List".
2. Check if a single band for each z-score rounded up to 2 decimal places displays in the table.
---
=> Feature/2392 Limit Z-score banding calculation to 2 decimal places

src/components/RepeatableFields/Membership.vue
Fix https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1192
- Fix exercise.otherMembership.value always be "object-inputevent"
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2473-bugfix-apply-1192-fi-xhfrt8w2.web.app/exercise/7lsEzMMY182YLyXuqyak/details/eligibility
- Add new memberships
- Apply the vacancy: https://jac-apply-develop.web.app/vacancy/7lsEzMMY182YLyXuqyak/
- Check the `Relevant memberships`, the membership options should can be selected independently. 
https://github.com/jac-uk/admin/assets/156695133/df2d9041-3a1b-43a5-a828-1b7c641c3648
Have permissions been considered for this …
=> Bugfix/apply 1192 Membership selection

src/components/Page/EditableField.vue
Closes [User Raised Issue BR_ADMIN_PR_000141 #343](https://github.com/jac-uk/ticketing-system/issues/343)
- Fix the save functionality in the `EditableField` component.
✅ Developers
Example application: https://jac-admin-develop--pr2476-bugfix-ts-343-unable-n0mpgeth.web.app/exercise/g45SG9vPFlhInL6yDonh/applications/draft/application/0h8NUJ5GPEiIBfL35Shh
Steps:
1. Go to an application and amend the data.
2. Check if the data can be saved correctly.
Demo: 
https://github.com/jac-uk/admin/assets/79906532/b86eb976-c146-4264-a5d0-9ecf2360349c
---
_can be OFF, DEVELOP or …
=> Bugfix/TS 343 Unable to amend application data

src/helpers/exerciseHelper.js, src/views/Exercise/Configuration/ProcessingVersion.vue, src/views/Exercise/Details.vue
In 'Processing version 2.0' we introduced a new set of stages and statuses.
Here we are introducing 'Processing version 3.0' which will include new Tasks (PSDQ, Sift, Selection Day etc).
_Note the new tasks were previously included in version 2 and causing confusion for SETs so this change will resolve that._
**To Do**
**Config page**
**Tasks for 2.0**
**Tasks for 3.0**
Closes #2475
Try changing processing version to 3.0 and check new tasks appear and nothing blows up! 
Try changing back to 2.0 and back again to 3.0 to try to get it to blow up 😄 
---
=> #2475 Introduce Processing Version 3.0

src/views/Exercise/Reports/StatutoryConsultation.vue
do-over of old branch with merge issues.
Alphabetical pagination on the stat-con report page was causing confusion with the stat-con download. 
I have made the pagination numerical by default so this page should always load any results, reducing confusion. 
✅ Developers
✅ UTG
visit stat con page (exercise >> reports >> statutory-consultation)
ensure pagination is numerical on initial load.
---
=> Make Pagination numerical by default

src/views/Exercise/Reports/EligibilityIssuesV2.vue
Rename `Reasons not satisfied` to `JAC comments` in the Eligibility Report.
✅ Developers
Example exercise on Production: https://jac-apply-admin-production--pr2482-hotfix-eligibility-m6wiapsd.web.app/exercise/IiaXjmpDQd7BQx7ovlv0/reports/eligibility-issues
1. Go to Eligibility Report
2. Check if `Reasons not satisfied` has been renamed to `JAC comments`
---
=> Hotfix/Eligibility Report JAC Comments

src/components/ModalViews/UploadFiles.vue, src/views/Exercise/Details/Downloads/Edit.vue
This is to fix an issue introduced in the earlier ticket to 'Limit format of SA template uploads to .docx':
Earlier Issue: https://github.com/jac-uk/admin/issues/2391
Earlier PR: https://github.com/jac-uk/admin/pull/2402
The UploadFiles component was passed a prop which originally specified a list of acceptable file types. The above PR removed that list and hardcoded the docx file extension which meant all instances of UploadFiles would only accept that file type.
As a fix I have reverted that change and have specified the docx file type for the Self Assessment template upload.
Closes jac-uk/ticketing-system#357
✅ Developers
✅ UTG
1. Go to a draft exercise at this url: https://jac-admin-develop--pr2485-bugfix-ts-357-allow-8roplgyx.web.app/
2. Go to the Exercise Downloads …
=> Ticketing System #357 Allow Pdfs To Be Uploaded When Specifying Download Files For Exercise

src/views/Exercise/Details/Assessments/Edit.vue
Mentions #2486 
✅ Developers
✅ UTG
[Example exercise](https://jac-admin-develop--pr2491-feature-2486-remove-w9dibni0.web.app/exercise/TSZHvLiBpittnlOXmMlI/details/assessments)
Steps:
1. Amend the assessment options of an exercise.
2. Ensure the CV option has been removed.
Demo:
https://github.com/user-attachments/assets/19913705-7d5b-4f21-9932-e5da27003fe8
---
=> Feature/2486 Remove CV as assessment option

src/helpers/exerciseHelper.js
Closes jac-uk/ticketing-system#362
✅ Developers
See described issue in jac-uk/ticketing-system#362 - the change here should fix it 😄 
---
=> ticketing-system#362 Application view

src/views/InformationReview/AssessmentsSummary.vue
[User Raised Issue BR_ADMIN_PR_000161 #363](https://github.com/jac-uk/ticketing-system/issues/363)
Add edit mode to self-assessment upload.
✅ Developers
[Example application](https://jac-admin-develop--pr2506-bugfix-ts-363-unable-e9jfjbzx.web.app/exercise/aD8YKYEYhQbPThjcaKsM/applications/draft/application/WSf0lOi60wyb1F4Igmic)
Steps:
1. Go to the application view.
2. Check if you can amend the reasonable adjustments.
3. Check if you can upload the self-assessment.
Demo:
[video-29921303-4da2deb56ddd0a294edeebc07212ee67.webm](https://github.com/user-attachments/assets/1288f049-5690-499e-86db-4517c548116e)
- Permissions have been added …
=> Bugfix/TS 363 Unable to amend reasonable adjustments

src/helpers/exerciseHelper.js
Closes #jac-uk/ticketing-system#365
✅ Developers
✅ UTG
---
=> fix listing can not be approved

src/App.vue
Add the programme view back to the exercises menu.
✅ Developers
Check if the "Programme view" appears under the exercises menu.
---
=> Bugfix/2458 Exercises Programme View

src/views/Exercise/Applications.vue, src/views/Exercise/Reports.vue, src/views/Exercise/Stages.vue, src/views/Exercise/Tasks.vue
Closes #2412 
✅ Developers
✅ UTG
- Go to the preview link
- Check the exercise applications view (click applications figure)
- Side bar should be removed
- Should use full width
- Check the Tasks ,Stages, Reports
- Should Use full width
---
=> remove sidebar, update styles

src/components/RepeatableFields/SelectionExerciseManager.vue, src/components/RepeatableFields/SelectionExerciseOfficer.vue, src/components/RepeatableFields/SeniorSelectionExerciseManager.vue, src/store/users.js, src/views/Exercise/Details/Contacts/Edit.vue
Closes #2505 
✅ Developers
✅ UTG
[Example exercise](https://jac-admin-develop--pr2510-feature-2505-apply-u-cilfp82k.web.app/exercise/TSZHvLiBpittnlOXmMlI/details/contacts/?referrer=exercise-show-overview)
Steps:
1. Go to the exercise contacts page.
2. Amend the "Senior selection exercise manager" fields and check if only users with the "Operations Senior Manager" role appear in the dropdown.
3. Amend the following fields and check if only users with the "Operations Team Member" role appear in the dropdown.
- Selection exercise manager
- Selection exercise officers
- Permissions have been …
=> Feature/2505 Apply user role filters on Exercise contacts page

src/store/exercise/document.js, src/views/CreateExercise.vue, src/views/Exercises.vue
Closes #2483 
✅ Developers
✅ UTG
- Go to the preview link:
- The exercise table should sort by the number part of reference number
- Create a JAC exercise, the reference number should had `JAC` prefix
- Create a Welsh government exercise, the reference number should had `GOW` prefix
- Create a external exercise, the reference number should had `EXT` prefix
---
=> change exercise reference prefix for external and Welsh GOV

src/components/RepeatableFields/StatutoryConsultee.vue, src/views/Exercise/Details/Vacancy/View.vue
[User Raised Issue BR_ADMIN_DE_000239 #342](https://github.com/jac-uk/ticketing-system/issues/342)
✅ Developers
✅ UTG
[Example exercise](https://jac-admin-develop--pr2526-bugfix-ts-342-stat-c-u197hzqh.web.app/exercise/nVYlHbW1Uivp0PsnVU3D/details/contacts/)
When Stat Con is waived, check if you can complete the contacts section without specifying a Stat Con contact.
Demo:
[video-30141148-1532855a73cc4873e598363eb3cdd513.webm](https://github.com/user-attachments/assets/4602755c-1e64-4ecb-9019-95cac94f7adb)
---
=> Bugfix/TS 342 Stat Con Contact

src/router.js, src/views/Exercise.vue, src/views/Exercise/Details/SelectionSetup/Edit.vue, src/views/Exercise/Details/SelectionSetup/View.vue
Closes #2494 
✅ Developers
✅ UTG
[Example exercise](https://jac-admin-develop--pr2520-feature-2494-amendme-7h6mlq9l.web.app/exercise/iJOImbuYiOYfF1g8MEao/details/selection-setup/)
Steps:
1. Go to an exercise.
2. Check if the "Additional settings" page name is changed to "Selection set-up".
3. Check if the radio buttons (Competencies, Skills & Abilities) appear under the "The assessment framework used in this exercise" question.
4. When Competencies is selected, check if the options are displayed correctly.
5. When Skills & Abilities is selected, check if the options are displayed correctly.
Demo:
[video-30138001-16ba69a35996745200b2b1adfb54c476.webm](https://github.com/user-attachments/assets/007be321-a5e0-44d1-9a99-a46d06c …
=> Feature/2494 Amendments to Additional settings page

src/views/Exercise/Reports.vue, src/views/Exercise/Reports/Agency.vue, src/views/Exercise/Reports/CommissionerConflicts.vue, src/views/Exercise/Reports/Custom.vue, src/views/Exercise/Reports/Deployment.vue, src/views/Exercise/Reports/Diversity.vue, src/views/Exercise/Reports/Handover.vue, src/views/Exercise/Reports/MeritList.vue, src/views/Exercise/Reports/Outreach.vue, src/views/Exercise/Reports/StatutoryConsultation.vue, src/views/Exercise/Stages.vue, src/views/Exercise/Tasks.vue, src/views/Exercise/Tasks/Task/Completed.vue
Fixes the layout of:
Note: I have removed `govuk-grid-row` from the top-level templates for Tasks, Reports and Stages. It is easier to manage if grid row and column code is together in the same file. 
Closes #2534
✅ Developers
Check all views in Admin and update the parent ticket with any additional views that need fixing
Before (content too wide)
After (content same width as header)
---
=> #2534 Fix broken layout

src/components/Form/DateInput.vue, src/components/Form/TextField.vue, src/components/Form/TextareaInput.vue, src/components/Page/EditableField.vue, src/components/Page/InformationReviewRenderer.vue, src/views/InformationReview/AssessmentsSummary.vue, src/views/InformationReview/PersonalDetailsSummary.vue
Added validation to the application edit screen.
Closes #2471 
✅ Developers
✅ UTG
- Go to an exercise with some applications and open one of them, for example: https://jac-admin-develop--pr2533-feature-2471-add-val-7q46xm8x.web.app/exercise/9OEv0lIZ4N8SWPmWJ4sx/applications/applied/application/jglQ5IG3HgOLNVeBwcYx
- Click the edit button
- Try to empty some of the required fields such as title, first name, date of birth and statutory eligibility requirement (when set to 'Yes' the textarea should be required) and when you press the 'save' button you should get an error
- Try to empty on of the non-required fields such as middle name. This should be allowed.
https://github.com/user-attachments/assets/19d5fcf1-2de4-4723-8232-b …
=> #2471 Add validation to the exercise application edit screen

src/store/releases.js, src/views/ReleasesList.vue
Display the date and time the releases were last fetched and indicate explicitly if data isnt currently available as the Zenhub API is a bit flaky.
https://jac-admin-develop--pr2546-hotfix-update-releas-a6fko0le.web.app/latest-releases
✅ Developers
✅ UTG
Ensure the date and time that the data was fetched is displayed along with the data. If there is no data then ensure it displays a message saying it is 'unavailable'.
---
=> Update releases to display last fetched date time

src/helpers/exerciseHelper.js, src/views/Exercise/Details/Overview.vue
- Hide `Submit for approval` button if the exercise advert is `basic` or `listing`.
✅ Developers
[Example exercise](https://jac-admin-develop--pr2555-bugfix-ts-373-approv-iwpfc0je.web.app/exercise/Biyjd07Xz2usL9yXjtjV/details/overview)
Steps:
1. Go to an exercise and change the advert type to `listing` or `basic`.
3. Check if "Submit for approval" is invisible. 
Demo:
https://github.com/user-attachments/assets/5d29c00a-0956-4238-8d2a-dd31e7d9b776
---
=> Bugfix/TS 373 Approve Exercise with Basic Advert

src/views/Exercise/Reports/Custom.vue
Did some investigation work for @nickaddy.
The only code change was to ensure the applied status is checked on page load
Closes #2544 
✅ Developers
✅ UTG
When you go to the custom report page the 'Applied' Application status should be checked by default
---
=> #2544 Custom report data overflow - Make applied checked on page load

src/store/exercise/document.js
Closes #2566 
- Filter ignored fields when copying an exercise.
✅ Developers
1. Find an exercise and copy the exercise to clipboard.
2. Submit the exercise for approval and publish it once approved.
3. Check if you can create test applications.
Demo:
https://github.com/user-attachments/assets/303a34e8-be34-43e6-b7ce-634998fa7e86
---
=> Bugfix/2566 Functionality of Copying Exercise

src/components/RepeatableFields/QuestionConfig.vue
We were receiving the following sass warning:
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in & {}.
This does not need testing
---
=> Fix sass warning for nested rules

src/views/Exercise/Reports/Diversity.vue
Fix [User Raised Issue BR_ADMIN_PR_000213 #414](https://github.com/jac-uk/ticketing-system/issues/414).
Related PR: [digital-platform: Bugfix/TS 414 Passed SD in Diversity Report #1229](https://github.com/jac-uk/digital-platform/pull/1229).
✅ Developers
[Example exercise](https://jac-admin-develop--pr2589-bugfix-ts-414-passed-pglejj4n.web.app/exercise/Biyjd07Xz2usL9yXjtjV/reports/diversity)
1. Go to the Diversity Report of an exercise.
2. Check if the stats of "Passed SD" are correct.
---
=> Bugfix/TS 414 Passed SD in Diversity Report

src/views/Exercise/Applications/Application.vue
- Fix starting date of character information v3.
✅ Developers
[Example application (old character questions)](https://jac-admin-develop--pr2590-bugfix-character-inf-9vxen0b8.web.app/exercise/y27ibpzogMIDluD5Wwc2/applications/draft/application/o1MQA6dkJIluJQrL1Efw)
[Example application (new character questions)](https://jac-admin-develop--pr2590-bugfix-character-inf-9vxen0b8.web.app/exercise/Biyjd07Xz2usL9yXjtjV/applications/applied/application/FXnA5A6P23E1E5XQTy0a)
1. Go to an application view of an exercise.
2. Check if the character information section shows correctly.
- Permissions have …
=> Bugfix/Character Information v3 in Application View

src/views/Exercise/Tasks/Task/Completed.vue
Fix call to send generic report feedback notification from this original PR: https://github.com/jac-uk/digital-platform/pull/1014
Closes #2577 
✅ Developers
✅ UTG
- Go to the following url: https://jac-admin-develop--pr2596-feature-2577-update-6w0hsi9s.web.app/exercise/AwRoe9iF2ufJ6MWJqACf/tasks/all/situationalJudgement/completed
- Press the 'send report notification' button
- Success should appear on the button
- An email should be sent to the candidates for this exercise
---
=> Updates to QT tasks on Admin

src/components/ModalViews/IndependentAssessorChange.vue, src/filters.js, src/views/Exercise/Dashboard/OverviewPanels/TypeOfExercise.vue, src/views/InformationReview/AssessorsSummary.vue
Two issues were reported, one had a ticket raised for it but they are connected so both go fixed in this ticket.
The issues arise because of overlapping references being used in the lookup helper.
**Issue 1)** 'Professional assessor' was being displayed next to occupation. This got flagged by a candidate and reported in the support channel. The fix involved removing the word assessor and hardcoding that in the template. This is a bit of a hack so will be nice to modify the way we do this lookup in the future to prevent this issue from arising again as it surely will.
**Issue 2)** The exercise type field was displaying 'Strategic Leadership Questions' instead of 'Leadership'.
Closes #2600 
Closes #2601 
✅ Developers
✅ UTG
**1) Go to the following url : …
=> Correct Incorrect Text Appearing Due To Lookups

src/views/Exercise/Reports/Custom.vue
As an Admin, I would like to be able to add selected fields to a custom report before generating data so that the process is more time-efficient.
Closes #2547 
✅ Developers
✅ UTG
Go to the following page: https://jac-admin-develop--pr2599-feature-2547-improve-w9zbe8i1.web.app/exercise/R5mu47EVqEPf1WbXsLfZ/reports/custom
Test 1
- Ensure the Application Status and Status filters no longer display in the page
- Ensure the Candidate Ref No, Full Name and Application Status fields are selected by default
- Ensure the 'Generate Report' button is visible and enabled (ie dark green), whilst the 'Download Report' button is disabled (pale green/grey)
- After pressing the 'Generate Report' button the page should scroll and the data should load (after a short time). Once the data has …
=> #2547 Improvements to Custom report v2.1

src/helpers/exerciseHelper.js, src/views/Exercise/Dashboard/Dashboard.vue, src/views/Exercise/Dashboard/OverviewPanels/TotalApplications.vue
closes #2579 
✅ Developers
✅ UTG
Go to the [preview URL](https://jac-admin-develop--pr2605-feat-2579-exercise-d-u61utu9s.web.app/) and check: 
---
=> Feature/2579 Exercise dashboard iteration

src/views/Exercise/Reports/Custom.vue
Fixed issue escaping newline chars when downloading the csv file. Previously the newline characters were causing some of the content to appear in the wrong column in the report.
Closes jac-uk/ticketing-system#428
✅ Developers
✅ UTG
Go to the following url: https://jac-admin-develop--pr2615-bugfix-ts-428-custom-mzq008u1.web.app/exercise/R5mu47EVqEPf1WbXsLfZ/reports/custom
Generate the report with the columns: 
- Candidate referenceNumber
- Fee paid or salaried sitting day details
... then download the report.
Ensure that no '/n' characters appear in the report and the application referencenNumbers only appear in the left hand column. Generally the report should look fine.
---
=> Ticketing System #428 Custom Report NewlIne Chars On Download

src/store/candidates.js, src/views/Candidates/CandidatesView.vue
Details in the candidate view, (Character Information, Equality and Diversity) were getting stuck when looking through different individuals, in circumstances when there were no answers. 
(ie. candidate A has answers for Char Info and E&D survey, Candidate B has none, Navigating to candidate A, then to Candidate B, you see candidate A's answers for Char Info and E&D).
✅ Developers
✅ UTG
Ensure no answers persist when looking through different candidates. 
- Start from each of the below urls
- Navigate to the candidate list
- then to any candidate with 0 applications (or any candidate with no char info/e&d data).
| Develop | Preview |
|---|---|
| [Candidate with Char Info and E&D](https://admin-develop.judicialappointments.digital/candidates/pdg1OwBW2aY5H9qSh6lP2AZo1Vf2) | …
=> Data persistence in candidate views

src/views/Exercise/Reports/Diversity.vue
Related issue: [User Raised Issue BR_ADMIN_PR_000268 #489](https://github.com/jac-uk/ticketing-system/issues/489)
- Fix change calculations.
✅ Developers
[Example exercise on Production](https://jac-apply-admin-production--pr2637-bugfix-ts-489-diver-44uytrzn.web.app/exercise/phf3iabh5KDhRiw4f4xm/reports/diversity)
Steps:
1. Go to the Diversity Report of an exercise.
2. Check if the changes are calculated correctly.
---
=> Bugfix/TS 489 Diversity Report Change Calculations

src/helpers/exerciseHelper.js, src/helpersTMP/Timeline/exerciseTimeline.js, src/router.js, src/store.js, src/store/exercise/reports/sccSummary.js, src/views/Exercise/Reports/SccSummary.vue, tests/unit/helpers/exerciseHelper.test.js
Closes #2631
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2641-feat-2631-scc-report-w5b13tuh.web.app/exercise/0ySRDHmWM8ARVxSCw7zv
- Click `SCC Summary Page` of reports menu.
- The SCC summary should have data.
- Enter customised fields and click Download SCC Summary, the SCC data should be included.
🟢 No risk - this is a self-contained piece of worke
---
=> Feature/2631 SCC Report Summary page 

src/helpers/exerciseHelper.js, src/views/Exercise/Details/Preferences/View/AdditionalWorkingPreferences.vue, src/views/Exercise/Reports/Custom.vue, src/views/InformationReview/PreferencesSummary.vue
closes #2320 
✅ Developers
✅ UTG
- Working preferences
- Go to the preview link: https://jac-admin-develop--pr2650-feat-2320-latest-wor-uenvqol7.web.app/exercise/oxz5BfzoJFMKWrvHHpBP/reports/custom
- Select working preference fields.
- Generate custom report.
- Non legal exercise experience
- Go to the preview link: https://jac-admin-develop--pr2650-feat-2320-latest-wor-uenvqol7.web.app/exercise/qxYX2i69L7k8pbzqRHyq/reports/custom
- Select experience field.
- Generate custom report. 
---
=> Update Custom report with latest working preferences

src/views/CreateExercise.vue, src/views/Exercise/Details/Overview.vue
Selection set-up has been added to the task list page and the create exercise page.
Closes jac-uk/ticketing-system#490
✅ Developers
✅ UTG
Go to this url: https://jac-admin-develop--pr2636-bugfix-ts-490-missin-uwi0wv3a.web.app/
**Test 1**
- Create a new exercise
- Ensure the Selection Setup appears in the Create An Exercise page, see figure 1 below
**Test 2**
- Ensure the Selection Setup appears in the Task List page, see figure 2 below
**Figure 1**
Figure 2
---
=> TS 490 Add selection setup to task list and create exercise page

src/views/Exercise.vue
Recent changes to tighten user permissions on cloud functions and UI features had introduced, or highlighted, a bug with the 'Create demo applications' buttons. There are two buttons with this label and only one had been updated with the correct permissions. This small PR fixes that.
The 'Create demo applications' button should only be displayed for user who have the `canCreateTestApplications` permission in their user role:
✅ Developers
You'll need a published approved exercise which does not have any applications. This one might work (for a while until someone creates applications!): 
https://jac-admin-develop--pr2678-bugfix-permissions-c-gxp3i72z.web.app/exercise/irlE2FKZJnFLOYAIsRHx/dashboard
Check the following:
- If the logged in user does not have permission to …
=> Bugfix: Permissions for 'Create demo applications'

src/views/Exercise/Reports/Handover.vue
https://github.com/jac-uk/digital-platform/pull/1311
Ensure table displays columns not intended for download. Strip the columns out for the download.
This is connected to the DP PR: https://github.com/jac-uk/digital-platform/pull/1311
✅ Developers
✅ UTG
Go to the handover report page.
Ensure the table displays the application reference and applicant's full name.
When the report is downloaded ensure the application id and reference and also the candidate fullname is not in the report.
The report format should match that of the JO Handover report.
See the parent ticket: https://github.com/jac-uk/digital-platform/issues/1310
🔴 High risk - this includes a …
=> DP 1310 Updates To handover Report To Align With JO 

src/views/Exercise/Reports/Agency.vue
closes #2667 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-apply-admin-production--pr2681-feat-2667-add-missi-kng012ty.web.app/exercise/WqosC7DVN0GuOfYee3dy/reports/agency
- Click refresh button
- Download all the reports of each tabs (ACRO, SRA, JCIO, HMRC, Other)
- Check the downloads have following fields
- Title
- First Name
- Middle name(s)
- Last Name or Company Name
- Suffix
- Previous known name(s)
- Professional names
- Any Other Names used
---
=> Admin #2667 Add missing fields to Agency report downloads 

package-lock.json, package.json, tests/unit/store/exercise/collection.spec.js, tests/unit/store/exercise/document.spec.js
closes #2646 
- Remove `firebase-mock`used in tests, the package have vulnerability, but is not maintained.
✅ Developers
- Run `npm i`.
- Run `npm audit` and check there is no vulnerablilites.
- Run tests.
---
=> Identify & Fix NPM Vulnerabilities in all Repositories - January

src/views/Exercise/Tasks/Task/Panel/View.vue
Related PR: [Feature/1222 Change of panel packs location #1315](https://github.com/jac-uk/digital-platform/pull/1315)
- Display an error message on panel packs if the exercise folder can not be found in Google Drive.
✅ Developers
✅ UTG
1. Go to a panel and click the "Export to google drive" button.
2. Go to Google Drive and check if the panel packs are generated in the location `JAC00082`.
3. Click the "Export to google drive" button again and check if the panel packs are generated in the new folder.
https://github.com/user-attachments/assets/d1c310c2-d97c-4877-b6a0-42c526681e3f
1. Go to a panel and click the "Export to google drive" button.
2. Check if the error message `Folder not found - please rename root exercise folder according to the reference number of the …
=> Feature/DP 1222 Change of panel packs location

src/views/Exercise/Tasks/Task/Completed.vue
Tidies up the PSDQ completed screen. 
**Before**
It was trying to display a merit list, even though PSDQ task does not involve merit.
**Now**
The page shows headline stats only, not the merit list.
Closes #2663
✅ Developers
✅ UTG
[Preview URL](https://jac-admin-develop--pr2664-feature-2663-guwxiqxq.web.app/)
Note: You will need an exercise with a completed PSDQ
Check that the PSDQ completed screen displays as described above, and does not include a merit list.
---
=> #2663 Bugfix: PSDQ completed. Remove merit list, show stats

src/views/Exercise/Details/Overview.vue
Closes #2692
The `Selection set-up` option appears twice in the list onscreen:
Steps to reproduce the behaviour:
1. Create a new exercise
2. Go to the Overview page and scroll down to the bottom of the list
3. See duplicate entry
`Selection set-up` should only appear once in the list onscreen.
---
=> #2692 Bugfix: Selection set-up appearing twice

src/views/Exercise/Details/Timeline/Edit.vue, src/views/Exercise/Tasks/Task/CandidateForm/Configure.vue, src/views/Exercise/Tasks/Task/CandidateForm/Panellist.vue
closes #2679 
✅ Developers
✅ UTG
- Go to the preview link: https://jac-admin-develop--pr2698-feat-admin-2679-ui-a-6hpryh1n.web.app/
- Test 1. The `Pre Selection Day Questionnaire` dates on of timeline should be optional:
- Go to the preview link: https://jac-admin-develop--pr2698-feat-admin-2679-ui-a-6hpryh1n.web.app/exercise/vFQI4CMwzhFwV7OzDxUX/details/timeline/?referrer=exercise-show-overview
- This preview link is only for testing `Pre Selection Day Questionnaire` dates, do not use it to test other PSDQ functions.
- The fields should be optional.
- If the dates are not set, the Pre Selection Day Questionnaire should not appear in task menu.
- Test 2. The set up of `candidate availability` in `Pre Selection Day Questionnaire` task:
- Go to the preview link: …
=> Feat/admin 2679 UI amendments to pre sd workflow

src/components/QuestionConfig/View.vue, src/components/RepeatableFields/QuestionConfig.vue, src/views/InformationReview/PreferencesSummary.vue
The 'First-tier Tribunal Medical Members SEC' exercise needs a couple of questions added to it.
We have modified the Additional Working Preferences Questions so that they use rich html inputs to give more control over the appearance of the questions.
- Make the additional working prefs questions use a rich html input
- Ensure questions display correctly.
- Ensure the text isnt bold when the input is html.
Closes #2710 
✅ Developers
✅ UTG
- Go to the following exercise: https://jac-admin-develop--pr2711-feature-2710-add-que-tndi9x2j.web.app/exercise/oMVaKLPbEzR89VoJl6yi/dashboard
- Add/Modify the Additional Working Preferences Questions and ensure they display correctly on any relevant screen in admin
- Go to the associated ticket in Apply and check the url there to  ensure …
=> #2710 Add Questions To Pre-Existing Exercise

src/helpers/scoreSheetHelper.js
Closes #2704 
In the Scenario Test task, when scoresheet data is pasted it appears not all data is being saved
✅ Developers
https://jac-apply-admin-production--pr2705-bugfix-2704-dxbzgv0y.web.app/
1. Go to Tasks > Scenario Test for an exercise where the ST has been completed and scored
2. Follow the on-screen instructions with regards naming the columns in the scoresheet
3. Copy the contents of the scoresheet to your clipboard (Ctrl+A to select all; Ctrl+C to copy) and use the 'Paste from clipboard' button in Admin
4. Observe that 'With scores' reports a number that matches the complete rows pasted in from the scoresheet
Actual
Expected
---
=> #2704 Bugfix: Scenario Test. Importing scoresheet

src/permissions.js
Adds a new permission to allow SETs to view panellist data. The panellist permissions are now:
**Can manage panellist data**
Allows user to view the panellist database and add, edit and delete panellists
**Can view panellists** 
Allows user to view panellist data but not manage it. For example the user will be able to view a dropdown of panellists when creating/editing Panels
Closes #2707 
✅ Developers
Login as a user with the new 'Can view panellists' permission and without the 'Can manage panellist data' permission
Locate an exercise with a panel task (e.g. sift, selection day)
Edit a panel and try to update panellists
**Before** (use admin-develop)
Unable to update panellists
**Now** (use preview URL provided in comments of this PR)
Able to update panellists
Also please …
=> #2707 Permission: can view panellists

src/components/QuestionConfig/View.vue, src/components/RepeatableFields/QuestionConfig.vue, src/views/Exercise/Reports/Custom.vue, src/views/InformationReview/PreferencesSummary.vue
Remove the status field and replace it with the Status (Admin) field as a default
Closes #2703 
✅ Developers
✅ UTG
Ensure the Status(Admin) field appears in the default fields instead of the Status field (see screenshot below).
Press the Generate Report button and ensure the fields display ok.
Press the Download Report button and ensure the fields display correctly in the downloaded file.
---
=> #2703 Amendment To Custom Report Default Fields
